/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Intel Arc B580 (device tag b580): SDPA prefill base
// rows for the device string "bmg g21" only (openspec/changes/
// sarc-1.5-b580-prefill-refine; generated by its tools/gen_b580.py). Not part
// of a release.
//
// Same mechanism as Xe2Sdpa.cpp: kUnverified rows (ET_VK_SARC_UNVERIFIED=1)
// that match only while ET_VK_SARC_DEV_PROFILE names a b580-* profile, so
// every other configuration selects exactly what the release tables select.
// The b580-* profiles (Overrides.cpp) then pick this card's kernels by name.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

#include <cstdlib>
#include <cstring>

namespace vkcompute {
namespace sarc {
namespace {

bool b580_profile_requested(const DeviceInfo&) {
  const char* e = std::getenv("ET_VK_SARC_DEV_PROFILE");
  return e != nullptr && std::strncmp(e, "b580-", 5) == 0;
}

const Row kB580SdpaRows[] = {
    {"bmg g21", b580_profile_requested, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g44s16m8nf",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"bmg g21", b580_profile_requested, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_sweep_t64x64k32g44s16m8",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_rows(
        kB580SdpaRows, sizeof(kB580SdpaRows) / sizeof(kB580SdpaRows[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
