/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Intel Arc B580 (device tag b580): linear candidate
// rows of openspec/changes/sarc-1.5-b580-prefill-refine (generated by its
// tools/gen_b580.py). Selected only by name: ET_VK_SARC_DQ8CA_VARIANT or a
// b580-* profile.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

namespace vkcompute {
namespace sarc {
namespace {

const Row kB580LinearCandidates[] = {
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_b580bt_t64x128k64g84s16m8",
     {64, 128, 64, 8, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_b580bt_t64x128k64g88s16m8",
     {64, 128, 64, 8, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_b580bt_t128x128k32g84s16m8",
     {128, 128, 32, 8, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_candidates(
        kB580LinearCandidates,
        sizeof(kB580LinearCandidates) / sizeof(kB580LinearCandidates[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
