/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Jetson Orin (device tag orin): SDPA prefill rows
// (openspec/changes/sarc-1.5-orin-prefill-refine; generated by its
// tools/gen_orin_sdpa.py). Not part of a release.
//
// The release tables have no Orin SDPA row, and impl/sarc/SdpaCoopmat.cpp
// builds the SARC SDPA path (spec constants, truncated softmax) only on a
// device with an active SDPA row. The rows below are that row, from the dev
// zone: kUnverified (so they need ET_VK_SARC_UNVERIFIED=1) and matching only
// while ET_VK_SARC_DEV_PROFILE names an orin-* profile other than orin-lin-*,
// so every other configuration of a dev build selects exactly what the release tables
// select. WG_TILE_K of the base rows is 32, which the spec constants assume.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

#include <cstdlib>
#include <cstring>

namespace vkcompute {
namespace sarc {
namespace {

// orin-lin-* profiles change linear kernels only and leave attention alone.
bool orin_profile_requested(const DeviceInfo&) {
  const char* e = std::getenv("ET_VK_SARC_DEV_PROFILE");
  return e != nullptr && std::strncmp(e, "orin-", 5) == 0 &&
      std::strncmp(e, "orin-lin-", 9) != 0;
}

const Row kOrinSdpaRows[] = {
    {"tegra orin", orin_profile_requested, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_4070ti_t128x64k32g42s32",
     {128, 64, 32, 4, 2, 32, 16, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"tegra orin", orin_profile_requested, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_4070ti_t64x64k32g42s32",
     {64, 64, 32, 4, 2, 32, 16, false}, kBufBuf, nullptr,
     Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_rows(kOrinSdpaRows, sizeof(kOrinSdpaRows) / sizeof(kOrinSdpaRows[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
