/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Intel Xe2 (device tag xe2): linear candidate rows of
// openspec/changes/sarc-1.5-xe2-prefill-refine (generated by its tools/gen_xe2.py).
// Selected only by name: ET_VK_SARC_Q4GSW_VARIANT / ET_VK_SARC_DQ8CA_VARIANT or
// an xe2-* profile. The sarc_dev_prof_* rows are MEASUREMENT ONLY: they write
// shader-clock phase counters over their output.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

namespace vkcompute {
namespace sarc {
namespace {

const Row kXe2LinearCandidates[] = {
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_prof_q4gsw_t128x128k16g44s16m8flip", {128, 128, 16, 4, 4, 16, 8, false},
     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_prof_dq8ca_zpg_t256x64k32g48s16m8p", {256, 64, 32, 4, 8, 16, 8, false},
     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_candidates(
        kXe2LinearCandidates,
        sizeof(kXe2LinearCandidates) / sizeof(kXe2LinearCandidates[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
