/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Intel Xe2 (device tag xe2): linear candidate rows of
// openspec/changes/sarc-1.5-xe2-prefill-refine (generated by its tools/gen_xe2.py).
// Selected only by name: ET_VK_SARC_Q4GSW_VARIANT / ET_VK_SARC_DQ8CA_VARIANT or
// an xe2-* profile. The sarc_dev_prof_* rows are MEASUREMENT ONLY: they write
// shader-clock phase counters over their output.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

namespace vkcompute {
namespace sarc {
namespace {

const Row kXe2LinearCandidates[] = {
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_prof_q4gsw_t128x128k16g44s16m8flip", {128, 128, 16, 4, 4, 16, 8, false},
     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_prof_dq8ca_zpg_t256x64k32g48s16m8p", {256, 64, 32, 4, 8, 16, 8, false},
     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_prof_dq8ca_coopmat_zpg_bt_t128x128k64g84s16m8p", {128, 128, 64, 8, 4, 16, 8, false},
     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t128x64k32g44s16m8",
     {128, 64, 32, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t128x64k32g24s16m8",
     {128, 64, 32, 2, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_bt_t128x64k32g24s16m8",
     {128, 64, 32, 2, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t128x64k32g42s16m8",
     {128, 64, 32, 4, 2, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_bt_t128x64k32g42s16m8",
     {128, 64, 32, 4, 2, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t256x64k32g44s16m8",
     {256, 64, 32, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t256x64k32g28s16m8",
     {256, 64, 32, 2, 8, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t128x128k32g44s16m8",
     {128, 128, 32, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_bt_t128x128k32g44s16m8",
     {128, 128, 32, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t256x128k32g48s16m8",
     {256, 128, 32, 4, 8, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_linear_dq8ca_coopmat_zpg_sweep_t128x64k64g44s16m8",
     {128, 64, 64, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_bt_t128x64k64g44s16m8",
     {128, 64, 64, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t256x64k32g48s16m8",
     {256, 64, 32, 4, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t128x64k64g44s16m8",
     {128, 64, 64, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t128x64k64g48s16m8",
     {128, 64, 64, 4, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t128x64k32g48s16m8",
     {128, 64, 32, 4, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t256x128k32g88s16m8",
     {256, 128, 32, 8, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t128x128k32g88s16m8",
     {128, 128, 32, 8, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t128x64k32g44s16m8",
     {128, 64, 32, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t256x64k32g416s16m8",
     {256, 64, 32, 4, 16, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t128x128k64g84s16m8",
     {128, 128, 64, 8, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t64x128k64g82s16m8",
     {64, 128, 64, 8, 2, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t64x64k128g42s16m8",
     {64, 64, 128, 4, 2, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kDq8caLinear,
     "sarc_dev_linear_dq8ca_coopmat_zpg_xe2bt_t64x64k64g42s16m8",
     {64, 64, 64, 4, 2, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2bx_t128x128k16g44s16m8fli",
     {128, 128, 16, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2bx_t128x128k16g44s16m8fliw",
     {128, 128, 16, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2bx_t128x128k32g44s16m8fli",
     {128, 128, 32, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2bx_t256x128k16g48s16m8fli",
     {256, 128, 16, 4, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2bx_t128x128k16g44s16m8flib",
     {128, 128, 16, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2bx_t256x128k16g48s16m8flib",
     {256, 128, 16, 4, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2s_t256x256k16g88s16m8flib",
     {256, 256, 16, 8, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2s_t256x128k16g48s16m8flib",
     {256, 128, 16, 4, 8, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2s_t128x256k16g84s16m8flib",
     {128, 256, 16, 8, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_dev_linear_q4gsw_coopmat_xe2s_t128x128k16g44s16m8flib",
     {128, 128, 16, 4, 4, 16, 8, false}, kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t128x128k32g44s16m8fli",
     {128, 128, 32, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t128x256k16g44s16m8fli",
     {128, 256, 16, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t64x128k16g42s16m8fli",
     {64, 128, 16, 4, 2, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t128x64k16g24s16m8fli",
     {128, 64, 16, 2, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t128x128k16g24s16m8fli",
     {128, 128, 16, 2, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t128x128k32g24s16m8fli",
     {128, 128, 32, 2, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
    {"", nullptr, Op::kQ4gswLinear,
     "sarc_linear_q4gsw_coopmat_sweep_t128x128k16g44s16m8flib",
     {128, 128, 16, 4, 4, 16, 8, false}, kTex3dTex2d, nullptr, Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_candidates(
        kXe2LinearCandidates,
        sizeof(kXe2LinearCandidates) / sizeof(kXe2LinearCandidates[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
