/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Intel Xe2 (device tag xe2): SDPA prefill rows for the
// Arc B580 / Arc Pro B70 (openspec/changes/sarc-1.5-xe2-prefill-refine;
// generated by its tools/gen_xe2.py). Not part of a release.
//
// The release tables have no Intel SDPA row, and impl/sarc/SdpaCoopmat.cpp
// builds the SARC SDPA path (spec constants, truncated softmax) only on a
// device with an active SDPA row. The base rows below are that row, from the
// dev zone: kUnverified (so they need ET_VK_SARC_UNVERIFIED=1) and matching
// only while ET_VK_SARC_DEV_PROFILE names an xe2-* profile, so every other
// configuration of a dev build selects exactly what the release tables select.
// Kernels: the 780M sweep twins built for the shapes Xe2 exposes (MMA 8x16x16
// fp16 x fp16 -> fp32, subgroup 16); WG_TILE_K of the base rows is 32, which
// the spec constants assume.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

#include <cstdlib>
#include <cstring>

namespace vkcompute {
namespace sarc {
namespace {

bool xe2_profile_requested(const DeviceInfo&) {
  const char* e = std::getenv("ET_VK_SARC_DEV_PROFILE");
  return e != nullptr && std::strncmp(e, "xe2-", 4) == 0;
}

const Row kXe2SdpaRows[] = {
    {"bmg g21", xe2_profile_requested, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g44s16m8nf",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"bmg g21", xe2_profile_requested, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_sweep_t64x64k32g44s16m8",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"bmg g31", xe2_profile_requested, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g44s16m8nf",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"bmg g31", xe2_profile_requested, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_sweep_t64x64k32g44s16m8",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
};

// Selected only through an xe2-* profile (impl/sarc_dev/Overrides.cpp).
const Row kXe2SdpaCandidates[] = {
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g44s16m8nf",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g44s16m8",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g48s16m8nf",
     {128, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t128x64k32g24s16m8nf",
     {128, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t64x64k32g44s16m8nf",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t64x64k32g24s16m8nf",
     {64, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t64x128k32g44s16m8nf",
     {64, 128, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_sweep_t64x128k32g84s16m8nf",
     {64, 128, 32, 8, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t128x64k32g44s16m8nf",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t128x64k64g44s16m8nf",
     {128, 64, 64, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t128x64k32g48s16m8nf",
     {128, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t128x64k32g24s16m8nf",
     {128, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t64x64k32g44s16m8nf",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t64x64k64g44s16m8nf",
     {64, 64, 64, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t64x128k32g44s16m8nf",
     {64, 128, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_pk_t64x128k32g84s16m8nf",
     {64, 128, 32, 8, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_sweep_t64x64k32g44s16m8",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t64x64k32g44s16m8",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t64x64k32g24s16m8",
     {64, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t64x64k32g48s16m8",
     {64, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t128x64k32g44s16m8",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t128x64k32g48s16m8",
     {128, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t64x128k32g44s16m8",
     {64, 128, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t64x128k32g84s16m8",
     {64, 128, 32, 8, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t128x128k32g48s16m8",
     {128, 128, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t128x128k32g88s16m8",
     {128, 128, 32, 8, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_ml_t32x64k32g42s16m8",
     {32, 64, 32, 4, 2, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t128x64k32g44s16m8nf",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t128x64k32g48s16m8nf",
     {128, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t128x64k32g24s16m8nf",
     {128, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t128x64k64g44s16m8nf",
     {128, 64, 64, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t64x64k32g44s16m8nf",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t64x64k32g24s16m8nf",
     {64, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t64x64k64g44s16m8nf",
     {64, 64, 64, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t64x128k32g44s16m8nf",
     {64, 128, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaQk,
     "sarc_sdpa_qk_coopmat_xe2_t64x128k32g84s16m8nf",
     {64, 128, 32, 8, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t64x64k32g44s16m8",
     {64, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t64x64k32g24s16m8",
     {64, 64, 32, 2, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t64x64k32g48s16m8",
     {64, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t128x64k32g44s16m8",
     {128, 64, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t128x64k32g48s16m8",
     {128, 64, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t64x128k32g44s16m8",
     {64, 128, 32, 4, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t64x128k32g84s16m8",
     {64, 128, 32, 8, 4, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t128x128k32g48s16m8",
     {128, 128, 32, 4, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t128x128k32g88s16m8",
     {128, 128, 32, 8, 8, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
    {"", nullptr, Op::kSdpaAv,
     "sarc_sdpa_av_coopmat_xe2_t32x64k32g42s16m8",
     {32, 64, 32, 4, 2, 16, 8, false}, kBufBuf, nullptr,
     Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_rows(kXe2SdpaRows, sizeof(kXe2SdpaRows) / sizeof(kXe2SdpaRows[0]));
    register_candidates(
        kXe2SdpaCandidates,
        sizeof(kXe2SdpaCandidates) / sizeof(kXe2SdpaCandidates[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
