#!/usr/bin/env python3
"""gen_orin_prof.py: measurement-only phase-timing (PROF) twins for the Jetson Orin.

  glsl/sarc_dev/sarc_dev_prof_orin_q4gsw{.glsl,.yaml}                    4w: the two tiles the Orin ships
  glsl/sarc_dev/sarc_dev_prof_orin_dq8ca_bf{.glsl,.yaml,_body.glslh}     8da4w: the whole-texel twins (gen_orin_bf.py)
  impl/sarc_dev/Overrides.cpp   `// >>> orin prof-q4gsw-rows`, `// >>> orin prof-dq8ca-rows`

The shipped 8da4w kernel is the one the 4070 Ti ships; its twin exists already
(sarc_dev_prof_4070ti_dq8ca_zpgtr, token t128x128k64g44s32mk32rap) and is used as it is.
4w: the phase counters do not depend on the tile, so the Orin twins are new VARIANTS of the 4070 Ti campaign's
PROF body (sarc_dev_prof_4070ti_q4gsw_body.glslh, included unchanged): t256x128k16g22s32 (fp16 accumulation) and
t128x128k32g42s32f32, parameters copied from the release yaml.
8da4w bf: the PROF declarations and output block are taken from the 4070 Ti twin's body and the same ticks are
placed in the orin_bf body; with ONE_SLICE the second barrier of a chunk is counted as `barrier`.
Counters and decode as in the sibling: subgroup 0 of every workgroup overwrites the first 8 output elements of its
tile with [barrier, fetch, mma, lds_store] / iterations and [prologue, group_epilog, drain, write] / 64
(prof_decode.py). The outputs are wrong by construction; the twins are selected only by name
(ET_VK_SARC_Q4GSW_VARIANT / ET_VK_SARC_DQ8CA_VARIANT=<token ending in p>) and are never part of a profile."""
import pathlib, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ET = pathlib.Path(__file__).resolve().parents[4]
ops = ET / "backends/vulkan/runtime/graph/ops"; root = ops / "glsl"
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, Jetson Orin, MEASUREMENT ONLY: phase-timing twin of %s
 * (generated by gen_orin_prof.py; see openspec/changes/sarc-1.5-orin-prefill-refine). Its output is
 * overwritten with cycle counts, so it must never be selected for a model.
 */

"""
YH = "# SARC development zone, Jetson Orin, MEASUREMENT ONLY (phase timing, generated by gen_orin_prof.py). Never shipped.\n\n"
def defaults(path):
    y = (root / path).read_text(); return y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
def variant(path, name):
    y = (root / path).read_text(); i = y.index(f"    - NAME: {name}\n") + len(f"    - NAME: {name}\n"); out = ""
    for l in y[i:].splitlines(keepends=True):
        if not l.startswith("      "): break
        out += l
    return out

# ---------------- 4w: Orin variants of the existing PROF body ----------------
F4 = "sarc_dev_prof_orin_q4gsw"
w = (root / "sarc_dev/sarc_dev_prof_4070ti_q4gsw.glsl").read_text(); w = w[w.index("#version 450 core"):]
assert '#include "sarc_dev_prof_4070ti_q4gsw_body.glslh"' in w
write_new(root / f"sarc_dev/{F4}.glsl", HDR % "sarc_linear_q4gsw_coopmat (the 4070 Ti campaign's PROF body, unchanged)" + w)
Q4 = [("t256x128k16g22s32", "{256, 128, 16, 2, 2, 32, 16, false}"), ("t128x128k32g42s32f32", "{128, 128, 32, 4, 2, 32, 16, false}"),
      ("t128x128k16g22s32", "{128, 128, 16, 2, 2, 32, 16, false}")]
y = YH + f"{F4}:\n" + defaults("sarc/sarc_linear_q4gsw_coopmat.yaml") + "  shader_variants:\n"
rows4 = "    // Jetson Orin phase timing, MEASUREMENT ONLY (glsl/sarc_dev/sarc_dev_prof_orin_q4gsw.yaml): the shipped\n    // Orin 4w tiles with shader-clock phase counters written over their output.\n"
for tok, dims in Q4:
    y += f"    - NAME: {F4}_{tok}p_texture3d_texture2d_half\n" + variant("sarc/sarc_linear_q4gsw_coopmat.yaml", f"sarc_linear_q4gsw_coopmat_{tok}_texture3d_texture2d_half")
    rows4 += f'    {{"", nullptr, Op::kQ4gswLinear,\n     "{F4}_{tok}p", {dims},\n     kTex3dTex2d, nullptr, Status::kUnverified}},\n'
write_new(root / f"sarc_dev/{F4}.yaml", y)

# ---------------- 8da4w: PROF twin of the orin_bf body ----------------
F8 = "sarc_dev_prof_orin_dq8ca_bf"
ref = (root / "sarc_dev/sarc_dev_prof_4070ti_dq8ca_zpgtr_body.glslh").read_text()
DECL = ref[ref.index("void main() {\n"):ref.index("#define PTICK(acc)")]; DECL += ref[ref.index("#define PTICK(acc)"):].split("\n", 1)[0] + "\n"
OUT = ref[ref.index("\n  // PROF output: subgroup 0 writes"):ref.rindex("#endif //")].rstrip("\n") + "\n"
assert OUT.rstrip().endswith("}") and "clock2x32ARB" in DECL
b = (root / "sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_orin_bf_body.glslh").read_text()
G = "SARC_LINEAR_DQ8CA_COOPMAT_ZPGTR_ORIN_BF_BODY_GLSLH"; b = sub(b, G, "SARC_DEV_PROF_ORIN_DQ8CA_BF_BODY_GLSLH", b.count(G))
b = sub(b, "void main() {\n", DECL)
b = sub(b, "  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {",
        "  PTICK(p_pro)\n  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {")
b = sub(b, "      memoryBarrierShared();\n      barrier();\n\n      // --- 2. prefetch chunk+1 -> temp ---",
        "      memoryBarrierShared();\n      barrier();\n      PTICK(p_bar)\n\n      // --- 2. prefetch chunk+1 -> temp ---")
b = sub(b, "      // --- 3. int8 MMA on the cur slice ---", "      PTICK(p_pre)\n      // --- 3. int8 MMA on the cur slice ---")
b = sub(b, "#ifdef ONE_SLICE\n      // orin bf1: the slice the MMA above read is the one written next.\n      memoryBarrierShared();\n      barrier();\n#endif\n      // --- 4. store temp (chunk+1) -> nxt slice ---",
        "      PTICK(p_mma)\n#ifdef ONE_SLICE\n      // orin bf1: the slice the MMA above read is the one written next.\n      memoryBarrierShared();\n      barrier();\n      PTICK(p_bar)\n#endif\n      // --- 4. store temp (chunk+1) -> nxt slice ---")
b = sub(b, "    }  // chunks", "      PTICK(p_st)\n    }  // chunks")
b = sub(b, "  }  // groups", "    PTICK(p_ep)\n  }  // groups")
b = sub(b, "  // --- Bias (optional) ---", "  PTICK(p_ep)\n  // --- Bias (optional) ---")
b = sub(b, "#endif // IO_TEXTURE\n}\n", "#endif // IO_TEXTURE\n" + OUT)
b = "// GENERATED by gen_orin_prof.py (measurement only, never shipped) from sarc_linear_dq8ca_coopmat_zpgtr_orin_bf_body.glslh.\n" + b
write_new(root / f"sarc_dev/{F8}_body.glslh", b)
w = (root / "sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_orin_bf.glsl").read_text(); w = w[w.index("#version 450 core"):]
w = sub(w, "#extension GL_EXT_control_flow_attributes : enable\n", "#extension GL_EXT_control_flow_attributes : enable\n#extension GL_ARB_shader_clock : require\n")
w = sub(w, '#include "sarc_linear_dq8ca_coopmat_zpgtr_orin_bf_body.glslh"', f'#include "{F8}_body.glslh"')
write_new(root / f"sarc_dev/{F8}.glsl", HDR % "sarc_linear_dq8ca_coopmat_zpgtr_orin_bf" + w)
by = (root / "sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_orin_bf.yaml").read_text()
names = re.findall(r"    - NAME: sarc_linear_dq8ca_coopmat_zpgtr_(orin_bf1?_\S+)_texture3d_texture2d_half\n", by)
y = YH + f"{F8}:\n" + defaults("sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_orin_bf.yaml") + "  shader_variants:\n"
rows8 = "    // Jetson Orin phase timing, MEASUREMENT ONLY (glsl/sarc_dev/sarc_dev_prof_orin_dq8ca_bf.yaml).\n"
for tok in names:
    v = variant("sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_orin_bf.yaml", f"sarc_linear_dq8ca_coopmat_zpgtr_{tok}_texture3d_texture2d_half")
    g = {k: int(x) for k, x in re.findall(r"(WG_TILE_M|WG_TILE_N|WG_TILE_K|SG_GRID_X|SG_GRID_Y): (\d+)", v)}
    y += f"    - NAME: {F8}_{tok}p_texture3d_texture2d_half\n" + v
    rows8 += (f'    {{"", nullptr, Op::kDq8caLinear,\n     "{F8}_{tok}p", {{{g["WG_TILE_M"]}, {g["WG_TILE_N"]}, {g["WG_TILE_K"]}, {g["SG_GRID_X"]}, {g["SG_GRID_Y"]}, 32, 16, true}},\n'
              "     kTex3dTex2d, nullptr, Status::kUnverified,\n     /*rowmajor_a=*/true},\n")
write_new(root / f"sarc_dev/{F8}.yaml", y)
o = ops / "impl/sarc_dev/Overrides.cpp"
put_block(o, "    // >>> 4070ti prof-q4gsw-rows\n", "prof-q4gsw-rows", rows4, "    ")
put_block(o, "    // >>> 4070ti prof-dq8ca-rows\n", "prof-dq8ca-rows", rows8, "    ")
print(f"orin prof twins: 4w {len(Q4)}, 8da4w bf {len(names)}")
