#!/usr/bin/env python3
"""gen_orin_q4.py: 4w sweep variants of the tiles the Jetson Orin ships.

  glsl/sarc_dev/sarc_linear_q4gsw_coopmat_orin.{glsl,yaml}
  impl/sarc_dev/Overrides.cpp   `// >>> orin q4-rows`

Why (4w screen 1 and phase timing, results/orin/): no existing dev tile beats the Orin rows, but every one of
them is an fp32-accumulating or `ga` tile; the Orin ships fp16 accumulation on a 256 x 128, K = 16 tile, for
which no staging variant exists. On the fp32 tile, column-major weight staging (`bt`: each packed-weight texel
fetched twice instead of four times) is worth 10 %. The shipped kernel spends 18 % of a wave fetching and 20 %
dequantising and storing weights. This family applies the release body's existing options to the shipped tiles
(the shader is the release kernel through the sweep wrapper, identical from #version on; nothing is new code):
  bt   B_COLMAJOR: column-major weight staging, one half texel per item
  c    CSH_IN_ASH: texture3d drain staged in Ash
and other subgroup grids of the same tile. `orin_t256x128k16g22s32` without a suffix is the shipped tile through
the sweep wrapper, the control of the screen. texture3d IO only (the Orin rows are texture3d only)."""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ET = pathlib.Path(__file__).resolve().parents[4]
ops = ET / "backends/vulkan/runtime/graph/ops"; g = ops / "glsl"
F = "sarc_linear_q4gsw_coopmat_orin"
w = (g / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.glsl").read_text(); w = w[w.index("#version 450 core"):]
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, Jetson Orin (generated by gen_orin_q4.py;
 * openspec/changes/sarc-1.5-orin-prefill-refine): sarc_linear_q4gsw_coopmat_sweep.glsl,
 * identical from #version on; Orin tiles.
 */

"""
write_new(g / f"sarc_dev/{F}.glsl", HDR + w)
sy = (g / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.yaml").read_text()
params = sy[sy.index("  parameter_names_with_default_values:"):sy.index("  shader_variants:")]
# (m, n, k, sgx, sgy, suffix, {options})
VS = [(256, 128, 16, 2, 2, "", {}), (256, 128, 16, 2, 2, "bt", {"B_COLMAJOR": True}), (256, 128, 16, 2, 2, "c", {"CSH_IN_ASH": True}),
      (256, 128, 16, 2, 2, "cbt", {"CSH_IN_ASH": True, "B_COLMAJOR": True}), (128, 128, 16, 2, 2, "bt", {"B_COLMAJOR": True}),
      (256, 128, 16, 4, 2, "", {}), (256, 128, 16, 4, 2, "bt", {"B_COLMAJOR": True}), (256, 128, 16, 2, 4, "", {}),
      (256, 128, 16, 2, 4, "bt", {"B_COLMAJOR": True}), (128, 128, 32, 4, 2, "f32bt", {"ACC_FP32": True, "B_COLMAJOR": True}),
      (256, 128, 16, 4, 4, "bt", {"B_COLMAJOR": True}), (128, 128, 32, 2, 2, "bt", {"B_COLMAJOR": True})]
y = "# SARC development zone, Jetson Orin: 4w sweep variants of the shipped Orin tiles (generated by gen_orin_q4.py). Not shipped.\n\n" + f"{F}:\n" + params + "  shader_variants:\n"
rows = "    // Jetson Orin 4w sweep variants of the shipped tiles (glsl/sarc_dev/sarc_linear_q4gsw_coopmat_orin.yaml).\n"
for m, n, k, sx, sy_, suf, opt in VS:
    assert sx * sy_ * 32 <= 1024 and 2048 % m == 0 and m % (16 * sy_) == 0 and n % (16 * sx) == 0 and 128 % k == 0
    tok = f"orin_t{m}x{n}k{k}g{sx}{sy_}s32{suf}"; name = f"sarc_linear_q4gsw_coopmat_{tok}"
    y += (f"    - NAME: {name}_texture3d_texture2d_half\n      IO_STORAGE: texture3d\n      WEIGHT_STORAGE: texture2d\n      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n"
          f"      WG_TILE_K: {k}\n      SG_GRID_X: {sx}\n      SG_GRID_Y: {sy_}\n      SUBGROUP_SIZE: 32\n" + "".join(f"      {o}: true\n" for o in opt))
    rows += (f'    {{"", nullptr, Op::kQ4gswLinear,\n     "{name}", {{{m}, {n}, {k}, {sx}, {sy_}, 32, 16, {"true" if opt.get("CSH_IN_ASH") else "false"}}},\n'
             "     kTex3dTex2d, nullptr, Status::kUnverified},\n")
write_new(g / f"sarc_dev/{F}.yaml", y)
put_block(ops / "impl/sarc_dev/Overrides.cpp", "    // >>> 4070ti prof-q4gsw-rows\n", "q4-rows", rows, "    ")
print(f"orin 4w: {len(VS)} variants")
