#!/usr/bin/env python3
"""gen_orin_sdpa.py: reach the SDPA prefill kernels on the Jetson Orin from the dev zone, without a hook
(the mechanism of the Xe2 campaign's impl/sarc_dev/Xe2Sdpa.cpp).

Writes impl/sarc_dev/OrinSdpa.cpp: two kUnverified base rows for "tegra orin" (QK^T and attn*V) that match only
while ET_VK_SARC_DEV_PROFILE names an orin-* profile, so every other configuration of a dev build selects
exactly what the release tables select (test_sarc_select unchanged). With ET_VK_SARC_UNVERIFIED=1 and such a
profile, impl/sarc/SdpaCoopmat.cpp builds the SARC SDPA path (spec constants, truncated softmax) and the profile
picks the kernel per shape.

The kernels are the 4070 Ti campaign's dev-zone SDPA variants (subgroup 32, MMA 16x16x16 fp16 x fp16 -> fp32,
the shapes vk-caps lists for the Orin as well): nothing of theirs is changed, they are only named; plus the Orin
QK^T tiles of gen_orin_qk.py (profile names orin-qk-orin_pk_<tile>). Profiles added
to impl/sarc_dev/Overrides.cpp inside `orin` blocks: one screening profile per candidate (orin-qk-<tile>,
orin-av-<tile>), and the orin-refineN profiles listed in REFINE below. Run from anywhere; a second run changes
nothing."""
import pathlib, re, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ET = pathlib.Path(__file__).resolve().parents[4]
IMPL = ET / "backends/vulkan/runtime/graph/ops/impl"; o = IMPL / "sarc_dev/Overrides.cpp"
BASE_QK = ("sarc_sdpa_qk_coopmat_4070ti_t128x64k32g42s32", "{128, 64, 32, 4, 2, 32, 16, false}")
BASE_AV = ("sarc_sdpa_av_coopmat_4070ti_t64x64k32g42s32", "{64, 64, 32, 4, 2, 32, 16, false}")
# orin-refineN: (op, token, predicate or None), first fitting entry wins per shape. Filled from the screens.
REFINE = {}
if (pathlib.Path(__file__).parent / "orin_refine.py").exists():
    from orin_refine import REFINE

text = o.read_text()
for name, _ in (BASE_QK, BASE_AV): assert f'"{name}"' in text, f"{name} is not a registered candidate"
cands = sorted(set(re.findall(r'"sarc_sdpa_(qk|av)_coopmat_((?:4070ti|orin)_[a-z0-9_]+)"', text)))
cpp = '''/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Jetson Orin (device tag orin): SDPA prefill rows
// (openspec/changes/sarc-1.5-orin-prefill-refine; generated by its
// tools/gen_orin_sdpa.py). Not part of a release.
//
// The release tables have no Orin SDPA row, and impl/sarc/SdpaCoopmat.cpp
// builds the SARC SDPA path (spec constants, truncated softmax) only on a
// device with an active SDPA row. The rows below are that row, from the dev
// zone: kUnverified (so they need ET_VK_SARC_UNVERIFIED=1) and matching only
// while ET_VK_SARC_DEV_PROFILE names an orin-* profile other than orin-lin-*,
// so every other configuration of a dev build selects exactly what the release tables
// select. WG_TILE_K of the base rows is 32, which the spec constants assume.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

#include <cstdlib>
#include <cstring>

namespace vkcompute {
namespace sarc {
namespace {

// orin-lin-* profiles change linear kernels only and leave attention alone.
bool orin_profile_requested(const DeviceInfo&) {
  const char* e = std::getenv("ET_VK_SARC_DEV_PROFILE");
  return e != nullptr && std::strncmp(e, "orin-", 5) == 0 &&
      std::strncmp(e, "orin-lin-", 9) != 0;
}

const Row kOrinSdpaRows[] = {
    {"tegra orin", orin_profile_requested, Op::kSdpaQk,
     "%s",
     %s, kBufBuf, nullptr,
     Status::kUnverified},
    {"tegra orin", orin_profile_requested, Op::kSdpaAv,
     "%s",
     %s, kBufBuf, nullptr,
     Status::kUnverified},
};

struct Registrar {
  Registrar() {
    register_rows(kOrinSdpaRows, sizeof(kOrinSdpaRows) / sizeof(kOrinSdpaRows[0]));
  }
} registrar;

} // namespace
} // namespace sarc
} // namespace vkcompute
''' % (BASE_QK + BASE_AV)
write_new(IMPL / "sarc_dev/OrinSdpa.cpp", cpp)

ident = lambda s: re.sub(r"[^A-Za-z0-9]", "_", s)
prefs = "// Jetson Orin (tools/gen_orin_sdpa.py): single-kernel SDPA screening profiles and orin-refineN.\n"
PREDS = {"head_dim_64_orin": "  return (s.op == Op::kSdpaQk ? s.K : s.N) == 64;",
         # the shapes the Orin's fp32-accumulating 4w row serves (orin_large_k in impl/sarc/table_nvidia.cpp)
         "k_above_8192_orin": "  return s.K > 8192;",
         # the shapes the table gives to the Orin's 256 x 128 fp16-accumulating 4w tile (orin_256, same file)
         "orin_256_shape": "  return s.K <= 8192 && (s.M != 256 || s.N % 2048 == 0);"}
for name, body in PREDS.items():
    if any(pred == name for e in REFINE.values() for _, _, pred in e):
        prefs += f"bool {name}(const ShapeInfo& s) {{\n{body}\n}}\n"
profs = ""
for op, tok in cands:
    short = tok[len("4070ti_"):] if tok.startswith("4070ti_") else tok; v = f"kOrin_{op}_{ident(short)}"; OP = "kSdpaQk" if op == "qk" else "kSdpaAv"
    prefs += f'const Preference {v}[] = {{{{Op::{OP}, "{tok}", nullptr}}}};\n'
    profs += f'    {{"orin-{op}-{short}", {v}, 1}},\n'
for name, entries in REFINE.items():
    v = "k" + ident(name).title().replace("_", "")
    prefs += f"const Preference {v}[] = {{\n" + "".join(f'    {{Op::{op}, "{tok}", {pred or "nullptr"}}},\n' for op, tok, pred in entries) + "};\n"
    profs += f'    {{"{name}", {v}, sizeof({v}) / sizeof(Preference)}},\n'
put_block(o, "struct Profile {\n", "sdpa-preferences", prefs)
put_block(o, "};\nconst Profile* requested_profile() {", "sdpa-profiles", profs, "    ")
# The softmax variant (release hook Override::softmax_variant, owner decision 2026-10-05) is named from the dev zone.
soft = """    // ET_VK_SARC_SOFTMAX_VARIANT=<suffix>: a dev-zone variant of the SARC softmax, e.g. 4070ti_nzf
    // (fp32 reduction, no zero tail). Through Override::softmax_variant, the release hook of the owner
    // decision of 2026-10-05; unset, the release softmax is used.
    if (const char* v = std::getenv("ET_VK_SARC_SOFTMAX_VARIANT")) {
      if (*v != 0) {
        o.softmax_variant = v;
        std::cerr << "[sarc_dev] softmax variant: " << v << std::endl;
      }
    }
"""
put_block(o, "    set_override(o);\n", "softmax-variant", soft, "    ")
print(f"OrinSdpa.cpp written; {len(cands)} screening profiles, {len(REFINE)} refine profiles")
