#!/usr/bin/env python3
"""gen_orin_qk.py: more packed-staging QK^T tiles for the Jetson Orin.

  glsl/sarc_dev/sarc_sdpa_qk_coopmat_orin_pk.{glsl,yaml}
  impl/sarc_dev/Overrides.cpp   `// >>> orin qk-rows`

Why (SDPA screen 1, results/orin/screens/sdpa-screen1-rows.csv): on this device packed staging beats direct feed
(the opposite of the 4070 Ti), and the one K = 64 tile of the sibling's list is the best QK^T kernel for all
three head configurations (9.4 ms per 8B layer against 10.3 for the same tile at K = 32). The shader is the
4070 Ti campaign's packed-staging QK^T kernel, unchanged from #version on (its chunk count is derived from the
32-wide count of the base row, so K = 64 and K = 128 tiles work with the base rows of OrinSdpa.cpp); this file
only adds tiles: K = 64 on other tile shapes and subgroup grids, and K = 128 (head_dim 128 in one chunk; such a
tile does not fit head_dim 64, which then takes the next preference of a profile).
Static pruning: subgroup 32, MMA 16x16x16 fp16 -> fp32, at most 1024 invocations, shared memory
16 * (M + N) * (K + 8) / 8 + 2 * M * N <= 49152 bytes, tiles dividing S = 2048 and head_dim."""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ET = pathlib.Path(__file__).resolve().parents[4]
root = ET / "backends/vulkan/runtime/graph/ops"; g = root / "glsl"
LDS_MAX, WG_MAX, SG = 49152, 1024, 32
def V(m, n, k, sx, sy):
    assert sx * sy * SG <= WG_MAX and 2048 % m == 0 and m % (16 * sy) == 0 and n % (16 * sx) == 0 and 128 % k == 0
    assert 16 * (m + n) * ((k + 8) // 8) + 2 * m * n <= LDS_MAX, (m, n, k)
    return dict(tok=f"t{m}x{n}k{k}g{sx}{sy}s{SG}nf", m=m, n=n, k=k, sx=sx, sy=sy)
PK = [V(64, 64, 64, 2, 2), V(64, 64, 64, 2, 1), V(64, 64, 64, 4, 2), V(128, 64, 64, 2, 4), V(128, 64, 64, 4, 4), V(128, 64, 64, 2, 2),
      V(64, 128, 64, 4, 2), V(32, 64, 64, 4, 2), V(64, 64, 128, 2, 2), V(64, 64, 128, 4, 2), V(64, 64, 128, 2, 1), V(64, 64, 128, 4, 4)]
F = "sarc_sdpa_qk_coopmat_orin_pk"
src = (g / "sarc_dev/sarc_sdpa_qk_coopmat_4070ti_pk.glsl").read_text(); src = src[src.index("#version 450 core"):]
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, Jetson Orin (generated by gen_orin_qk.py;
 * openspec/changes/sarc-1.5-orin-prefill-refine). QK^T with packed staging:
 * sarc_sdpa_qk_coopmat_4070ti_pk.glsl, identical from #version on; more tiles.
 */

"""
write_new(g / f"sarc_dev/{F}.glsl", HDR + src)
v0 = PK[0]
y = f"# SARC development zone, Jetson Orin: QK^T with packed staging, more tiles (generated by gen_orin_qk.py). Not shipped.\n\n{F}:\n"
y += f"  parameter_names_with_default_values:\n    DTYPE: half\n    PRECISION: highp\n    IO_STORAGE: buffer\n    K_CACHE_STORAGE: buffer\n    MMA_M: 16\n    MMA_N: 16\n    MMA_K: 16\n"
y += f"    WG_TILE_M: {v0['m']}\n    WG_TILE_N: {v0['n']}\n    WG_TILE_K: {v0['k']}\n    SG_GRID_X: {v0['sx']}\n    SG_GRID_Y: {v0['sy']}\n    SUBGROUP_SIZE: {SG}\n    NO_MASK_FILL: true\n"
y += "  generate_variant_forall:\n    combination:\n      parameter_names: [IO_STORAGE, K_CACHE_STORAGE]\n      combos:\n        - parameter_values: [buffer, buffer]\n    DTYPE:\n      - VALUE: half\n  shader_variants:\n"
rows = "    // Jetson Orin: packed-staging QK^T, more tiles (glsl/sarc_dev/sarc_sdpa_qk_coopmat_orin_pk.yaml).\n    // Selected only through ET_VK_SARC_DEV_PROFILE=orin-*.\n"
for v in PK:
    y += f"    - NAME: {F}_{v['tok']}\n      WG_TILE_M: {v['m']}\n      WG_TILE_N: {v['n']}\n      WG_TILE_K: {v['k']}\n      SG_GRID_X: {v['sx']}\n      SG_GRID_Y: {v['sy']}\n      SUBGROUP_SIZE: {SG}\n"
    rows += f'    {{"", nullptr, Op::kSdpaQk,\n     "{F}_{v["tok"]}",\n     {{{v["m"]}, {v["n"]}, {v["k"]}, {v["sx"]}, {v["sy"]}, {SG}, 16, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n'
write_new(g / f"sarc_dev/{F}.yaml", y)
put_block(root / "impl/sarc_dev/Overrides.cpp", "    // >>> 4070ti df-rows\n", "qk-rows", rows, "    ")
print(f"orin QK^T packed staging: {len(PK)} tiles")
