#!/usr/bin/env python3
"""Candidate 2 (A, 8da4w): texel-wise weight staging for the zpg kernel, as a new dev-zone family.

usage: gen_bt.py <executorch tree>

The release zpg body stages B one LDS word per slot: every slot fetches a whole packed-weight texel
(4 K x 8 N nibbles), keeps one of its 4 components and one nibble parity (a component-select and a
parity-select chain) and stores 1 word, so each texel is fetched 8 times per chunk. Here a slot is
(texel, parity): one fetch, the 4 components widened together, 4 LDS words stored. Same LDS layout, same
values, same MMA loop: the result is bit-identical to the release kernel by construction (checked by
test_llama_microbench correctness and production-diff).

Writes (new files, dev zone): glsl/sarc_dev/sarc_dev_linear_dq8ca_coopmat_zpg_bt{.glsl,.yaml,_body.glslh} and the
PROF twin sarc_dev_prof_dq8ca_coopmat_zpg_bt{...}; adds candidate rows and profile 780m-refine2 to Overrides.cpp.
A tile needs 2 * (WG_TILE_K/4) * (WG_TILE_N/8) to be a multiple of the workgroup size.
"""
import pathlib, sys
root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
g = root / "glsl"

def sub(text, old, new, count=1):
    n = text.count(old)
    assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)

b = (g / "sarc/sarc_linear_dq8ca_coopmat_zpg_body.glslh").read_text()
b = b.replace("SARC_LINEAR_DQ8CA_COOPMAT_ZPG_BODY_GLSLH", "SARC_DEV_LINEAR_DQ8CA_COOPMAT_ZPG_BT_BODY_GLSLH")
b = sub(b, "// Body of sarc_linear_dq8ca_coopmat_zpg;",
        "// GENERATED by gen_bt.py from the release zpg body (texel-wise B staging). Body of sarc_dev_linear_dq8ca_coopmat_zpg_bt;")
b = sub(b, "void main() {\n", """// All four components of a packed-weight texel at once: `shift` is 0 or 4
// (nibble parity). Same arithmetic as widen_nibbles, per component.
uvec4 widen_nibbles4(const uvec4 w, const uint shift) {
  const uvec4 nib = (w >> shift) & uvec4(0x0F0F0F0Fu);
  const uvec4 p   = nib ^ uvec4(0x08080808u);
  const uvec4 sgn = p & uvec4(0x08080808u);
  return p | (sgn * 0x1Eu);
}

void main() {
""")
b = sub(b, """  const uint B_TOTAL_SLOTS = K_BLOCKS_PER_CHUNK * WG_TILE_N;
  const uint B_SLOTS_PER_THREAD = B_TOTAL_SLOTS / WG_SIZE;
  const uint N8_PER_TILE = WG_TILE_N >> 3u;
""", """  // Texel-wise: a slot is (texel, nibble parity) and yields 4 LDS words (the
  // texel's 4 components = 4 output columns x 4 K). The yaml generator checks
  // that the slot count is a multiple of WG_SIZE.
  const uint N8_PER_TILE = WG_TILE_N >> 3u;
  const uint B_TOTAL_SLOTS = 2u * K_BLOCKS_PER_CHUNK * N8_PER_TILE;
  const uint B_SLOTS_PER_THREAD = B_TOTAL_SLOTS / WG_SIZE;
""")
b = sub(b, """    const uint a           = gl_LocalInvocationID.x + si * WG_SIZE;
    const uint slab_idx    = a / B_SLAB_U32;
    const uint local_a     = a % B_SLAB_U32;
    const uint n_col       = local_a / B_STRIDE_U32;
    const uint k4_in_slab  = local_a % B_STRIDE_U32;
    const uint k4_in_chunk = slab_idx * (MMA_K >> 2u) + k4_in_slab;
    const uint n8_in_tile  = n_col >> 3u;
    const uint rem         = n_col & 7u;
    b_lds_off[si] = a;
    b_comp[si]    = rem & 3u;
    b_par[si]     = rem >> 2u;
    b_n8blk[si]   = (tile_n_start >> 3u) + n8_in_tile;
    b_k4off[si]   = k4_in_chunk;
""", """    const uint s           = gl_LocalInvocationID.x + si * WG_SIZE;
    const uint par         = s & 1u;
    const uint tex         = s >> 1u;
    const uint k4_in_chunk = tex % K_BLOCKS_PER_CHUNK;
    const uint n8_in_tile  = tex / K_BLOCKS_PER_CHUNK;
    const uint slab_idx    = k4_in_chunk / (MMA_K >> 2u);
    const uint k4_in_slab  = k4_in_chunk % (MMA_K >> 2u);
    // LDS word of component 0; component c is c * B_STRIDE_U32 further.
    b_lds_off[si] = slab_idx * B_SLAB_U32
        + (n8_in_tile * 8u + par * 4u) * B_STRIDE_U32 + k4_in_slab;
    b_comp[si]    = 0u;        // unused: all four components are staged
    b_par[si]     = par * 4u;  // nibble shift
    b_n8blk[si]   = (tile_n_start >> 3u) + n8_in_tile;
    b_k4off[si]   = k4_in_chunk;
""")
b = sub(b, """      Bsh_int8[b_lds_off[si]] =
          widen_nibbles(uint(temp_B[si][b_comp[si]]), b_par[si]);
""", """      const uvec4 bw = widen_nibbles4(uvec4(temp_B[si]), b_par[si]);
      [[unroll]] for (uint c = 0; c < 4u; ++c) {
        Bsh_int8[b_lds_off[si] + c * B_STRIDE_U32] = bw[c];
      }
""")
b = sub(b, """          Bsh_int8[nxt_b + b_lds_off[si]] =
              widen_nibbles(uint(temp_B[si][b_comp[si]]), b_par[si]);
""", """          const uvec4 bw = widen_nibbles4(uvec4(temp_B[si]), b_par[si]);
          [[unroll]] for (uint c = 0; c < 4u; ++c) {
            Bsh_int8[nxt_b + b_lds_off[si] + c * B_STRIDE_U32] = bw[c];
          }
""")
(g / "sarc_dev/sarc_dev_linear_dq8ca_coopmat_zpg_bt_body.glslh").write_text(b)

HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone: %s
 * (generated by gen_bt.py; openspec/changes/sarc-1.5-780m-prefill-refine). The wrapper is the zpg sweep
 * wrapper with a different body.
 */

"""
w0 = (g / "sarc_dev/sarc_linear_dq8ca_coopmat_zpg_sweep.glsl").read_text()
w0 = w0[w0.index("#version 450 core"):]
w = sub(w0, '#include "sarc_linear_dq8ca_coopmat_zpg_body.glslh"', '#include "sarc_dev_linear_dq8ca_coopmat_zpg_bt_body.glslh"')
(g / "sarc_dev/sarc_dev_linear_dq8ca_coopmat_zpg_bt.glsl").write_text(HDR % "8da4w zpg kernel with texel-wise weight staging" + w)
y = (g / "sarc_dev/sarc_linear_dq8ca_coopmat_zpg_sweep.yaml").read_text()
defaults = y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
# (token, M, N, K, sgx, sgy, a_blocks, storages)
T = [("t128x64k32g22s32", 128, 64, 32, 2, 2, 2), ("t128x128k32g42s32", 128, 128, 32, 4, 2, 1),
     ("t128x64k64g42s32", 128, 64, 64, 4, 2, 2), ("t128x64k64g22s32", 128, 64, 64, 2, 2, 4)]
def variants(prefix, suffix, tiles, storages=("texture3d", "buffer")):
    out = "  shader_variants:\n"
    for tok, m, n, k, sx, sy, ab in tiles:
        wg = sx * sy * 32
        assert (m // 4) * (k // 4) == ab * wg and (2 * (k // 4) * (n // 8)) % wg == 0, tok
        assert 2 * m * k + 2 * n * k + 8 * m + 12 * n + sy * 16 * n * 2 <= 60000, tok
        for io in storages:
            out += f"    - NAME: {prefix}_{tok}{suffix}_{io}_texture2d_half\n      IO_STORAGE: {io}\n"
            out += f"      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n      WG_TILE_K: {k}\n      SG_GRID_X: {sx}\n      SG_GRID_Y: {sy}\n      A_MAP_FULL: true\n"
            if ab > 1: out += f"      A_MULTI_BLOCK: true\n      A_BLOCKS: {ab}\n"
    return out
YH = "# SARC development zone: 8da4w zpg with texel-wise weight staging (generated by gen_bt.py). Not shipped.\n# Select with ET_VK_SARC_DQ8CA_VARIANT=bt_<tile> or ET_VK_SARC_DEV_PROFILE=780m-refine2.\n\n"
(g / "sarc_dev/sarc_dev_linear_dq8ca_coopmat_zpg_bt.yaml").write_text(YH + "sarc_dev_linear_dq8ca_coopmat_zpg_bt:\n" + defaults + variants("sarc_dev_linear_dq8ca_coopmat_zpg_bt", "", T))

# PROF twin of the bt body (same PTICK points as gen_prof.py).
p = b.replace("SARC_DEV_LINEAR_DQ8CA_COOPMAT_ZPG_BT_BODY_GLSLH", "SARC_DEV_PROF_DQ8CA_COOPMAT_ZPG_BT_BODY_GLSLH")
p = sub(p, "void main() {\n", """void main() {
  // PROF (measurement only): per-phase shader-clock cycles of this wave.
  uint p_pro = 0u, p_bar = 0u, p_pre = 0u, p_mma = 0u, p_st = 0u, p_ep = 0u, p_dr = 0u, p_wr = 0u;
  uint p_t = clock2x32ARB().x;
#define PTICK(acc) { const uint p_n = clock2x32ARB().x; acc += (p_n - p_t) & 0xFFFFFu; p_t = p_n; }
""")
p = sub(p, "  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {",
        "  PTICK(p_pro)\n  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {")
p = sub(p, "      memoryBarrierShared();\n      barrier();\n\n      // --- 2. prefetch chunk+1 -> temp ---",
        "      memoryBarrierShared();\n      barrier();\n      PTICK(p_bar)\n\n      // --- 2. prefetch chunk+1 -> temp ---")
p = sub(p, "      // --- 3. int8 MMA on the cur slice ---", "      PTICK(p_pre)\n      // --- 3. int8 MMA on the cur slice ---")
p = sub(p, "      // --- 4. store temp (chunk+1) -> nxt slice ---", "      PTICK(p_mma)\n      // --- 4. store temp (chunk+1) -> nxt slice ---")
p = sub(p, "    }  // chunks", "      PTICK(p_st)\n    }  // chunks")
p = sub(p, "  }  // groups", "    PTICK(p_ep)\n  }  // groups")
p = sub(p, "  // --- Bias (optional) ---", "  PTICK(p_ep)\n  // --- Bias (optional) ---")
p = sub(p, "    }\n    memoryBarrierShared();\n    barrier();\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {",
        "    }\n    memoryBarrierShared();\n    barrier();\n    PTICK(p_dr)\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {")
p = sub(p, "              float(Csh_out[base + 3u])));\n    }\n  }\n#else", "              float(Csh_out[base + 3u])));\n    }\n    PTICK(p_wr)\n  }\n#else")
p = sub(p, "#endif // IO_TEXTURE\n}\n", """#endif // IO_TEXTURE

  PTICK(p_wr)
  {
    const float it = float(max(num_chunks, 1u));
    const vec4 v0 = vec4(float(p_bar), float(p_pre), float(p_mma), float(p_st)) / it;
    const vec4 v1 = vec4(float(p_pro), float(p_ep), float(p_dr), float(p_wr)) / 64.0;
#ifdef IO_TEXTURE
    memoryBarrierImage();
    barrier();
    if (gl_SubgroupID == 0u && subgroupElect()) {
      imageStore(t_output, ivec3(tile_n_start / 4u, tile_m_start, 0), v0);
      imageStore(t_output, ivec3(tile_n_start / 4u + 1u, tile_m_start, 0), v1);
    }
#endif
  }
}
""")
(g / "sarc_dev/sarc_dev_prof_dq8ca_coopmat_zpg_bt_body.glslh").write_text(p)
w = sub(w0, "#extension GL_EXT_control_flow_attributes : enable\n", "#extension GL_EXT_control_flow_attributes : enable\n#extension GL_ARB_shader_clock : require\n")
w = sub(w, '#include "sarc_linear_dq8ca_coopmat_zpg_body.glslh"', '#include "sarc_dev_prof_dq8ca_coopmat_zpg_bt_body.glslh"')
(g / "sarc_dev/sarc_dev_prof_dq8ca_coopmat_zpg_bt.glsl").write_text(HDR % "MEASUREMENT ONLY phase-timing twin of sarc_dev_linear_dq8ca_coopmat_zpg_bt (output overwritten with cycle counts)" + w)
(g / "sarc_dev/sarc_dev_prof_dq8ca_coopmat_zpg_bt.yaml").write_text("# SARC development zone, MEASUREMENT ONLY (generated by gen_bt.py). Never shipped.\n\nsarc_dev_prof_dq8ca_coopmat_zpg_bt:\n" + defaults + variants("sarc_dev_prof_dq8ca_coopmat_zpg_bt", "p", T[:1], ("texture3d",)))

o = root / "impl/sarc_dev/Overrides.cpp"; t = o.read_text()
if "sarc_dev_linear_dq8ca_coopmat_zpg_bt" not in t:
    a = "    // 780M phase timing, MEASUREMENT ONLY (glsl/sarc_dev/sarc_dev_prof_dq8ca_zpg.yaml)."
    rows = "    // 780M prefill refine 2026-10-03, candidate 2: texel-wise weight staging\n    // (glsl/sarc_dev/sarc_dev_linear_dq8ca_coopmat_zpg_bt.yaml).\n"
    for tok, m, n, k, sx, sy, ab in T:
        rows += f'    {{"", nullptr, Op::kDq8caLinear,\n     "sarc_dev_linear_dq8ca_coopmat_zpg_bt_{tok}",\n     {{{m}, {n}, {k}, {sx}, {sy}, 32, 16, false}}, kTex3dTex2d | kBufTex2d, nullptr,\n     Status::kUnverified}},\n'
    rows += '    {"", nullptr, Op::kDq8caLinear,\n     "sarc_dev_prof_dq8ca_coopmat_zpg_bt_t128x64k32g22s32p", dq_tile(128, 64, 2, 2),\n     kTex3dTex2d, nullptr, Status::kUnverified},\n'
    t = sub(t, a, rows + a)
    a = "struct Profile {\n"
    t = sub(t, a, """const Preference k780mRefine2[] = {
    {Op::kDq8caLinear, "bt_t128x64k32g22s32", nullptr},
    {Op::kQ4gswLinear, "t128x256k32g42s32f32c", n_at_least_1024},
};
""" + a)
    a = '    {"780m-refine1-dq",'
    t = sub(t, a, '    {"780m-refine2", k780mRefine2, sizeof(k780mRefine2) / sizeof(Preference)},\n' + a)
    o.write_text(t)
print("bt family generated")
