#!/usr/bin/env python3
"""gen_7900xtx_q4.py: writes glsl/sarc_dev/sarc_dev_7900xtx_x_linear_q4gsw_coopmat.yaml and impl/sarc_dev/Space7900xtxQ4.inc from one table of variants
(second set, item 3: 4w linear). Run from the repository root. Suffix bpN = BT_PAD_H N (padding in fp16 of a row of the column-major B staging; the row pitch
is 32 + N fp16: 72 bytes for N = 4, 80 for the release default 8, 88 for 12), apN = A staged as uvec2 with A_PAD_H N (row pitch 32 + N fp16), gXY = SG_GRID_X x
SG_GRID_Y of the 256 x 128 tile (g24 = the release table kernel's grid, g28 = 16 waves). cbt = column-major B staging
with fp32 accumulation. The phase timing of the table kernel comes from the 780M's twin (sarc_dev_prof_q4gsw, a 7900xtx block adds the 256 x 128 cbt tile). bp8 without ap is the control: the release kernel's staging."""
G = "backends/vulkan/runtime/graph/ops/glsl/sarc_dev/sarc_dev_7900xtx_x_linear_q4gsw_coopmat.yaml"
I = "backends/vulkan/runtime/graph/ops/impl/sarc_dev/Space7900xtxQ4.inc"
FAM = "sarc_dev_7900xtx_x_linear_q4gsw_coopmat"
HEAD = f"""# SARC development zone, 7900 XTX campaign second set: the 4w coopmat linear (release body copy) with options, default off.
# GENERATED by openspec/changes/sarc-1.5-7900xtx-prefill-refine/tools/gen_7900xtx_q4.py; do not edit. Not shipped.

{FAM}:
  parameter_names_with_default_values:
    PRECISION: highp
    HAS_BIAS: false
    IO_STORAGE: texture3d
    WEIGHT_STORAGE: texture2d
    MMA_M: 16
    MMA_N: 16
    MMA_K: 16
    WG_TILE_M: 256
    WG_TILE_N: 128
    WG_TILE_K: 32
    SG_GRID_X: 2
    SG_GRID_Y: 4
    SUBGROUP_SIZE: 32
    ACC_FP32: true
    CSH_IN_ASH: true
    ACC_GROUP_FP32: false
    ACC_GROUP_FP32_REG: false
    FRAG_LAYOUT: false
    IMG_A: false
    IMG_W: false
    SH_F16V4: false
    CSH_BAND: false
    B_COLMAJOR: true
    CSH_FULL: false
    CSH_POOL: false
    BT_PAD_H: 8
    A_V2: false
    A_PAD_H: 8
    ABL: 0
  shader_variants:
"""
V = []
def row(gx, gy, pad, apad=None, abl=0):
    V.append((gx, gy, pad, apad, abl))
for gx, gy in ((2, 4), (2, 8)):
    for pad in (8, 4, 12):
        row(gx, gy, pad)
    for apad, pad in ((8, 8), (4, 8), (4, 4), (4, 12), (12, 4), (8, 12)):
        assert 256 * (32 + apad) * 2 + 128 * (32 + pad) * 2 <= 65536   # A rows x (K + A_PAD_H) fp16 + B columns x (K + BT_PAD_H) fp16, bytes
        row(gx, gy, pad, apad)
for a in (4, 16, 20):   # ablation twins of the table kernel, MEASUREMENT ONLY (wrong results by design): 4 = the stores of the next chunk, 16 = the barrier of the chunk loop
    row(2, 4, 8, abl=a)
y = HEAD
inc = "// GENERATED by openspec/changes/sarc-1.5-7900xtx-prefill-refine/tools/gen_7900xtx_q4.py. Do not edit.\n"
for gx, gy, pad, apad, abl in V:
    s = f"t256x128k32g{gx}{gy}s32f32cbt" + (f"ap{apad}" if apad is not None else "") + f"bp{pad}" + (f"abl{abl}" if abl else "")
    base = f"{FAM}_{s}"
    y += f"    - NAME: {base}_texture3d_texture2d_half\n      SG_GRID_X: {gx}\n      SG_GRID_Y: {gy}\n      BT_PAD_H: {pad}\n"
    if apad is not None: y += f"      A_V2: true\n      A_PAD_H: {apad}\n"
    if abl: y += f"      ABL: {abl}\n"
    inc += (f'{{"", nullptr, Op::kQ4gswLinear, "{base}", {{256, 128, 32, {gx}, {gy}, 32, 16, true, false, false}}, '
            f'kTex3dTex2d, nullptr, Status::kUnverified}},\n')
open(G, "w").write(y); open(I, "w").write(inc)
print(len(V), "variants")
