#!/usr/bin/env python3
"""gen_7900xtx_dq.py: writes glsl/sarc_dev/sarc_dev_7900xtx_x_linear_dq8ca_coopmat_zpg.yaml and impl/sarc_dev/Space7900xtxDq.inc from one table of
variants (second set, item 2: 8da4w linear; the RX 7600 round-2 recipe on this card's own incumbent tiles). Run from the repository root:
python3 -I <this file>. The kernels are the zpg body with options, all default off (gen_7900xtx_dq_body.py). Suffix: <tile>paN pbN = row pitch N uint (4 = 16 bytes,
6 = 24 bytes) of the A / B staging in shared memory, csha = drain tile in the A staging buffer, p = phase-timing twin (MEASUREMENT ONLY: wrong results by design).
Tiles are the incumbents of the 7900xtx-refine5 picks: t256x64k32g24s32 (6 shapes), t128x64k32g22s32 (8B wk_wv / wq_wo), t128x64k32g42s32 (the release table
kernel), and the 780M's t256x64k64g48s32 (1B w2). pa4pb4 of each tile is the control: the same arithmetic and staging as the incumbent's body."""
G = "backends/vulkan/runtime/graph/ops/glsl/sarc_dev/sarc_dev_7900xtx_x_linear_dq8ca_coopmat_zpg.yaml"
I = "backends/vulkan/runtime/graph/ops/impl/sarc_dev/Space7900xtxDq.inc"
FAM = "sarc_dev_7900xtx_x_linear_dq8ca_coopmat_zpg"
HEAD = f"""# SARC development zone, 7900 XTX campaign second set: the shipped 8da4w zpg kernel (release body copy) with options, default off.
# GENERATED by openspec/changes/sarc-1.5-7900xtx-prefill-refine/tools/gen_7900xtx_dq.py; do not edit. Not shipped. Candidate kernels are selected
# by the 7900xtx profiles in impl/sarc_dev/Overrides.cpp; the measurement-only twins (suffix p = phase timing; wrong results by design) only by exact name.

{FAM}:
  parameter_names_with_default_values:
    PRECISION: highp
    HAS_BIAS: false
    IO_STORAGE: texture3d
    WEIGHT_NBITS: 4
    WEIGHT_STORAGE: texture2d
    A_MAP_FULL: true
    A_MULTI_BLOCK: true
    A_BLOCKS: 1
    A_PAD: 0
    CSH_IN_ASH: false
    BF: false
    UV4: false
    A_PITCH: 4
    B_PITCH: 4
    ST_A: -1
    ST_B: -1
    PROF: false
    ABL: 0
    MMA_M: 16
    MMA_N: 16
    MMA_K: 16
    WG_TILE_M: 256
    WG_TILE_N: 64
    WG_TILE_K: 32
    SG_GRID_X: 2
    SG_GRID_Y: 4
    SUBGROUP_SIZE: 32
  shader_variants:
"""
# tile token -> (M, N, K, gx, gy, A_BLOCKS, A_MULTI_BLOCK)
TILES = {"t256x64k32g24s32": (256, 64, 32, 2, 4, 2, True), "t128x64k32g22s32": (128, 64, 32, 2, 2, 2, True),
         "t128x64k32g42s32": (128, 64, 32, 4, 2, 1, False), "t256x64k64g48s32": (256, 64, 64, 4, 8, 1, True)}
V = []
def row(tile, pa=4, pb=4, csha=False, prof=False, bf=False, sa=-1, sb=-1, abl=0):
    V.append((tile, pa, pb, csha, prof, bf, sa, sb, abl))
for t in ("t256x64k32g24s32", "t128x64k32g22s32", "t128x64k32g42s32"):
    for pa, pb in ((4, 4), (5, 4), (6, 4), (8, 4), (6, 6)):
        row(t, pa, pb)
    row(t, 4, 4, prof=True); row(t, 6, 4, prof=True)
# synchronisation variants (second set, item 2) on the two incumbent tiles of K step 32: bf = branch-free chunk loop; aXbY = the stores of the next chunk's A / B
# staging issued after K slab X / Y of the current chunk's MMAs instead of after the last slab (need bf); ablN = removed work, MEASUREMENT ONLY (wrong results by
# design): 1 A global fetch, 2 B global fetch, 4 LDS stores of the next chunk, 8 the MMA loop, 16 the barrier of the chunk loop.
for t in ("t256x64k32g24s32", "t128x64k32g42s32"):
    row(t, bf=True)
    for sa, sb in ((0, 0), (0, 1), (1, 1)):
        row(t, bf=True, sa=sa, sb=sb)
for a in (1, 2, 4, 7, 8, 16, 23):
    row("t256x64k32g24s32", abl=a)
t = "t256x64k64g48s32"                      # 16 waves: the drain tile moves into the A buffer to stay under 64 KiB with the padded rows
row(t)
for pa, pb in ((4, 4), (5, 4), (6, 4), (6, 6)):
    assert 8192 * pa + 2048 * pb + 2816 <= 65536
    row(t, pa, pb, csha=True)
row(t, 4, 4, csha=True, prof=True); row(t, 6, 4, csha=True, prof=True)
y = HEAD
inc = "// GENERATED by openspec/changes/sarc-1.5-7900xtx-prefill-refine/tools/gen_7900xtx_dq.py. Do not edit.\n"
for tile, pa, pb, csha, prof, bf, sa, sb, abl in V:
    m, n, k, gx, gy, ab, mb = TILES[tile]
    s = tile if (tile == "t256x64k64g48s32" and pa == 4 and pb == 4 and not csha and not prof) else f"{tile}pa{pa}pb{pb}" + ("csha" if csha else "") + ("p" if prof else "")
    if bf: s = f"{tile}bf" + (f"a{sa}b{sb}" if sa >= 0 else "")
    if abl: s = f"{tile}abl{abl}"
    base = f"{FAM}_{s}"
    y += (f"    - NAME: {base}_texture3d_texture2d_half\n      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n      WG_TILE_K: {k}\n      SG_GRID_X: {gx}\n      SG_GRID_Y: {gy}\n"
          f"      A_BLOCKS: {ab}\n      A_MULTI_BLOCK: {'true' if mb else 'false'}\n")
    if csha: y += "      CSH_IN_ASH: true\n"
    if pa != 4: y += f"      A_PITCH: {pa}\n"
    if pb != 4: y += f"      B_PITCH: {pb}\n"
    if prof: y += "      PROF: true\n"
    if bf: y += "      BF: true\n"
    if sa >= 0: y += f"      ST_A: {sa}\n      ST_B: {sb}\n"
    if abl: y += f"      ABL: {abl}\n"
    inc += (f'{{"", nullptr, Op::kDq8caLinear, "{base}", {{{m}, {n}, {k}, {gx}, {gy}, 32, 16, {"true" if csha else "false"}, false, false}}, '
            f'kTex3dTex2d, nullptr, Status::kUnverified}},\n')
open(G, "w").write(y); open(I, "w").write(inc)
print(len(V), "variants")
