#!/usr/bin/env python3
"""Direct-feed SDPA prefill kernels for the RTX 4070 Ti SUPER (dev zone, new code of this campaign).

usage: gen_4070ti_df.py <executorch tree>

  glsl/sarc_dev/sarc_sdpa_qk_coopmat_4070ti_df.{glsl,yaml}   QK^T
  glsl/sarc_dev/sarc_sdpa_av_coopmat_4070ti_df.{glsl,yaml}   attn*V
  impl/sarc_dev/Overrides.cpp                                `// >>> 4070ti df-*` blocks (rows, preferences, profiles)

Why (screen 1 and the fresh roofs, see proposal.md): on this card the ported SARC SDPA kernels are bound by
memory traffic and by the half-rate fp32-accumulate MMA, not by staging arithmetic. These kernels therefore
  - stage nothing in shared memory: every subgroup loads its MMA operands straight from the tensors
    (Q and K^T, the latter as a ColumnMajor load of K; P rows and V), so there is no barrier in the fast path and
    no cross-subgroup dependency;
  - decide the causal mask per subgroup tile and, for the QK^T store, per 16 x 16 MMA tile (NO_MASK_FILL: elements
    the truncated SARC softmax never reads are not written);
  - ACC selects the accumulator: 0 = fp32 (same accumulation order as the release kernels), 1 = fp16 per 32 of K,
    folded into an fp32 total (token prefix dfg), 2 = fp16 throughout (dfh). 1 and 2 change precision and are only
    candidates together with a measured error.
Bindings, spec constants, dispatch grid and names follow impl/sarc/SdpaCoopmat.cpp (sarc_sdpa_qk_ / sarc_sdpa_av_
prefix, "coopmat", QK^T tile tokens ending in "nf"). The row's k is nominal (32, what the fit check needs).
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
g = root / "glsl"
LDS_MAX, WG_MAX, SG = 49152, 1024, 32

HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_df.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine). %s
 */

#version 450 core

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_control_flow_attributes : enable

#define PRECISION ${PRECISION}
// 0: fp32 accumulator; 1: fp16 per 32 of K, fp32 total; 2: fp16 accumulator.
#define ACC ${ACC}

layout(std430) buffer;

#include "common.glslh"

"""
CONSTS = """
const uint MMA = 16;
const uint WG_TILE_M = ${WG_TILE_M};
const uint WG_TILE_N = ${WG_TILE_N};
const uint SG_GRID_X = ${SG_GRID_X};
const uint SG_GRID_Y = ${SG_GRID_Y};
const uint SG_TILE_M = WG_TILE_M / SG_GRID_Y;
const uint SG_TILE_N = WG_TILE_N / SG_GRID_X;
const uint MI = SG_TILE_M / MMA;
const uint NJ = SG_TILE_N / MMA;

#define ACC32 coopmat<float, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define ACC16 coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define MAT_A coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseA>
#define MAT_B coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseB>
#if ACC == 2
#define RES ACC16
#else
#define RES ACC32
#endif
RES result[MI][NJ];
#if ACC == 1
ACC16 part[MI][NJ];
#endif
"""

QK = HDR % "QK^T, direct feed (no operand staging), NO_MASK_FILL." + """// Bindings mirror sdpa_compute_attn_weights_tiled: attn_weights(0), q(1), k(2).
${layout_declare_tensor(B, "w", "t_attn_weights", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_q", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_k", DTYPE, K_CACHE_STORAGE, is_scalar_array=True)}

${layout_declare_ubo(B, "ivec4", "q_sizes")}
${layout_declare_ubo(B, "ivec4", "k_sizes")}
${layout_declare_ubo(B, "int", "input_pos")}

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

${layout_declare_spec_const(C, "float", "inv_scale", "1.0")}
// head_dim / 32 (from the table row) and the attn_weights row width at node
// construction, as in glsl/sarc/sarc_sdpa_qk_coopmat.glsl.
${layout_declare_spec_const(C, "int", "num_k_chunks_arg", "0")}
${layout_declare_spec_const(C, "int", "aw_row_width_arg", "0")}
""" + CONSTS + """
// Scratch of the slow path only (row width differs from the baked one).
shared float16_t Csh[WG_TILE_M * WG_TILE_N];

void main() {
    const uvec2 tileID = uvec2(gl_WorkGroupID.xy);
    const uvec2 sgInTile = uvec2(gl_SubgroupID % SG_GRID_X, gl_SubgroupID / SG_GRID_X);
    const int q_h = int(gl_WorkGroupID.z);

    // LLM layout: q_sizes WHCN {D, H_q, S, B}; k_sizes WHCN {D, H_kv, C_max, B}.
    const int Q_H = q_sizes.y;
    const int S = q_sizes.z;
    const int KV_H = k_sizes.y;
    const int S_aligned = align_up_4(S);
    const int context_len = input_pos + S;
    const int aw_row_width = div_up_4(context_len) * 4;
    const uint D = uint(num_k_chunks_arg) * 32u;

    int kv_h = q_h;
    if (KV_H < Q_H) {
        kv_h = q_h / (Q_H / KV_H);
    }

    const uint s_tile_base = WG_TILE_M * tileID.y;
    const uint c_tile_base = WG_TILE_N * tileID.x;
    if (c_tile_base >= uint(context_len) || s_tile_base >= uint(S)) {
        return;
    }
    // Every element of the workgroup tile is masked: nothing is read from it.
    if (int(c_tile_base) > int(s_tile_base) + int(WG_TILE_M) - 1 + input_pos) {
        return;
    }

    const uint s0 = s_tile_base + SG_TILE_M * sgInTile.y;
    const uint c0 = c_tile_base + SG_TILE_N * sgInTile.x;
    const bool sg_masked = int(c0) > int(s0) + int(SG_TILE_M) - 1 + input_pos;

    if (!sg_masked) {
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                result[i][j] = RES(0.0);
            }
        }
        const uint q_stride = uint(Q_H) * D;
        const uint k_stride = uint(KV_H) * D;
        const uint q_base = (s0 * uint(Q_H) + uint(q_h)) * D;
        const uint k_base = (c0 * uint(KV_H) + uint(kv_h)) * D;
#if ACC == 1
        for (uint kg = 0; kg < D; kg += 32u) {
            [[unroll]] for (uint i = 0; i < MI; ++i) {
                [[unroll]] for (uint j = 0; j < NJ; ++j) {
                    part[i][j] = ACC16(0.0);
                }
            }
            [[unroll]] for (uint kk = 0; kk < 32u; kk += MMA) {
                const uint k = kg + kk;
#else
        {
            for (uint k = 0; k < D; k += MMA) {
#endif
                MAT_A matA[MI];
                [[unroll]] for (uint i = 0; i < MI; ++i) {
                    coopMatLoad(matA[i], t_q, q_base + MMA * i * q_stride + k, q_stride,
                                gl_CooperativeMatrixLayoutRowMajor);
                }
                [[unroll]] for (uint j = 0; j < NJ; ++j) {
                    // B = K^T [d][c]: element (d, c) is K[c][d], a column-major read of K.
                    MAT_B matB;
                    coopMatLoad(matB, t_k, k_base + MMA * j * k_stride + k, k_stride,
                                gl_CooperativeMatrixLayoutColumnMajor);
                    [[unroll]] for (uint i = 0; i < MI; ++i) {
#if ACC == 1
                        part[i][j] = coopMatMulAdd(matA[i], matB, part[i][j]);
#else
                        result[i][j] = coopMatMulAdd(matA[i], matB, result[i][j]);
#endif
                    }
                }
            }
#if ACC == 1
            [[unroll]] for (uint i = 0; i < MI; ++i) {
                [[unroll]] for (uint j = 0; j < NJ; ++j) {
                    result[i][j] += ACC32(part[i][j]);
                }
            }
#endif
        }
    }

    // The store stride must be a compile-time value (see the release kernel's
    // header): the baked row width is used only when it is the live one.
    const bool direct =
        aw_row_width_arg == aw_row_width &&
        s_tile_base + WG_TILE_M <= uint(S) &&
        c_tile_base + WG_TILE_N <= uint(context_len);
    if (direct) {
        if (sg_masked) {
            return;
        }
        const uint STRIDE = uint(aw_row_width_arg);
        const uint aw_base = (uint(q_h) * uint(S_aligned) + s0) * STRIDE + c0;
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                // An MMA tile wholly above the diagonal is never read.
                if (int(c0 + MMA * j) <= int(s0 + MMA * i + MMA - 1u) + input_pos) {
#if ACC == 2
                    ACC16 out_tile = result[i][j] * float16_t(inv_scale);
#else
                    ACC16 out_tile = ACC16(result[i][j] * inv_scale);
#endif
                    coopMatStore(out_tile, t_attn_weights,
                                 aw_base + MMA * i * STRIDE + MMA * j, STRIDE,
                                 gl_CooperativeMatrixLayoutRowMajor);
                }
            }
        }
        return;
    }

    // Slow path: through a shared scratch with a compile-time stride, then a
    // scalar copy of the visible elements. All subgroups reach the barrier.
    if (!sg_masked) {
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
#if ACC == 2
                ACC16 out_tile = result[i][j] * float16_t(inv_scale);
#else
                ACC16 out_tile = ACC16(result[i][j] * inv_scale);
#endif
                coopMatStore(out_tile, Csh,
                             (SG_TILE_M * sgInTile.y + MMA * i) * WG_TILE_N +
                                 SG_TILE_N * sgInTile.x + MMA * j,
                             WG_TILE_N, gl_CooperativeMatrixLayoutRowMajor);
            }
        }
    }
    memoryBarrierShared();
    barrier();
    const uint WG_SIZE = SG_GRID_X * SG_GRID_Y * ${SUBGROUP_SIZE}u;
    for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * WG_TILE_N; idx += WG_SIZE) {
        const uint gs = s_tile_base + idx / WG_TILE_N;
        const uint gc = c_tile_base + idx % WG_TILE_N;
        if (gs < uint(S) && gc < uint(context_len) && int(gc) <= int(gs) + input_pos) {
            t_attn_weights[(uint(q_h) * uint(S_aligned) + gs) * uint(aw_row_width) + gc] = Csh[idx];
        }
    }
}
"""

AV = HDR % "attn*V, direct feed (no operand staging)." + """// Bindings mirror sdpa_compute_out_tiled: output(0), attn_weights(1), v(2).
${layout_declare_tensor(B, "w", "t_output", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_attn_weights", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_v", DTYPE, V_CACHE_STORAGE, is_scalar_array=True)}

${layout_declare_ubo(B, "ivec4", "q_sizes")}
${layout_declare_ubo(B, "ivec4", "v_sizes")}
${layout_declare_ubo(B, "int", "input_pos")}

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// Same spec-constant list as glsl/sarc/sarc_sdpa_av_coopmat.glsl.
${layout_declare_spec_const(C, "float", "inv_scale_unused", "1.0")}
${layout_declare_spec_const(C, "int", "gqa_group_size_unused", "1")}
${layout_declare_spec_const(C, "int", "num_k_chunks_arg", "0")}
${layout_declare_spec_const(C, "int", "out_row_stride_arg", "0")}
${layout_declare_spec_const(C, "int", "head_dim_arg", "0")}
""" + CONSTS + """
void main() {
    const uvec2 tileID = uvec2(gl_WorkGroupID.xy);
    const uvec2 sgInTile = uvec2(gl_SubgroupID % SG_GRID_X, gl_SubgroupID / SG_GRID_X);
    const int q_h = int(gl_WorkGroupID.z);

    // LLM layout: q_sizes WHCN {D, H_q, S, B}; v_sizes WHCN {D, H_kv, C_max, B}.
    const int Q_H = q_sizes.y;
    const int S = q_sizes.z;
    const int KV_H = v_sizes.y;
    const int S_aligned = align_up_4(S);
    const int context_len = input_pos + S;
    const uint W = uint(div_up_4(context_len)) * 4u;
    const uint D = uint(head_dim_arg);

    int kv_h = q_h;
    if (KV_H < Q_H) {
        kv_h = q_h / (Q_H / KV_H);
    }

    const uint s0 = WG_TILE_M * tileID.y + SG_TILE_M * sgInTile.y;
    const uint d0 = WG_TILE_N * tileID.x + SG_TILE_N * sgInTile.x;
    if (s0 >= uint(S) || d0 >= D) {
        return;
    }

    [[unroll]] for (uint i = 0; i < MI; ++i) {
        [[unroll]] for (uint j = 0; j < NJ; ++j) {
            result[i][j] = RES(0.0);
        }
    }

    // P[s, c] == 0 for c > s + input_pos (the softmax writes the masked tail as
    // zero), so the rows of this subgroup need context columns up to max_c only.
    // 32-wide groups: context_len is a multiple of 32 (the row's k).
    const uint max_c = min(s0 + SG_TILE_M - 1u + uint(input_pos), uint(context_len) - 1u);
    const uint groups = min(uint(num_k_chunks_arg), max_c / 32u + 1u);

    const uint a_base = (uint(q_h) * uint(S_aligned) + s0) * W;
    const uint v_stride = uint(KV_H) * D;
    const uint b_base = uint(kv_h) * D + d0;

    for (uint grp = 0; grp < groups; ++grp) {
#if ACC == 1
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                part[i][j] = ACC16(0.0);
            }
        }
#endif
        [[unroll]] for (uint kk = 0; kk < 32u; kk += MMA) {
            const uint c = grp * 32u + kk;
            MAT_A matA[MI];
            [[unroll]] for (uint i = 0; i < MI; ++i) {
                coopMatLoad(matA[i], t_attn_weights, a_base + MMA * i * W + c, W,
                            gl_CooperativeMatrixLayoutRowMajor);
            }
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                MAT_B matB;
                coopMatLoad(matB, t_v, c * v_stride + b_base + MMA * j, v_stride,
                            gl_CooperativeMatrixLayoutRowMajor);
                [[unroll]] for (uint i = 0; i < MI; ++i) {
#if ACC == 1
                    part[i][j] = coopMatMulAdd(matA[i], matB, part[i][j]);
#else
                    result[i][j] = coopMatMulAdd(matA[i], matB, result[i][j]);
#endif
                }
            }
        }
#if ACC == 1
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                result[i][j] += ACC32(part[i][j]);
            }
        }
#endif
    }

    // DHSB output, head-interleaved; the stride is a spec constant.
    const uint out_row_stride = uint(out_row_stride_arg);
    const uint out_base = s0 * out_row_stride + uint(q_h) * D + d0;
    [[unroll]] for (uint i = 0; i < MI; ++i) {
        [[unroll]] for (uint j = 0; j < NJ; ++j) {
#if ACC == 2
            coopMatStore(result[i][j], t_output,
#else
            ACC16 out_tile = ACC16(result[i][j]);
            coopMatStore(out_tile, t_output,
#endif
                         out_base + MMA * i * out_row_stride + MMA * j, out_row_stride,
                         gl_CooperativeMatrixLayoutRowMajor);
        }
    }
}
"""

PRE = {0: "df", 1: "dfg", 2: "dfh"}
def V(m, n, sx, sy, acc=0, nf=False):
    assert sx * sy * SG <= WG_MAX and 2048 % m == 0 and m % (16 * sy) == 0 and n % (16 * sx) == 0
    return dict(tok=f"{PRE[acc]}_t{m}x{n}k32g{sx}{sy}s{SG}" + ("nf" if nf else ""), m=m, n=n, sx=sx, sy=sy, acc=acc)
def yaml(family, what, cache, variants):
    v0 = variants[0]
    out = f"# SARC development zone, RTX 4070 Ti SUPER: {what} (generated by gen_4070ti_df.py). Not shipped.\n\n{family}:\n"
    out += f"  parameter_names_with_default_values:\n    DTYPE: half\n    PRECISION: highp\n    IO_STORAGE: buffer\n    {cache}: buffer\n"
    out += f"    WG_TILE_M: {v0['m']}\n    WG_TILE_N: {v0['n']}\n    SG_GRID_X: {v0['sx']}\n    SG_GRID_Y: {v0['sy']}\n    SUBGROUP_SIZE: {SG}\n    ACC: 0\n"
    out += f"  generate_variant_forall:\n    combination:\n      parameter_names: [IO_STORAGE, {cache}]\n      combos:\n        - parameter_values: [buffer, buffer]\n    DTYPE:\n      - VALUE: half\n  shader_variants:\n"
    for v in variants:
        out += f"    - NAME: {family[:-3]}_{v['tok']}\n      WG_TILE_M: {v['m']}\n      WG_TILE_N: {v['n']}\n      SG_GRID_X: {v['sx']}\n      SG_GRID_Y: {v['sy']}\n      SUBGROUP_SIZE: {SG}\n      ACC: {v['acc']}\n"
    return out

# Subgroup tile = (m / sy) x (n / sx); MI x NJ accumulators of 16 x 16 per subgroup.
QKV = [V(64, 64, 1, 1, 0, True), V(32, 64, 1, 1, 0, True), V(64, 32, 1, 1, 0, True), V(32, 32, 1, 1, 0, True),
       V(16, 64, 1, 1, 0, True), V(128, 64, 2, 2, 0, True), V(128, 64, 4, 2, 0, True), V(64, 64, 2, 2, 0, True),
       V(128, 128, 2, 2, 0, True), V(64, 64, 1, 1, 1, True), V(32, 64, 1, 1, 1, True), V(64, 64, 1, 1, 2, True),
       V(32, 64, 1, 1, 2, True), V(64, 64, 2, 2, 1, True), V(64, 64, 2, 2, 2, True)]
for v in QKV: assert 2 * v["m"] * v["n"] <= LDS_MAX, v["tok"]
# attn*V: one subgroup spans the whole head_dim where it can (64-column tiles fit both head dims).
AVV = [V(16, 64, 1, 1), V(32, 64, 1, 1), V(64, 64, 1, 1), V(64, 64, 1, 2), V(32, 64, 2, 1), V(16, 128, 1, 1),
       V(32, 128, 1, 1), V(32, 128, 2, 1), V(64, 128, 2, 1), V(64, 128, 2, 2), V(32, 64, 1, 1, 1), V(32, 128, 1, 1, 1),
       V(32, 128, 2, 1, 1), V(32, 64, 1, 1, 2), V(32, 128, 1, 1, 2), V(32, 128, 2, 1, 2), V(64, 64, 1, 1, 1), V(64, 64, 1, 1, 2)]
F_QK, F_AV = "sarc_sdpa_qk_coopmat_4070ti_df", "sarc_sdpa_av_coopmat_4070ti_df"
write_new(g / f"sarc_dev/{F_QK}.glsl", QK); write_new(g / f"sarc_dev/{F_QK}.yaml", yaml(F_QK, "QK^T, direct feed", "K_CACHE_STORAGE", QKV))
write_new(g / f"sarc_dev/{F_AV}.glsl", AV); write_new(g / f"sarc_dev/{F_AV}.yaml", yaml(F_AV, "attn*V, direct feed", "V_CACHE_STORAGE", AVV))

o = root / "impl/sarc_dev/Overrides.cpp"
rows = "    // RTX 4070 Ti SUPER direct-feed SDPA kernels: glsl/sarc_dev/sarc_sdpa_{qk,av}_coopmat_4070ti_df.yaml.\n"
prefs = "// RTX 4070 Ti SUPER: single-kernel screening profiles of the direct-feed SDPA kernels.\n"
profs = ""
for op, fam, vs, kind in (("kSdpaQk", F_QK, QKV, "qk"), ("kSdpaAv", F_AV, AVV, "av")):
    for v in vs:
        cid = f"k4070ti_{kind}_{v['tok']}"
        rows += f'    {{"", nullptr, Op::{op},\n     "{fam[:-3]}_{v["tok"]}",\n     {{{v["m"]}, {v["n"]}, 32, {v["sx"]}, {v["sy"]}, {SG}, 16, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n'
        prefs += f'const Preference {cid}[] = {{{{Op::{op}, "4070ti_{v["tok"]}", nullptr}}}};\n'
        profs += f'    {{"4070ti-{kind}-{v["tok"]}", {cid}, 1}},\n'
put_block(o, "};\n\nstd::string& requested_variant() {", "df-rows", rows, "    ")
put_block(o, "struct Profile {\n", "df-preferences", prefs)
put_block(o, "};\nconst Profile* requested_profile() {", "df-profiles", profs, "    ")
print(f"4070ti direct-feed sdpa: {len(QKV)} QK^T and {len(AVV)} attn*V variants")
