#!/usr/bin/env python3
"""A fused prefill attention kernel for the RTX 4070 Ti SUPER (dev zone, measurement through a local hook).

usage: gen_4070ti_fused.py <executorch tree>

  glsl/sarc_dev/sarc_sdpa_fused_coopmat_4070ti.{glsl,yaml}   variants c<column tile>d<head_dim>

Why: with the SDPA kernels of candidate 1 the attention block is bound by memory traffic. Per layer and head the
S x context fp16 score matrix is written by QK^T, read and rewritten by the softmax and read by attn*V: on 1B that
is 134 + 134 + 268 + 134 MB per layer against 8 MB of real inputs and outputs. This kernel never materialises
the matrix. One workgroup (one subgroup of 32) owns 16 rows of one head and walks the visible context in column
tiles, twice:
  pass 1: scores = Q K^T for the tile (MMA fed directly from the tensors) -> shared memory -> running row maximum;
  pass 2: the same scores again -> e = exp(score - row max) in shared memory, row sums, then out += e V (MMA, the
          e tile loaded from shared memory, V directly from the tensor);
  end:    out / row sum -> output.
QK^T is computed twice because a cooperative-matrix accumulator cannot be rescaled per row (no online softmax);
its cost is small next to the traffic it replaces. Accumulation is fp32 as in the release kernels; the softmax
is evaluated in fp32 and normalised after the attn*V accumulation instead of before it, so results are not
bit-identical to the three-kernel path: the measured error is part of the candidate's evidence.

NOT REACHABLE FROM THE DEV ZONE. LLM-mode SDPA is three nodes (QK^T, softmax, attn*V) built by impl/SDPA.cpp;
a fused kernel needs one node bound to q, k_cache, v_cache and out. tools/local-hook-fused-sdpa.patch (not
committed) adds that node behind ET_VK_SARC_FUSED_SDPA=<column tile> and reduces the three nodes to one junk
workgroup each when the fused kernel applies (S a multiple of 16, context a multiple of the column tile,
head_dim 64 or 128, fp16 buffers); the kernel checks the same shape condition itself and does nothing otherwise,
so decode and unaligned prompts keep the three-node path. The hook that a release would need is in proposal.md.
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new
g = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops/glsl"
SRC = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_fused.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine). Fused LLM-mode prefill attention:
 * out = softmax(Q K^T * inv_scale, causal) V without materialising the score matrix.
 * One workgroup = one subgroup of 32 = 16 rows of one head.
 */

#version 450 core

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_control_flow_attributes : enable

#define PRECISION ${PRECISION}

layout(std430) buffer;

#include "common.glslh"

${layout_declare_tensor(B, "w", "t_output", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_q", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_k", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_v", DTYPE, IO_STORAGE, is_scalar_array=True)}

${layout_declare_ubo(B, "ivec4", "q_sizes")}
${layout_declare_ubo(B, "ivec4", "k_sizes")}
${layout_declare_ubo(B, "int", "input_pos")}

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

${layout_declare_spec_const(C, "float", "inv_scale", "1.0")}
${layout_declare_spec_const(C, "int", "out_row_stride_arg", "0")}

const uint MMA = 16u;
const uint TILE_C = ${TILE_C};
const uint D = ${HEAD_DIM};
const uint NJ = TILE_C / MMA;
const uint ND = D / MMA;
const uint HALF_C = TILE_C / 2u;
const uint HALF_D = D / 2u;

#define ACC32 coopmat<float, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define ACC16 coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define MAT_A coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseA>
#define MAT_B coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseB>

// 16 rows x TILE_C: scores, then exp(score - row max), row-major.
shared float16_t Ssh[MMA * TILE_C];
// 16 rows x head_dim: the unnormalised output.
shared float Osh[MMA * D];
// Row reductions: each row is shared by two threads.
shared float red[32];

ACC32 sacc[NJ];
ACC32 oacc[ND];

uint q_base, q_stride, kv_head, kv_stride;

// Scores of rows s0 .. s0 + 15 against context c0 .. c0 + TILE_C - 1 into Ssh.
void qk_tile(const uint c0) {
    [[unroll]] for (uint j = 0; j < NJ; ++j) {
        sacc[j] = ACC32(0.0);
    }
    [[unroll]] for (uint k = 0; k < D; k += MMA) {
        MAT_A a;
        coopMatLoad(a, t_q, q_base + k, q_stride, gl_CooperativeMatrixLayoutRowMajor);
        [[unroll]] for (uint j = 0; j < NJ; ++j) {
            // K^T [d][c] is a column-major read of K [c][d].
            MAT_B b;
            coopMatLoad(b, t_k, (c0 + MMA * j) * kv_stride + kv_head + k, kv_stride,
                        gl_CooperativeMatrixLayoutColumnMajor);
            sacc[j] = coopMatMulAdd(a, b, sacc[j]);
        }
    }
    [[unroll]] for (uint j = 0; j < NJ; ++j) {
        ACC16 o = ACC16(sacc[j] * inv_scale);
        coopMatStore(o, Ssh, MMA * j, TILE_C, gl_CooperativeMatrixLayoutRowMajor);
    }
}

void main() {
    // LLM layout: q_sizes WHCN {D, H_q, S, B}; k_sizes WHCN {D, H_kv, C_max, B}.
    const int Q_H = q_sizes.y;
    const int S = q_sizes.z;
    const int KV_H = k_sizes.y;
    const int context_len = input_pos + S;
    // The hook dispatches this kernel for every shape; it only acts on the
    // shapes it covers (the same condition as in the hook).
    if (q_sizes.x != int(D) || S <= 1 || (S & 15) != 0 ||
        (uint(context_len) % TILE_C) != 0u) {
        return;
    }
    const int q_h = int(gl_WorkGroupID.z);
    int kv_h = q_h;
    if (KV_H < Q_H) {
        kv_h = q_h / (Q_H / KV_H);
    }
    const uint s0 = MMA * gl_WorkGroupID.y;
    if (s0 >= uint(S)) {
        return;
    }

    const uint t = gl_LocalInvocationID.x;
    const uint r = t & 15u;   // row within the block
    const uint h = t >> 4u;   // which half of the columns this thread reduces
    const uint gs = s0 + r;
    // Columns below vis_end are visible to this thread's row (causal mask).
    const uint vis_end = min(gs + uint(input_pos) + 1u, uint(context_len));
    const uint blk_end = min(s0 + MMA + uint(input_pos), uint(context_len));
    const uint n_tiles = (blk_end + TILE_C - 1u) / TILE_C;

    q_stride = uint(Q_H) * D;
    q_base = (s0 * uint(Q_H) + uint(q_h)) * D;
    kv_stride = uint(KV_H) * D;
    kv_head = uint(kv_h) * D;

    const uint sh_base = r * TILE_C + h * HALF_C;

    // ---- pass 1: row maximum ----
    float row_max = -3.0e38;
    for (uint tile = 0; tile < n_tiles; ++tile) {
        const uint c0 = tile * TILE_C;
        qk_tile(c0);
        memoryBarrierShared();
        barrier();
        const uint cbase = c0 + h * HALF_C;
        for (uint i = 0; i < HALF_C; ++i) {
            if (cbase + i < vis_end) {
                row_max = max(row_max, float(Ssh[sh_base + i]));
            }
        }
        memoryBarrierShared();
        barrier();
    }
    red[t] = row_max;
    memoryBarrierShared();
    barrier();
    row_max = max(red[r], red[r + 16u]);
    memoryBarrierShared();
    barrier();

    // ---- pass 2: e = exp(score - max), row sum, out += e V ----
    [[unroll]] for (uint d = 0; d < ND; ++d) {
        oacc[d] = ACC32(0.0);
    }
    float row_sum = 0.0;
    for (uint tile = 0; tile < n_tiles; ++tile) {
        const uint c0 = tile * TILE_C;
        qk_tile(c0);
        memoryBarrierShared();
        barrier();
        const uint cbase = c0 + h * HALF_C;
        for (uint i = 0; i < HALF_C; ++i) {
            float e = 0.0;
            if (cbase + i < vis_end) {
                e = exp(float(Ssh[sh_base + i]) - row_max);
            }
            row_sum += e;
            Ssh[sh_base + i] = float16_t(e);
        }
        memoryBarrierShared();
        barrier();
        [[unroll]] for (uint j = 0; j < NJ; ++j) {
            MAT_A a;
            coopMatLoad(a, Ssh, MMA * j, TILE_C, gl_CooperativeMatrixLayoutRowMajor);
            [[unroll]] for (uint d = 0; d < ND; ++d) {
                MAT_B b;
                coopMatLoad(b, t_v, (c0 + MMA * j) * kv_stride + kv_head + MMA * d, kv_stride,
                            gl_CooperativeMatrixLayoutRowMajor);
                oacc[d] = coopMatMulAdd(a, b, oacc[d]);
            }
        }
        memoryBarrierShared();
        barrier();
    }
    red[t] = row_sum;
    [[unroll]] for (uint d = 0; d < ND; ++d) {
        coopMatStore(oacc[d], Osh, MMA * d, D, gl_CooperativeMatrixLayoutRowMajor);
    }
    memoryBarrierShared();
    barrier();
    const float inv_sum = 1.0 / (red[r] + red[r + 16u]);

    // DHSB output, head-interleaved rows.
    const uint out_base = gs * uint(out_row_stride_arg) + uint(q_h) * D + h * HALF_D;
    const uint o_base = r * D + h * HALF_D;
    for (uint i = 0; i < HALF_D; ++i) {
        t_output[out_base + i] = float16_t(Osh[o_base + i] * inv_sum);
    }
}
"""
F = "sarc_sdpa_fused_coopmat_4070ti"
write_new(g / f"sarc_dev/{F}.glsl", SRC)
y = f"""# SARC development zone, RTX 4070 Ti SUPER: fused prefill attention (generated by gen_4070ti_fused.py). Not shipped.
# Shared memory: 16 * TILE_C * 2 + 16 * HEAD_DIM * 4 + 128 bytes.

{F}:
  parameter_names_with_default_values:
    DTYPE: half
    PRECISION: highp
    IO_STORAGE: buffer
    TILE_C: 64
    HEAD_DIM: 64
  shader_variants:
"""
for c in (32, 64, 128, 256):
    for d in (64, 128):
        assert 16 * c * 2 + 16 * d * 4 + 128 <= 49152
        y += f"    - NAME: {F}_c{c}d{d}_buffer_half\n      TILE_C: {c}\n      HEAD_DIM: {d}\n"
write_new(g / f"sarc_dev/{F}.yaml", y)
print("4070ti fused sdpa generated")
