#!/usr/bin/env python3
"""Measurement-only phase-timing (PROF) twins of the two linear kernels the RTX 4070 Ti SUPER ships.

usage: gen_4070ti_prof.py <executorch tree>

Replaces the 780M campaign's gen_prof.py and apply_prof_hooks.py for this device. Reads the release bodies and
yamls and the sweep wrappers (never writes them) and writes only new files and marked blocks:

  glsl/sarc_dev/sarc_dev_prof_4070ti_q4gsw{.glsl,.yaml,_body.glslh}         4w, the shipped `ga` tiles
  glsl/sarc_dev/sarc_dev_prof_4070ti_dq8ca_zpgtr{.glsl,.yaml,_body.glslh}   8da4w zpgtr t128x128k64g44s32mk32ra
  impl/sarc_dev/Overrides.cpp   `// >>> 4070ti prof-q4gsw-rows` and `// >>> 4070ti prof-dq8ca-rows`

Each wave keeps one running shader-clock timestamp (VK_KHR_shader_clock; shaderSubgroupClock is reported by this
device) and PTICK(x) adds the cycles since the previous tick to phase x. Subgroup 0 of every workgroup overwrites
the first 8 output elements of its tile with
  [barrier, fetch, mma, lds_store] / iterations   and   [prologue, group_epilog, drain, write] / 64.
The outputs of these kernels are therefore wrong by construction: they are selected only by name, with
ET_VK_SARC_Q4GSW_VARIANT / ET_VK_SARC_DQ8CA_VARIANT=<tile token ending in p>, and read back with
ET_VK_DUMP_OUTPUT_DIR and prof_decode.py. They are never gated and never part of a profile.

What the phases mean here (differences from the 780M twins):
  4w `ga` (ACC_GROUP_FP32): the per-group fp16 -> fp32 fold is not ticked separately; it is counted in the phase
    it is coded in (mma). iterations = K / 16.
  zpgtr: drain (accumulator -> LDS) and write (imageStore / coopMatStore) are not separated: both are in `write`
    and `drain` reads 0. The hoisted zero-point correction is counted in group_epilog. iterations = K / 64.
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ops = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
root = ops / "glsl"

def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)

DECL = """void main() {
  // PROF (measurement only): per-phase shader-clock cycles of this wave.
  uint p_pro = 0u, p_bar = 0u, p_pre = 0u, p_mma = 0u, p_st = 0u, p_ep = 0u, p_dr = 0u, p_wr = 0u;
  uint p_t = clock2x32ARB().x;
#define PTICK(acc) { const uint p_n = clock2x32ARB().x; acc += (p_n - p_t) & 0xFFFFFu; p_t = p_n; }
"""
OUT = """
  // PROF output: subgroup 0 writes the phase means into the first 8 elements of its tile.
  PTICK(p_wr)
  {
    const float it = float(max(num_chunks, 1u));
    const vec4 v0 = vec4(float(p_bar), float(p_pre), float(p_mma), float(p_st)) / it;
    const vec4 v1 = vec4(float(p_pro), float(p_ep), float(p_dr), float(p_wr)) / 64.0;
#ifdef IO_TEXTURE
    memoryBarrierImage();
    barrier();
    if (gl_SubgroupID == 0u && subgroupElect()) {
      imageStore(t_output, ivec3(tile_n_start / 4u, tile_m_start, 0), v0);
      imageStore(t_output, ivec3(tile_n_start / 4u + 1u, tile_m_start, 0), v1);
    }
#else
    memoryBarrierBuffer();
    barrier();
    if (gl_SubgroupID == 0u && subgroupElect()) {
      const uint pb = tile_m_start * uint(out_N_arg) + tile_n_start;
      [[unroll]] for (uint c = 0; c < 4u; ++c) {
        t_output[pb + c] = float16_t(v0[c]);
        t_output[pb + 4u + c] = float16_t(v1[c]);
      }
    }
#endif
  }
}
"""
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER, MEASUREMENT ONLY: phase-timing twin of %s
 * (generated by gen_4070ti_prof.py; see openspec/changes/sarc-1.5-4070ti-prefill-refine). Its output is
 * overwritten with cycle counts, so it must never be selected for a model.
 */

"""
YH = "# SARC development zone, RTX 4070 Ti SUPER, MEASUREMENT ONLY (phase timing, generated by gen_4070ti_prof.py). Never shipped.\n\n"
def wrapper(sweep, body, prof_body):
    w = (root / f"sarc_dev/{sweep}.glsl").read_text()
    w = w[w.index("#version 450 core"):]
    w = sub(w, "#extension GL_EXT_control_flow_attributes : enable\n",
            "#extension GL_EXT_control_flow_attributes : enable\n#extension GL_ARB_shader_clock : require\n")
    return sub(w, f'#include "{body}"', f'#include "{prof_body}"')
def defaults(release_yaml):
    y = (root / f"sarc/{release_yaml}").read_text()
    return y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
def shipped(release_yaml, name):
    """The parameter lines of one shipped variant, copied from the release yaml."""
    y = (root / f"sarc/{release_yaml}").read_text()
    i = y.index(f"    - NAME: {name}\n") + len(f"    - NAME: {name}\n"); out = ""
    for l in y[i:].splitlines(keepends=True):
        if not l.startswith("      "): break
        out += l
    return out

# ---------------- 4w (`ga` tiles) ----------------
F4 = "sarc_dev_prof_4070ti_q4gsw"
b = (root / "sarc/sarc_linear_q4gsw_coopmat_body.glslh").read_text()
b = sub(b, "SARC_LINEAR_Q4GSW_COOPMAT_BODY_GLSLH", "SARC_DEV_PROF_4070TI_Q4GSW_BODY_GLSLH", b.count("SARC_LINEAR_Q4GSW_COOPMAT_BODY_GLSLH"))
b = sub(b, "void main() {\n", DECL)
b = sub(b, "  uint chunk;\n  for (chunk = 0; chunk + 1u < num_chunks; ++chunk) {",
        "  PTICK(p_pro)\n  uint chunk;\n  for (chunk = 0; chunk + 1u < num_chunks; ++chunk) {")
b = sub(b, "    memoryBarrierShared();\n    barrier();\n\n    // --- prefetch chunk+1 -> temp ---",
        "    memoryBarrierShared();\n    barrier();\n    PTICK(p_bar)\n\n    // --- prefetch chunk+1 -> temp ---")
b = sub(b, "    // --- MMA math on the cur slice ---", "    PTICK(p_pre)\n    // --- MMA math on the cur slice ---")
b = sub(b, "    // --- store temp (chunk+1) -> nxt slice, dequantizing B ---",
        "    PTICK(p_mma)\n    // --- store temp (chunk+1) -> nxt slice, dequantizing B ---")
b = sub(b, "    }\n  }\n\n  // --- epilogue: barrier, then MMA on the last chunk (loop peeled) ---",
        "    }\n    PTICK(p_st)\n  }\n\n  // --- epilogue: barrier, then MMA on the last chunk (loop peeled) ---")
b = sub(b, "    memoryBarrierShared();\n    barrier();\n\n    [[unroll]] for (uint k = 0; k < WG_TILE_K / MMA_K; ++k) {",
        "    memoryBarrierShared();\n    barrier();\n    PTICK(p_bar)\n\n    [[unroll]] for (uint k = 0; k < WG_TILE_K / MMA_K; ++k) {")
b = sub(b, "  // --- Bias staging (if any) ---", "  PTICK(p_mma)\n  // --- Bias staging (if any) ---")
b = sub(b, "    }\n    memoryBarrierShared();\n    barrier();\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {",
        "    }\n    memoryBarrierShared();\n    barrier();\n    PTICK(p_dr)\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {")
b = sub(b, "#endif\n    }\n  }\n#endif // CSH_FULL / CSH_BAND", "#endif\n    }\n    PTICK(p_wr)\n  }\n#endif // CSH_FULL / CSH_BAND")
b = sub(b, "#endif // IO_TEXTURE\n}\n", "#endif // IO_TEXTURE\n" + OUT)
b = b.replace("// Body of sarc_linear_q4gsw_coopmat;", "// GENERATED by gen_4070ti_prof.py (measurement only, never shipped). Body of sarc_linear_q4gsw_coopmat;", 1)
write_new(root / f"sarc_dev/{F4}_body.glslh", b)
write_new(root / f"sarc_dev/{F4}.glsl", HDR % "sarc_linear_q4gsw_coopmat" +
          wrapper("sarc_linear_q4gsw_coopmat_sweep", "sarc_linear_q4gsw_coopmat_body.glslh", f"{F4}_body.glslh"))
# (tile token, storage suffixes, TileDims, storages): the rows of impl/sarc/table_nvidia.cpp
Q4 = [("t256x128k16g42s32ga", ["texture3d_texture2d"], "{256, 128, 16, 4, 2, 32, 16, false}", "kTex3dTex2d"),
      ("t128x128k16g24s32ga", ["texture3d_texture2d"], "{128, 128, 16, 2, 4, 32, 16, false}", "kTex3dTex2d"),
      ("t128x256k16g42s32ga", ["buffer_texture2d"], "{128, 256, 16, 4, 2, 32, 16, false}", "kBufTex2d"),
      ("t128x128k16g42s32ga", ["buffer_texture2d", "buffer_buffer"], "{128, 128, 16, 4, 2, 32, 16, false}", "kBufTex2d | kBufBuf")]
y = YH + f"{F4}:\n" + defaults("sarc_linear_q4gsw_coopmat.yaml") + "  shader_variants:\n"
rows4 = "    // RTX 4070 Ti SUPER phase timing, MEASUREMENT ONLY (glsl/sarc_dev/sarc_dev_prof_4070ti_q4gsw.yaml):\n    // the shipped `ga` tiles with shader-clock phase counters written over their output.\n"
for tok, sts, dims, mask in Q4:
    for st in sts:
        y += f"    - NAME: {F4}_{tok}p_{st}_half\n" + shipped("sarc_linear_q4gsw_coopmat.yaml", f"sarc_linear_q4gsw_coopmat_{tok}_{st}_half")
    rows4 += f'    {{"", nullptr, Op::kQ4gswLinear,\n     "{F4}_{tok}p", {dims},\n     {mask}, nullptr, Status::kUnverified}},\n'
write_new(root / f"sarc_dev/{F4}.yaml", y)

# ---------------- 8da4w zpgtr ----------------
F8 = "sarc_dev_prof_4070ti_dq8ca_zpgtr"
b = (root / "sarc/sarc_linear_dq8ca_coopmat_zpgtr_body.glslh").read_text()
b = sub(b, "SARC_LINEAR_DQ8CA_COOPMAT_ZPGTR_BODY_GLSLH", "SARC_DEV_PROF_4070TI_DQ8CA_ZPGTR_BODY_GLSLH", b.count("SARC_LINEAR_DQ8CA_COOPMAT_ZPGTR_BODY_GLSLH"))
b = sub(b, "void main() {\n", DECL)
b = sub(b, "  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {",
        "  PTICK(p_pro)\n  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {")
b = sub(b, "      memoryBarrierShared();\n      barrier();\n\n      // --- 2. prefetch chunk+1 -> temp ---",
        "      memoryBarrierShared();\n      barrier();\n      PTICK(p_bar)\n\n      // --- 2. prefetch chunk+1 -> temp ---")
b = sub(b, "      // --- 3. int8 MMA on the cur slice ---", "      PTICK(p_pre)\n      // --- 3. int8 MMA on the cur slice ---")
b = sub(b, "      // --- 4. store temp (chunk+1) -> nxt slice ---", "      PTICK(p_mma)\n      // --- 4. store temp (chunk+1) -> nxt slice ---")
b = sub(b, "    }  // chunks", "      PTICK(p_st)\n    }  // chunks")
b = sub(b, "  }  // groups", "    PTICK(p_ep)\n  }  // groups")
b = sub(b, "  // --- Bias (optional) ---", "  PTICK(p_ep)\n  // --- Bias (optional) ---")
b = sub(b, "#endif // IO_TEXTURE\n}\n", "#endif // IO_TEXTURE\n" + OUT)
b = "// GENERATED by gen_4070ti_prof.py (measurement only, never shipped) from sarc_linear_dq8ca_coopmat_zpgtr_body.glslh.\n" + b
write_new(root / f"sarc_dev/{F8}_body.glslh", b)
write_new(root / f"sarc_dev/{F8}.glsl", HDR % "sarc_linear_dq8ca_coopmat_zpgtr" +
          wrapper("sarc_linear_dq8ca_coopmat_zpgtr_sweep", "sarc_linear_dq8ca_coopmat_zpgtr_body.glslh", f"{F8}_body.glslh"))
tok = "t128x128k64g44s32mk32ra"
y = YH + f"{F8}:\n" + defaults("sarc_linear_dq8ca_coopmat_zpgtr.yaml") + "  shader_variants:\n"
for st in ("buffer_texture2d", "texture3d_texture2d"):
    y += f"    - NAME: {F8}_{tok}p_{st}_half\n" + shipped("sarc_linear_dq8ca_coopmat_zpgtr.yaml", f"sarc_linear_dq8ca_coopmat_zpgtr_{tok}_{st}_half")
write_new(root / f"sarc_dev/{F8}.yaml", y)
rows8 = f"""    // RTX 4070 Ti SUPER phase timing, MEASUREMENT ONLY (glsl/sarc_dev/sarc_dev_prof_4070ti_dq8ca_zpgtr.yaml).
    {{"", nullptr, Op::kDq8caLinear,
     "{F8}_{tok}p", {{128, 128, 64, 4, 4, 32, 16, true}},
     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified,
     /*rowmajor_a=*/true}},
"""
o = ops / "impl/sarc_dev/Overrides.cpp"
put_block(o, "};\n\n// dq8ca (8da4w) sweep candidates, selected with ET_VK_SARC_DQ8CA_VARIANT.", "prof-q4gsw-rows", rows4, "    ")
put_block(o, "    // >>> 4070ti sdpa-rows\n", "prof-dq8ca-rows", rows8, "    ")
print("4070ti prof twins generated")
