#!/usr/bin/env python3
"""SDPA prefill kernels for the RTX 4070 Ti SUPER as dev-zone families of their own.

usage: gen_4070ti_sdpa.py <executorch tree>

Replaces the 780M campaign's gen_sdpa.py, gen_qkpk.py and gen_avml.py for this device. It reads the release
shaders glsl/sarc/sarc_sdpa_{qk,av}_coopmat.glsl (never writes them) and writes only new files and marked blocks:

  glsl/sarc_dev/sarc_sdpa_qk_coopmat_4070ti.{glsl,yaml}     QK^T, release body + NO_MASK_FILL
  glsl/sarc_dev/sarc_sdpa_qk_coopmat_4070ti_pk.{glsl,yaml}  QK^T, packed staging (uvec4 LDS, ColumnMajor B)
  glsl/sarc_dev/sarc_sdpa_av_coopmat_4070ti.{glsl,yaml}     attn*V, release body
  glsl/sarc_dev/sarc_sdpa_av_coopmat_4070ti_ml.{glsl,yaml}  attn*V, multi-pass staging (tiles other than 64 x 64)
  impl/sarc_dev/Overrides.cpp                               three `// >>> 4070ti sdpa-*` blocks: candidate rows,
                                                            preferences, profiles (4070ti-qk-*, 4070ti-av-*,
                                                            4070ti-refine1)

The shader transformations are the 780M campaign's, applied to the same release sources; what is specific to this
device is the variant list, pruned statically: subgroup size 32 only (the device has no other), fp16 MMA
16 x 16 x 16, at most 1024 invocations per workgroup, shared memory at most 49152 bytes (vulkaninfo, driver
615.71.09), and tiles that divide S = 2048, context 2048 and head_dim 64 (1B) / 128 (3B, 8B).

Kernel names keep the sarc_sdpa_qk_ / sarc_sdpa_av_ prefixes that impl/sarc/SdpaCoopmat.cpp:sdpa_gwg keys on and
contain "coopmat" and, for NO_MASK_FILL, a tile token ending in "s32nf" (the test's pairing check). The device tag
follows the family name, so profile tokens start with "4070ti_" and match no other device's rows.

NO_MASK_FILL is only valid with the truncated SARC softmax. On this device that softmax, and the spec constants
of these kernels, are only enabled when the device has active SDPA rows: impl/sarc_dev/Rtx4070tiSdpa.cpp registers
them from the dev zone (up to build topic11: superseded/local-hook-nvidia-sdpa.patch, never committed).
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
g = root / "glsl"
LDS_MAX, WG_MAX, SG = 49152, 1024, 32
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)
def hdr(what):
    return f"""/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_sdpa.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine). {what}
 */

"""
def yaml(family, what, cache, extra_default, variants):
    v0 = variants[0]
    out = f"# SARC development zone, RTX 4070 Ti SUPER: {what} (generated by gen_4070ti_sdpa.py). Not shipped.\n\n{family}:\n"
    out += f"  parameter_names_with_default_values:\n    DTYPE: half\n    PRECISION: highp\n    IO_STORAGE: buffer\n    {cache}: buffer\n    MMA_M: 16\n    MMA_N: 16\n    MMA_K: 16\n"
    out += f"    WG_TILE_M: {v0['m']}\n    WG_TILE_N: {v0['n']}\n    WG_TILE_K: {v0['k']}\n    SG_GRID_X: {v0['sx']}\n    SG_GRID_Y: {v0['sy']}\n    SUBGROUP_SIZE: {SG}\n{extra_default}"
    out += f"  generate_variant_forall:\n    combination:\n      parameter_names: [IO_STORAGE, {cache}]\n      combos:\n        - parameter_values: [buffer, buffer]\n    DTYPE:\n      - VALUE: half\n  shader_variants:\n"
    for v in variants:
        out += f"    - NAME: {family}_{v['tok']}\n      WG_TILE_M: {v['m']}\n      WG_TILE_N: {v['n']}\n      WG_TILE_K: {v['k']}\n      SG_GRID_X: {v['sx']}\n      SG_GRID_Y: {v['sy']}\n      SUBGROUP_SIZE: {SG}\n"
        if v.get("nf") is not None and "NO_MASK_FILL" in extra_default: out += f"      NO_MASK_FILL: {'true' if v['nf'] else 'false'}\n"
    return out
def V(m, n, k, sx, sy, nf=None):
    assert sx * sy * SG <= WG_MAX and 2048 % m == 0 and m % (16 * sy) == 0 and n % (16 * sx) == 0
    return dict(tok=f"t{m}x{n}k{k}g{sx}{sy}s{SG}" + ("nf" if nf else ""), m=m, n=n, k=k, sx=sx, sy=sy, nf=nf)

# ---- QK^T: release body + NO_MASK_FILL (transformation of the 780M gen_sdpa.py) ----
q = (g / "sarc/sarc_sdpa_qk_coopmat.glsl").read_text()
q = q[q.index("#version 450 core"):]
q = sub(q, "#define PRECISION ${PRECISION}\n", """#define PRECISION ${PRECISION}

// NO_MASK_FILL: do not write attn_weights elements that the truncated softmax
// never reads (c > s + input_pos). Valid only with sarc_sdpa_attn_weights_softmax.
$if NO_MASK_FILL:
  #define NO_MASK_FILL
""")
q = sub(q, """    const bool tile_all_visible =
        tile_in_extent && aw_stride_is_static &&
        (int(c_tile_base) + int(WG_TILE_N) - 1 <= int(s_tile_base) + input_pos);
""", """#ifdef NO_MASK_FILL
    // A diagonal tile's masked elements are never read, so it needs no mask:
    // every executed tile takes the direct store.
    const bool tile_all_visible = tile_in_extent && aw_stride_is_static;
#else
    const bool tile_all_visible =
        tile_in_extent && aw_stride_is_static &&
        (int(c_tile_base) + int(WG_TILE_N) - 1 <= int(s_tile_base) + input_pos);
#endif
""")
q = sub(q, "    if (tile_all_masked) {\n        for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * WG_TILE_N;",
        "    if (tile_all_masked) {\n#ifdef NO_MASK_FILL\n        return;\n#endif\n        for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * WG_TILE_N;")
QK = [V(128, 64, 32, 4, 2, True), V(128, 64, 32, 4, 2, False), V(128, 64, 32, 2, 4, True), V(128, 64, 32, 2, 2, True)]
for v in QK: assert 2 * (v["m"] * 40 + 32 * (v["n"] + 8) + v["m"] * v["n"]) <= LDS_MAX, v["tok"]   # Ash + Bsh + Csh, fp16
F_QK = "sarc_sdpa_qk_coopmat_4070ti"
write_new(g / f"sarc_dev/{F_QK}.glsl", hdr("QK^T: glsl/sarc/sarc_sdpa_qk_coopmat.glsl plus NO_MASK_FILL (see the define below).") + q)
write_new(g / f"sarc_dev/{F_QK}.yaml", yaml(F_QK, "QK^T with NO_MASK_FILL", "K_CACHE_STORAGE", "    NO_MASK_FILL: false\n", QK))

# ---- QK^T packed staging (transformation of the 780M gen_qkpk.py) ----
p = sub(q, """const uint FP16_PER_VEC4 = 4; // we read native tensors as f16vec4 (4 fp16)
""", """const uint F16_PER_UV4 = 8; // one shared uvec4 holds 8 fp16 (two native f16vec4)
""")
a0 = p.index("// fp16 shared tiles with skew padding."); a1 = p.index("shared float16_t Csh[WG_TILE_M * WG_TILE_N];")
p = p[:a0] + """// Packed staging: A = Q rows [s][d], B = K rows [c][d] (K^T comes from a
// ColumnMajor load), both d-contiguous with one uvec4 of skew padding per row.
// C = scaled result [s][c] scratch for the masked scalar store (fallback path).
const uint AB_STRIDE_UV4 = (WG_TILE_K + F16_PER_UV4) / F16_PER_UV4;

shared uvec4 Ash[WG_TILE_M * AB_STRIDE_UV4];
shared uvec4 Bsh[WG_TILE_N * AB_STRIDE_UV4];
""" + p[a1:]
p = sub(p, "    for (uint chunk = 0; chunk < uint(num_k_chunks_arg); ++chunk) {",
        "    // num_k_chunks_arg counts 32-wide chunks (head_dim / 32, from the table row).\n    const uint num_chunks = uint(num_k_chunks_arg) * 32u / WG_TILE_K;\n    const uint UV4_PER_CHUNK = WG_TILE_K / F16_PER_UV4;\n    for (uint chunk = 0; chunk < num_chunks; ++chunk) {")
s0 = p.index("        // --- Stage A = Q [s][d] into fp16 shared (contiguous d) ---"); s1 = p.index("        // coopmat-lds-fence (WRITE->READ): the Ash/Bsh staging stores above")
p = p[:s0] + """        // --- Stage A = Q rows, 8 fp16 per uvec4 store ---
        for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * UV4_PER_CHUNK;
             idx += WG_SIZE) {
            const uint ls = idx / UV4_PER_CHUNK;      // local s row
            const uint l8 = idx % UV4_PER_CHUNK;      // uvec4 within the chunk
            const uint src = (s_tile_base + ls) * q_row_stride + q_head_base +
                d4_chunk + l8 * 2u;
            const f16vec4 v0 = t_q[src];
            const f16vec4 v1 = t_q[src + 1u];
            Ash[ls * AB_STRIDE_UV4 + l8] = uvec4(
                packFloat2x16(v0.xy), packFloat2x16(v0.zw),
                packFloat2x16(v1.xy), packFloat2x16(v1.zw));
        }

        // --- Stage B = K rows [c][d] (no transpose; loaded ColumnMajor) ---
        for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_N * UV4_PER_CHUNK;
             idx += WG_SIZE) {
            const uint lc = idx / UV4_PER_CHUNK;      // local c row of K
            const uint l8 = idx % UV4_PER_CHUNK;
            const uint src = (c_tile_base + lc) * k_row_stride + k_head_base +
                d4_chunk + l8 * 2u;
            const f16vec4 v0 = t_k[src];
            const f16vec4 v1 = t_k[src + 1u];
            Bsh[lc * AB_STRIDE_UV4 + l8] = uvec4(
                packFloat2x16(v0.xy), packFloat2x16(v0.zw),
                packFloat2x16(v1.xy), packFloat2x16(v1.zw));
        }

""" + p[s1:]
p = sub(p, """                coopMatLoad(
                    matA[i], Ash,
                    row_a * A_ROW + k_start,
                    A_ROW,
                    gl_CooperativeMatrixLayoutRowMajor);""", """                coopMatLoad(
                    matA[i], Ash,
                    row_a * AB_STRIDE_UV4 + k_start / F16_PER_UV4,
                    AB_STRIDE_UV4,
                    gl_CooperativeMatrixLayoutRowMajor);""")
p = sub(p, """                coopMatLoad(
                    matB, Bsh,
                    k_start * B_ROW + col_b,
                    B_ROW,
                    gl_CooperativeMatrixLayoutRowMajor);""", """                coopMatLoad(
                    matB, Bsh,
                    col_b * AB_STRIDE_UV4 + k_start / F16_PER_UV4,
                    AB_STRIDE_UV4,
                    gl_CooperativeMatrixLayoutColumnMajor);""")
assert "A_ROW" not in p and "B_ROW" not in p and "FP16_PER_VEC4" not in p
PK = [V(128, 64, 32, 4, 2, True), V(128, 64, 64, 4, 2, True), V(128, 64, 32, 2, 4, True), V(64, 64, 32, 2, 2, True),
      # second batch (screen 2)
      V(64, 64, 32, 4, 2, True), V(64, 128, 32, 4, 2, True), V(128, 64, 32, 4, 4, True), V(64, 64, 32, 4, 4, True), V(64, 64, 32, 2, 1, True), V(32, 64, 32, 4, 2, True)]
for v in PK: assert 16 * (v["m"] + v["n"]) * ((v["k"] + 8) // 8) + 2 * v["m"] * v["n"] <= LDS_MAX, v["tok"]
F_PK = "sarc_sdpa_qk_coopmat_4070ti_pk"
write_new(g / f"sarc_dev/{F_PK}.glsl", hdr("QK^T with packed staging: uvec4 staging of Q and K rows, ColumnMajor B load,\n * WG_TILE_K 32 or 64; otherwise sarc_sdpa_qk_coopmat_4070ti.glsl.") + p)
write_new(g / f"sarc_dev/{F_PK}.yaml", yaml(F_PK, "QK^T with packed staging", "K_CACHE_STORAGE", "    NO_MASK_FILL: true\n", PK))

# ---- attn*V: release body, subgroup-32 tiles (single pass: WG_SIZE == 4 * M == K * N / 8) ----
a = (g / "sarc/sarc_sdpa_av_coopmat.glsl").read_text()
a = a[a.index("#version 450 core"):]
AV = [V(64, 64, 32, 4, 2), V(64, 64, 32, 2, 4)]
for v in AV: assert v["sx"] * v["sy"] * SG == 4 * v["m"] == 32 * v["n"] // 8, v["tok"]
F_AV = "sarc_sdpa_av_coopmat_4070ti"
write_new(g / f"sarc_dev/{F_AV}.glsl", hdr("attn*V: glsl/sarc/sarc_sdpa_av_coopmat.glsl, identical from #version on.") + a)
write_new(g / f"sarc_dev/{F_AV}.yaml", yaml(F_AV, "attn*V, subgroup-32 tiles", "V_CACHE_STORAGE", "", AV))

# ---- attn*V multi-pass staging (transformation of the 780M gen_avml.py) ----
ml = sub(a, """    const uint INVS_PER_ROW_A = WG_TILE_K / FP16_PER_VEC4;
    const uint a_col = gl_LocalInvocationID.x % INVS_PER_ROW_A;
    const uint a_row_offset = gl_LocalInvocationID.x / INVS_PER_ROW_A;

    const uint INVS_PER_ROW_B = WG_TILE_N / FP16_PER_VEC4;
    const uint b_col = gl_LocalInvocationID.x % INVS_PER_ROW_B;
    const uint b_row_offset = gl_LocalInvocationID.x / INVS_PER_ROW_B;
""", """    // Multi-pass staging (dev): A has WG_TILE_M * INVS_PER_ROW_A uvec4 slots and
    // B has WG_TILE_K * INVS_PER_ROW_B; each thread takes slots tid, tid + WG_SIZE, ...
    const uint INVS_PER_ROW_A = WG_TILE_K / FP16_PER_VEC4;
    const uint INVS_PER_ROW_B = WG_TILE_N / FP16_PER_VEC4;
""")
ml = sub(ml, """        // --- Load A (attn_weights) tile -> shared (single pass) ---
        {
            f16vec4 v0 = f16vec4(0);""", """        // --- Load A (attn_weights) tile -> shared ---
        for (uint a_idx = gl_LocalInvocationID.x; a_idx < WG_TILE_M * INVS_PER_ROW_A;
             a_idx += WG_SIZE) {
            const uint a_col = a_idx % INVS_PER_ROW_A;
            const uint a_row_offset = a_idx / INVS_PER_ROW_A;
            f16vec4 v0 = f16vec4(0);""")
ml = sub(ml, """        // --- Load B (V) tile -> shared (single pass), row-major [c, d] ---
        {
            f16vec4 v0 = f16vec4(0);""", """        // --- Load B (V) tile -> shared, row-major [c, d] ---
        for (uint b_idx = gl_LocalInvocationID.x; b_idx < WG_TILE_K * INVS_PER_ROW_B;
             b_idx += WG_SIZE) {
            const uint b_col = b_idx % INVS_PER_ROW_B;
            const uint b_row_offset = b_idx / INVS_PER_ROW_B;
            f16vec4 v0 = f16vec4(0);""")
ML = [V(64, 128, 32, 4, 2), V(128, 128, 32, 4, 2), V(128, 64, 32, 4, 2),   # 128-column tiles serve head_dim 128 only
      # second batch (screen 2)
      V(128, 64, 32, 4, 4), V(256, 64, 32, 4, 2), V(128, 64, 32, 2, 4), V(64, 128, 32, 4, 4), V(128, 128, 32, 4, 4), V(32, 64, 32, 4, 2), V(256, 64, 32, 4, 4)]
for v in ML: assert 16 * (v["m"] * 5 + 32 * ((v["n"] + 8) // 8)) <= LDS_MAX, v["tok"]
F_ML = "sarc_sdpa_av_coopmat_4070ti_ml"
write_new(g / f"sarc_dev/{F_ML}.glsl", hdr("attn*V with multi-pass staging, for tiles other than 64 x 64;\n * otherwise sarc_sdpa_av_coopmat_4070ti.glsl.") + ml)
write_new(g / f"sarc_dev/{F_ML}.yaml", yaml(F_ML, "attn*V with multi-pass staging", "V_CACHE_STORAGE", "", ML))

# ---- impl/sarc_dev/Overrides.cpp: marked blocks only ----
o = root / "impl/sarc_dev/Overrides.cpp"
FAM = [("kSdpaQk", F_QK, QK, "qk", ""), ("kSdpaQk", F_PK, PK, "qk", "pk_"), ("kSdpaAv", F_AV, AV, "av", ""), ("kSdpaAv", F_ML, ML, "av", "ml_")]
rows = "    // RTX 4070 Ti SUPER prefill refine: glsl/sarc_dev/sarc_sdpa_{qk,av}_coopmat_4070ti*.yaml.\n    // Selected only through ET_VK_SARC_DEV_PROFILE=4070ti-*.\n"
prefs = "// RTX 4070 Ti SUPER: single-kernel SDPA screening profiles and 4070ti-refine1.\n"
profs = ""
for op, fam, vs, kind, pre in FAM:
    for v in vs:
        tok = f"4070ti_{pre}{v['tok']}"; cid = f"k4070ti_{kind}_{pre}{v['tok']}"
        rows += f'    {{"", nullptr, Op::{op},\n     "{fam}_{v["tok"]}",\n     {{{v["m"]}, {v["n"]}, {v["k"]}, {v["sx"]}, {v["sy"]}, {SG}, 16, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n'
        prefs += f'const Preference {cid}[] = {{{{Op::{op}, "{tok}", nullptr}}}};\n'
        profs += f'    {{"4070ti-{kind}-{pre}{v["tok"]}", {cid}, 1}},\n'
prefs += """// Candidate 1 (SDPA prefill kernels for this device), the best tile per head_dim of screen 2
// (results/4070ti/screens/sdpa-screen2.csv), accumulation unchanged (fp32):
//   QK^T    head_dim 64: direct feed t64x64 (one subgroup per workgroup); 128: packed staging t64x128
//   attn*V  head_dim 64: multi-pass staging t32x64; 128: t64x128 (does not fit head_dim 64)
bool head_dim_64_4070ti(const ShapeInfo& s) {
  return (s.op == Op::kSdpaQk ? s.K : s.N) == 64;
}
const Preference k4070tiRefine1[] = {
    {Op::kSdpaQk, "4070ti_df_t64x64k32g11s32nf", head_dim_64_4070ti},
    {Op::kSdpaQk, "4070ti_pk_t64x128k32g42s32nf", nullptr},
    {Op::kSdpaAv, "4070ti_ml_t32x64k32g42s32", head_dim_64_4070ti},
    {Op::kSdpaAv, "4070ti_ml_t64x128k32g42s32", nullptr},
};
"""
profs += '    {"4070ti-refine1", k4070tiRefine1, sizeof(k4070tiRefine1) / sizeof(Preference)},\n'
put_block(o, "};\n\nstd::string& requested_variant() {", "sdpa-rows", rows, "    ")
put_block(o, "struct Profile {\n", "sdpa-preferences", prefs)
put_block(o, "};\nconst Profile* requested_profile() {", "sdpa-profiles", profs, "    ")
print(f"4070ti sdpa families generated: {sum(len(f[2]) for f in FAM)} variants")
