#!/usr/bin/env python3
"""8da4w zpgtr with half-texel weight staging for the RTX 4070 Ti SUPER (dev-zone twin of the release body).

usage: gen_4070ti_bh.py <executorch tree>

  glsl/sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_4070ti_bh{.glsl,.yaml,_body.glslh}
  impl/sarc_dev/Overrides.cpp   `// >>> 4070ti bh-dq8ca-rows`

Why (phase timing, results/4070ti/phases): on the shipped zpgtr kernel a wave spends 34 to 43 % of its time in
the fetch phase, more than in the MMA. With B_PAIR every staging slot fetches a whole packed-weight texel (four
32-bit words, 32 nibbles) and keeps one word, so each texel is fetched four times per chunk, by four threads.
Here a slot keeps two words of its texel (components 0-1 or 2-3) and writes four shared-memory words instead of
two: half as many weight fetches for the same shared-memory contents. The values, the shared-memory layout and
the MMA order are unchanged (the body is the release body with the slot map and the two store sites rewritten;
the release file is read, never written), so the output is meant to be bit-identical; the gate checks it.
Token prefix `bh_`; MMA 16x16x32, A_RAW and B_PAIR as shipped.
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ops = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
root = ops / "glsl"
LDS_MAX, WG_MAX, SG = 49152, 1024, 32
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)
F = "sarc_linear_dq8ca_coopmat_zpgtr_4070ti_bh"
b = (root / "sarc/sarc_linear_dq8ca_coopmat_zpgtr_body.glslh").read_text()
b = sub(b, "SARC_LINEAR_DQ8CA_COOPMAT_ZPGTR_BODY_GLSLH", "SARC_LINEAR_DQ8CA_COOPMAT_ZPGTR_4070TI_BH_BODY_GLSLH", b.count("SARC_LINEAR_DQ8CA_COOPMAT_ZPGTR_BODY_GLSLH"))
# one slot = (k4, n8, half of the texel): half as many slots, each producing four shared-memory words
b = sub(b, "  const uint B_SLOTS_PER_THREAD = B_TOTAL_SLOTS / (2u * WG_SIZE);",
        "  // 4070ti bh: a slot is a (k4, n8, texel half) triple producing four LDS uints.\n"
        "  const uint B_SLOTS_PER_THREAD = B_TOTAL_SLOTS / (4u * WG_SIZE);\n"
        "  const int kBhSlotsDivide[(B_TOTAL_SLOTS % (4u * WG_SIZE) == 0u && B_TOTAL_SLOTS >= 4u * WG_SIZE) ? 1 : -1] = int[](0);")
b = sub(b, """    const uint comp        = (q / K4_PER_SLAB) & 3u;
    const uint slab_idx    = (q / (K4_PER_SLAB * 4u)) % NUM_K_SLABS;
    const uint n8_in_tile  = q / (K4_PER_SLAB * 4u * NUM_K_SLABS);""",
        """    // 4070ti bh: comp is the first of the slot's two texel components.
    const uint comp        = ((q / K4_PER_SLAB) & 1u) * 2u;
    const uint slab_idx    = (q / (K4_PER_SLAB * 2u)) % NUM_K_SLABS;
    const uint n8_in_tile  = q / (K4_PER_SLAB * 2u * NUM_K_SLABS);""")
b = sub(b, """      Bsh_int8[b_lds_off[si]] = widen_nibbles(w, 0u);
      Bsh_int8[b_lds_off[si] + 4u * B_STRIDE_U32] = widen_nibbles(w, 1u);
""", """      Bsh_int8[b_lds_off[si]] = widen_nibbles(w, 0u);
      Bsh_int8[b_lds_off[si] + 4u * B_STRIDE_U32] = widen_nibbles(w, 1u);
      const uint w2 = uint(temp_B[si][b_comp[si] + 1u]);
      Bsh_int8[b_lds_off[si] + B_STRIDE_U32] = widen_nibbles(w2, 0u);
      Bsh_int8[b_lds_off[si] + 5u * B_STRIDE_U32] = widen_nibbles(w2, 1u);
""")
b = sub(b, """          Bsh_int8[nxt_b + b_lds_off[si]] = widen_nibbles(w, 0u);
          Bsh_int8[nxt_b + b_lds_off[si] + 4u * B_STRIDE_U32] = widen_nibbles(w, 1u);
""", """          Bsh_int8[nxt_b + b_lds_off[si]] = widen_nibbles(w, 0u);
          Bsh_int8[nxt_b + b_lds_off[si] + 4u * B_STRIDE_U32] = widen_nibbles(w, 1u);
          const uint w2 = uint(temp_B[si][b_comp[si] + 1u]);
          Bsh_int8[nxt_b + b_lds_off[si] + B_STRIDE_U32] = widen_nibbles(w2, 0u);
          Bsh_int8[nxt_b + b_lds_off[si] + 5u * B_STRIDE_U32] = widen_nibbles(w2, 1u);
""")
b = "// GENERATED by gen_4070ti_bh.py from sarc_linear_dq8ca_coopmat_zpgtr_body.glslh (half-texel weight staging;\n// valid with B_PAIR and without B_SEL_EARLY_N only).\n#if !defined(B_PAIR) || defined(B_SEL_EARLY_N)\n#error \"the 4070ti bh body needs B_PAIR and no B_SEL_EARLY_N\"\n#endif\n" + b
write_new(root / f"sarc_dev/{F}_body.glslh", b)
w = (root / "sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_sweep.glsl").read_text()
w = sub(w[w.index("#version 450 core"):], '#include "sarc_linear_dq8ca_coopmat_zpgtr_body.glslh"', f'#include "{F}_body.glslh"')
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_bh.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine): zpgtr with half-texel weight staging.
 */

"""
write_new(root / f"sarc_dev/{F}.glsl", HDR + w)
def Z(m, n, k, sx, sy):
    wg = sx * sy * SG
    assert wg <= WG_MAX and 2048 % m == 0 and 128 % k == 0 and k % 32 == 0 and m % (16 * sy) == 0 and n % (16 * sx) == 0
    assert (m * k // 16) % wg == 0 and m * k // 16 >= wg and (k * n // 16) % wg == 0 and k * n // 16 >= wg, (m, n, k, sx, sy)
    assert 2 * m * k + 2 * k * n + 8 * m + 12 * n <= LDS_MAX and sy * 16 * n <= m * k, (m, n, k, sx, sy)
    return dict(tok=f"bh_t{m}x{n}k{k}g{sx}{sy}s{SG}mk32ra", m=m, n=n, k=k, sx=sx, sy=sy)
VS = [Z(128, 128, 64, 4, 4), Z(128, 128, 64, 4, 2), Z(128, 128, 64, 2, 4), Z(256, 128, 32, 4, 2)]
ry = (root / "sarc/sarc_linear_dq8ca_coopmat_zpgtr.yaml").read_text()
y = "# SARC development zone, RTX 4070 Ti SUPER: zpgtr with half-texel weight staging (generated by gen_4070ti_bh.py). Not shipped.\n\n" + f"{F}:\n" + ry[ry.index("  parameter_names_with_default_values:"):ry.index("  shader_variants:")] + "  shader_variants:\n"
rows = "    // RTX 4070 Ti SUPER zpgtr with half-texel weight staging (glsl/sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_4070ti_bh.yaml).\n"
for v in VS:
    geo = f"      WG_TILE_M: {v['m']}\n      WG_TILE_N: {v['n']}\n      WG_TILE_K: {v['k']}\n      SG_GRID_X: {v['sx']}\n      SG_GRID_Y: {v['sy']}\n      SUBGROUP_SIZE: {SG}\n      MMA_K: 32\n      A_RAW: true\n      B_PAIR: true\n"
    name = F[:-3] + "_" + v["tok"]
    y += f"    - NAME: {name}_buffer_texture2d_half\n" + geo + f"    - NAME: {name}_texture3d_texture2d_half\n      IO_STORAGE: texture3d\n      CSH_IN_ASH: true\n" + geo
    rows += f'    {{"", nullptr, Op::kDq8caLinear,\n     "{name}", {{{v["m"]}, {v["n"]}, {v["k"]}, {v["sx"]}, {v["sy"]}, {SG}, 16, true}},\n     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified,\n     /*rowmajor_a=*/true}},\n'
write_new(root / f"sarc_dev/{F}.yaml", y)
put_block(ops / "impl/sarc_dev/Overrides.cpp", "    // >>> 4070ti prof-dq8ca-rows\n", "bh-dq8ca-rows", rows, "    ")
print(f"4070ti zpgtr bh: {len(VS)} variants")
