#!/usr/bin/env python3
"""A dev-zone variant of the SARC LLM softmax for the RTX 4070 Ti SUPER that does not zero the whole masked tail.

usage: gen_4070ti_softmax.py <executorch tree>

  glsl/sarc_dev/sarc_sdpa_attn_weights_softmax_4070ti.{glsl,yaml}
      one variant, `sarc_sdpa_attn_weights_softmax_buffer_half_4070ti_nz`

Why: with the SDPA kernels of candidate 1 the release softmax is half of the attention time and runs at the DRAM
write roof; half of what it writes is zeros above the diagonal (row s: columns s + input_pos + 1 .. context_len).
The SARC attn*V kernels read row s only up to the end of their own row tile, so the zeros beyond that are never
read. This variant zeroes row s up to (s / 256) * 256 + 256 + align_up(input_pos, 32), which covers every attn*V
tile whose M divides 256 and whose K step is 32 (all rows and candidates of this device), and only when the SARC
attn*V kernel is the one that runs: the condition below is the fit check of this device's table row (S a multiple
of 64, head_dim a multiple of 64, context a multiple of 32, not single-token). Otherwise it behaves exactly as
the release shader. The body is the release shader with that one loop bound changed; the release file is read,
never written.

NOT REACHABLE FROM THE DEV ZONE: the softmax name is fixed in impl/sarc/SdpaCoopmat.cpp. It is measured through
tools/local-hook-nvidia-sdpa-softmax.patch (not committed), which appends "_" + $ET_VK_SARC_SOFTMAX_VARIANT to
the name. The hook that would be needed is written down in proposal.md.
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new
g = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops/glsl"
def sub(text, old, new):
    assert text.count(old) == 1, f"anchor occurs {text.count(old)} times: {old[:70]!r}"
    return text.replace(old, new)
s = (g / "sarc/sarc_sdpa_attn_weights_softmax.glsl").read_text()
s = s[s.index("#version 450 core"):]
s = sub(s, """  for (int c4 = reduce_texel_len + worker_id; c4 < context_texel_len;
       c4 += NUM_WORKERS_PER_WG) {""", """  // 4070ti nz: when the SARC attn*V kernel runs (the fit check of this device's
  // table row), it reads row s only up to the end of its row tile, so only that
  // much of the tail is zeroed; otherwise the whole tail, as in the release shader.
#ifdef HAS_INPUT_POS
  const bool av_truncates = S > 1 && (S & 63) == 0 && (q_sizes.x & 63) == 0 &&
      (context_len & 31) == 0;
  const int zero_len = av_truncates
      ? min(context_len, (s / 256) * 256 + 256 + ((input_pos + 31) / 32) * 32)
      : context_len;
#else
  const int zero_len = context_len;
#endif
  const int zero_texel_len = div_up_4(zero_len);
  for (int c4 = reduce_texel_len + worker_id; c4 < zero_texel_len;
       c4 += NUM_WORKERS_PER_WG) {""")
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_softmax.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine): glsl/sarc/sarc_sdpa_attn_weights_softmax.glsl
 * with the zero tail limited to what the SARC attn*V kernels read. Valid only with those kernels.
 */

"""
F = "sarc_sdpa_attn_weights_softmax_4070ti"
write_new(g / f"sarc_dev/{F}.glsl", HDR + s)
write_new(g / f"sarc_dev/{F}.yaml", f"""# SARC development zone, RTX 4070 Ti SUPER: LLM softmax without the full zero tail (generated by gen_4070ti_softmax.py). Not shipped.

{F}:
  parameter_names_with_default_values:
    IN_DTYPE: half
    OUT_DTYPE: half
    STORAGE: buffer
    MODE: llm
  shader_variants:
    - NAME: sarc_sdpa_attn_weights_softmax_buffer_half_4070ti_nz
""")
print("4070ti softmax nz generated")
