#!/usr/bin/env python3
"""Linear sweep tiles for the RTX 4070 Ti SUPER as dev-zone families of their own (the release bodies, unmodified).

usage: gen_4070ti_lin.py <executorch tree>

  glsl/sarc_dev/sarc_linear_q4gsw_coopmat_4070ti.{glsl,yaml}         4w, `ga` (ACC_GROUP_FP32) tiles
  glsl/sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_4070ti.{glsl,yaml}   8da4w zpgtr tiles (MMA 16x16x32, A_RAW, B_PAIR)
  impl/sarc_dev/Overrides.cpp                                        `// >>> 4070ti lin-*` blocks (candidate rows)

The wrappers are the sweep wrappers from `#version` on and include the release bodies, which are not written.
Variants are selected by tile token with ET_VK_SARC_Q4GSW_VARIANT / ET_VK_SARC_DQ8CA_VARIANT (tools/screen.sh) and,
once chosen, by a 4070ti-refineN profile. texture3d only for 4w (the model path); zpgtr gets both storages, as its
shipped row has them.

Static pruning (asserted here, before anything is compiled):
  subgroup 32, at most 1024 invocations, shared memory at most 49152 bytes (vulkaninfo, driver 615.71.09);
  M | 2048, N | 512 (every projection width of the three models is a multiple of 512 except 3B's 3072 and 8B's
  14336, both multiples of 256 and 128... so N in {128, 256}), k | 128 (the quantization group);
  4w staging maps: M * k / 8 and k * N / 8 are positive multiples of the workgroup size;
  zpgtr staging maps: M * k / 16 and k * N / 8 are positive multiples of the workgroup size, and the texture3d
  drain band fits in Ash (SG_GRID_Y * 16 * N <= M * k).
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from devzone import write_new, put_block
ops = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
root = ops / "glsl"
LDS_MAX, WG_MAX, SG = 49152, 1024, 32
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_lin.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine): sweep tiles of %s for this device.
 * Identical to the sweep wrapper from #version on; the body is the release body.
 */

"""
def wrapper(sweep):
    w = (root / f"sarc_dev/{sweep}.glsl").read_text()
    return w[w.index("#version 450 core"):]
def defaults(release_yaml):
    y = (root / f"sarc/{release_yaml}").read_text()
    return y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]

# ---------------- 4w: ACC_GROUP_FP32 tiles ----------------
def Q(m, n, k, sx, sy, c=False, bt=False):
    wg = sx * sy * SG
    assert wg <= WG_MAX and 2048 % m == 0 and 128 % k == 0 and m % (16 * sy) == 0 and n % (16 * sx) == 0
    assert (m * k // 8) % wg == 0 and m * k // 8 >= wg and (k * n // 8) % wg == 0 and k * n // 8 >= wg, (m, n, k, sx, sy)
    lds = 2 * 2 * (m * (k + 8) + k * (n + 8)) + (0 if c else sy * 16 * n * 2)
    assert lds <= LDS_MAX, (m, n, k, sx, sy, lds)
    return dict(tok=f"t{m}x{n}k{k}g{sx}{sy}s{SG}ga" + ("c" if c else "") + ("bt" if bt else ""), m=m, n=n, k=k, sx=sx, sy=sy, c=c, bt=bt, lds=lds)
Q4 = [Q(256, 128, 16, 4, 2, c=True), Q(256, 128, 16, 2, 4, c=True), Q(256, 256, 16, 4, 4, c=True),
      Q(128, 256, 16, 4, 2), Q(128, 256, 16, 4, 2, c=True), Q(128, 128, 32, 4, 2), Q(128, 128, 32, 4, 2, c=True),
      Q(128, 128, 32, 4, 4, c=True), Q(128, 128, 32, 2, 4, c=True), Q(128, 128, 16, 4, 2), Q(128, 128, 16, 4, 2, c=True),
      Q(256, 128, 16, 4, 2, bt=True), Q(256, 128, 16, 4, 2, c=True, bt=True), Q(128, 128, 32, 4, 2, c=True, bt=True)]
F4 = "sarc_linear_q4gsw_coopmat_4070ti"
write_new(root / f"sarc_dev/{F4}.glsl", HDR % "sarc_linear_q4gsw_coopmat" + wrapper("sarc_linear_q4gsw_coopmat_sweep"))
y = f"# SARC development zone, RTX 4070 Ti SUPER: 4w `ga` sweep tiles (generated by gen_4070ti_lin.py). Not shipped.\n\n{F4}:\n" + defaults("sarc_linear_q4gsw_coopmat.yaml") + "  shader_variants:\n"
rows4 = "    // RTX 4070 Ti SUPER 4w sweep tiles (glsl/sarc_dev/sarc_linear_q4gsw_coopmat_4070ti.yaml), texture3d.\n"
for v in Q4:
    y += (f"    - NAME: {F4}_{v['tok']}_texture3d_texture2d_half   # shared memory {v['lds']} bytes\n      IO_STORAGE: texture3d\n      WEIGHT_STORAGE: texture2d\n"
          f"      WG_TILE_M: {v['m']}\n      WG_TILE_N: {v['n']}\n      WG_TILE_K: {v['k']}\n      SG_GRID_X: {v['sx']}\n      SG_GRID_Y: {v['sy']}\n      SUBGROUP_SIZE: {SG}\n      ACC_GROUP_FP32: true\n"
          + ("      CSH_IN_ASH: true\n" if v["c"] else "") + ("      B_COLMAJOR: true\n" if v["bt"] else ""))
    rows4 += f'    {{"", nullptr, Op::kQ4gswLinear,\n     "{F4}_{v["tok"]}", {{{v["m"]}, {v["n"]}, {v["k"]}, {v["sx"]}, {v["sy"]}, {SG}, 16, {"true" if v["c"] else "false"}}},\n     kTex3dTex2d, nullptr, Status::kUnverified}},\n'
write_new(root / f"sarc_dev/{F4}.yaml", y)

# ---------------- 8da4w: zpgtr tiles (MMA_K 32, A_RAW + B_PAIR, as shipped) ----------------
def Z(m, n, k, sx, sy):
    wg = sx * sy * SG
    assert wg <= WG_MAX and 2048 % m == 0 and 128 % k == 0 and k % 32 == 0 and m % (16 * sy) == 0 and n % (16 * sx) == 0
    assert (m * k // 16) % wg == 0 and m * k // 16 >= wg and (k * n // 8) % wg == 0 and k * n // 8 >= wg, (m, n, k, sx, sy)
    # Ash and Bsh int8 (two slices each), per-row and per-column scale / zero-point / correction arrays,
    # and for buffer IO nothing more; texture3d drains through Ash (CSH_IN_ASH).
    lds = 2 * m * k + 2 * k * n + 8 * m + 12 * n
    assert sy * 16 * n <= m * k, (m, n, k, sx, sy)   # the texture3d drain band must fit in Ash (kCshFitsInAsh)
    assert lds <= LDS_MAX, (m, n, k, sx, sy, lds)
    return dict(tok=f"t{m}x{n}k{k}g{sx}{sy}s{SG}mk32ra", m=m, n=n, k=k, sx=sx, sy=sy, lds=lds)
Z8 = [Z(128, 128, 64, 4, 2), Z(128, 128, 64, 2, 4), Z(256, 128, 32, 4, 4), Z(256, 128, 32, 4, 2), Z(128, 256, 32, 8, 1),
      Z(128, 128, 32, 4, 2), Z(128, 64, 64, 4, 4), Z(128, 64, 64, 4, 2), Z(64, 128, 64, 4, 2), Z(256, 64, 64, 4, 4),
      Z(256, 64, 64, 4, 2), Z(256, 128, 32, 2, 4), Z(128, 128, 64, 2, 2)]
F8 = "sarc_linear_dq8ca_coopmat_zpgtr_4070ti"
write_new(root / f"sarc_dev/{F8}.glsl", HDR % "sarc_linear_dq8ca_coopmat_zpgtr" + wrapper("sarc_linear_dq8ca_coopmat_zpgtr_sweep"))
y = f"# SARC development zone, RTX 4070 Ti SUPER: 8da4w zpgtr sweep tiles (generated by gen_4070ti_lin.py). Not shipped.\n\n{F8}:\n" + defaults("sarc_linear_dq8ca_coopmat_zpgtr.yaml") + "  shader_variants:\n"
rows8 = "    // RTX 4070 Ti SUPER 8da4w zpgtr sweep tiles (glsl/sarc_dev/sarc_linear_dq8ca_coopmat_zpgtr_4070ti.yaml).\n"
for v in Z8:
    geo = f"      WG_TILE_M: {v['m']}\n      WG_TILE_N: {v['n']}\n      WG_TILE_K: {v['k']}\n      SG_GRID_X: {v['sx']}\n      SG_GRID_Y: {v['sy']}\n      SUBGROUP_SIZE: {SG}\n      MMA_K: 32\n      A_RAW: true\n      B_PAIR: true\n"
    y += f"    - NAME: {F8}_{v['tok']}_buffer_texture2d_half   # shared memory {v['lds']} bytes\n" + geo
    y += f"    - NAME: {F8}_{v['tok']}_texture3d_texture2d_half\n      IO_STORAGE: texture3d\n      CSH_IN_ASH: true\n" + geo
    rows8 += f'    {{"", nullptr, Op::kDq8caLinear,\n     "{F8}_{v["tok"]}", {{{v["m"]}, {v["n"]}, {v["k"]}, {v["sx"]}, {v["sy"]}, {SG}, 16, true}},\n     kTex3dTex2d | kBufTex2d, nullptr, Status::kUnverified,\n     /*rowmajor_a=*/true}},\n'
write_new(root / f"sarc_dev/{F8}.yaml", y)

o = ops / "impl/sarc_dev/Overrides.cpp"
put_block(o, "    // >>> 4070ti prof-q4gsw-rows\n", "lin-q4gsw-rows", rows4, "    ")
put_block(o, "    // >>> 4070ti prof-dq8ca-rows\n", "lin-dq8ca-rows", rows8, "    ")
print(f"4070ti linear sweep tiles: {len(Q4)} 4w, {len(Z8)} zpgtr")
