#!/usr/bin/env python3
"""Candidate 6 (B, SDPA attn*V): multi-pass staging so the tile can be wider than 64 columns.

usage: gen_avml.py <executorch tree>      (run gen_sdpa.py first)

The release attn*V kernel stages A (the softmax output) and B (V) in a single pass, which pins the tile to
WG_SIZE == 4 * WG_TILE_M == WG_TILE_K * WG_TILE_N / 8, i.e. 64 x 64 for 256 threads. For head_dim 128 (3B, 8B) the
output is two 64-column tiles per (head, row tile), so every 64 x 32 block of the softmax output is read from
memory twice, once per column tile; that read is the kernel's memory traffic (the matrix is 100-270 MB per layer).
Here the two staging blocks loop over passes (compile-time trip counts), so a 64 x 128 or 128 x 128 tile stages
each softmax block once. Arithmetic and the causal chunk truncation are unchanged. Head_dim 64 (1B) does not fit
a 128-column tile and keeps its 64 x 64 kernel (the profile lists both)."""
import pathlib, sys
root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
g = root / "glsl"
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)
a = (g / "sarc_dev/sarc_sdpa_av_coopmat_sweep.glsl").read_text()
a = a[a.index("#version 450 core"):]
a = sub(a, """    const uint INVS_PER_ROW_A = WG_TILE_K / FP16_PER_VEC4;
    const uint a_col = gl_LocalInvocationID.x % INVS_PER_ROW_A;
    const uint a_row_offset = gl_LocalInvocationID.x / INVS_PER_ROW_A;

    const uint INVS_PER_ROW_B = WG_TILE_N / FP16_PER_VEC4;
    const uint b_col = gl_LocalInvocationID.x % INVS_PER_ROW_B;
    const uint b_row_offset = gl_LocalInvocationID.x / INVS_PER_ROW_B;
""", """    // Multi-pass staging (dev): A has WG_TILE_M * INVS_PER_ROW_A uvec4 slots and
    // B has WG_TILE_K * INVS_PER_ROW_B; each thread takes slots tid, tid + WG_SIZE, ...
    const uint INVS_PER_ROW_A = WG_TILE_K / FP16_PER_VEC4;
    const uint INVS_PER_ROW_B = WG_TILE_N / FP16_PER_VEC4;
""")
a = sub(a, """        // --- Load A (attn_weights) tile -> shared (single pass) ---
        {
            f16vec4 v0 = f16vec4(0);""", """        // --- Load A (attn_weights) tile -> shared ---
        for (uint a_idx = gl_LocalInvocationID.x; a_idx < WG_TILE_M * INVS_PER_ROW_A;
             a_idx += WG_SIZE) {
            const uint a_col = a_idx % INVS_PER_ROW_A;
            const uint a_row_offset = a_idx / INVS_PER_ROW_A;
            f16vec4 v0 = f16vec4(0);""")
a = sub(a, """        // --- Load B (V) tile -> shared (single pass), row-major [c, d] ---
        {
            f16vec4 v0 = f16vec4(0);""", """        // --- Load B (V) tile -> shared, row-major [c, d] ---
        for (uint b_idx = gl_LocalInvocationID.x; b_idx < WG_TILE_K * INVS_PER_ROW_B;
             b_idx += WG_SIZE) {
            const uint b_col = b_idx % INVS_PER_ROW_B;
            const uint b_row_offset = b_idx / INVS_PER_ROW_B;
            f16vec4 v0 = f16vec4(0);""")
(g / "sarc_dev/sarc_sdpa_av_coopmat_ml.glsl").write_text("""/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone: attn*V with multi-pass staging, for tiles other than 64 x 64 (generated by
 * gen_avml.py from glsl/sarc/sarc_sdpa_av_coopmat.glsl; openspec/changes/sarc-1.5-780m-prefill-refine).
 */

""" + a)
# (token, M, N, sgx, sgy, subgroup); K stays 32 (the spec constants come from the table row)
V = [("t64x128k32g42s32", 64, 128, 4, 2, 32), ("t64x128k32g22s64", 64, 128, 2, 2, 64),
     ("t128x128k32g42s32", 128, 128, 4, 2, 32), ("t128x64k32g42s32", 128, 64, 4, 2, 32)]
y = "# SARC development zone: attn*V with multi-pass staging (generated by gen_avml.py). Not shipped.\n\nsarc_sdpa_av_coopmat_ml:\n"
y += "  parameter_names_with_default_values:\n    DTYPE: half\n    PRECISION: highp\n    IO_STORAGE: buffer\n    V_CACHE_STORAGE: buffer\n    MMA_M: 16\n    MMA_N: 16\n    MMA_K: 16\n"
y += "    WG_TILE_M: 64\n    WG_TILE_N: 128\n    WG_TILE_K: 32\n    SG_GRID_X: 4\n    SG_GRID_Y: 2\n    SUBGROUP_SIZE: 32\n"
y += "  generate_variant_forall:\n    combination:\n      parameter_names: [IO_STORAGE, V_CACHE_STORAGE]\n      combos:\n        - parameter_values: [buffer, buffer]\n    DTYPE:\n      - VALUE: half\n  shader_variants:\n"
for tok, m, n, sx, sy, sg in V:
    assert 16 * (m * 5 + 32 * ((n + 8) // 8)) <= 60000, tok
    y += f"    - NAME: sarc_sdpa_av_coopmat_ml_{tok}\n      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n      WG_TILE_K: 32\n      SG_GRID_X: {sx}\n      SG_GRID_Y: {sy}\n      SUBGROUP_SIZE: {sg}\n"
(g / "sarc_dev/sarc_sdpa_av_coopmat_ml.yaml").write_text(y)
o = root / "impl/sarc_dev/Overrides.cpp"; t = o.read_text()
if "sarc_sdpa_av_coopmat_ml" not in t:
    x = "};\n\nstd::string& requested_variant() {"
    rows = "    // 780M prefill refine 2026-10-03, candidate 6: attn*V with multi-pass staging\n    // (glsl/sarc_dev/sarc_sdpa_av_coopmat_ml.yaml).\n"
    for tok, m, n, sx, sy, sg in V:
        rows += f'    {{"", nullptr, Op::kSdpaAv,\n     "sarc_sdpa_av_coopmat_ml_{tok}",\n     {{{m}, {n}, 32, {sx}, {sy}, {sg}, 16, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n'
    t = sub(t, x, rows + x)
    x = "struct Profile {\n"
    prefs = "".join(f'const Preference kAvMl_{tok}[] = {{{{Op::kSdpaAv, "ml_{tok}", nullptr}}}};\n' for tok, *_ in V)
    prefs += """// refine3 with the packed-staging QK^T kernel.
const Preference k780mRefine5[] = {
    {Op::kDq8caLinear, "bt_t128x64k32g22s32", nullptr},
    {Op::kQ4gswLinear, "t128x256k32g42s32f32c", n_at_least_1024},
    {Op::kSdpaQk, "pk_t128x64k32g42s32nf", nullptr},
    {Op::kSdpaAv, "t64x64k32g42s32", nullptr},
};
"""
    t = sub(t, x, prefs + x)
    x = '    {"780m-refine1-dq",'
    t = sub(t, x, "".join(f'    {{"avml-{tok}", kAvMl_{tok}, 1}},\n' for tok, *_ in V) + '    {"780m-refine5", k780mRefine5, sizeof(k780mRefine5) / sizeof(Preference)},\n' + x)
    o.write_text(t)
print("av ml family generated")
