#!/usr/bin/env python3
"""Candidate 4 (A, 4w): texel-wise weight staging for the 4w kernel, as a new dev-zone family.

usage: gen_bx.py <executorch tree>

In the release body a thread's B_PASSES weight rows come from B_PASSES different packed-weight texels
(k_row = p * B_ROWS_PER_PASS + b_row_offset), so every texel (4 K rows x 8 N) is fetched 4 times per chunk and
the nibble shift is a per-thread variable. Here a thread's rows are the rows of ONE texel
(k_row = k4 * 4 + sub * B_PASSES + p): one fetch per thread per chunk and, for B_PASSES = 4, constant shifts.
Same LDS layout and the same dequantized values, so the output is bit-identical to the release kernel.
Needs B_PASSES in {1, 2, 4}. Writes glsl/sarc_dev/sarc_dev_linear_q4gsw_coopmat_bx{.glsl,.yaml,_body.glslh},
candidate rows and profile 780m-refine4 (impl/sarc_dev/Overrides.cpp)."""
import pathlib, sys
root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
g = root / "glsl"
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)
b = (g / "sarc/sarc_linear_q4gsw_coopmat_body.glslh").read_text()
b = b.replace("SARC_LINEAR_Q4GSW_COOPMAT_BODY_GLSLH", "SARC_DEV_LINEAR_Q4GSW_COOPMAT_BX_BODY_GLSLH")
b = b.replace("#ifndef SARC_DEV_LINEAR_Q4GSW_COOPMAT_BX_BODY_GLSLH", "// GENERATED by gen_bx.py from the release 4w body (texel-wise B staging).\n#ifndef SARC_DEV_LINEAR_Q4GSW_COOPMAT_BX_BODY_GLSLH", 1)
b = sub(b, "const uint B_PASSES = WG_TILE_K / B_ROWS_PER_PASS;\n", """const uint B_PASSES = WG_TILE_K / B_ROWS_PER_PASS;
// Texel-wise B staging (dev): one packed-weight texel (4 K rows x 8 N) feeds all
// B_PASSES rows of a thread; B_RP threads share a texel when B_PASSES < 4.
// Row of pass p within the chunk, and its first nibble index in the texel.
const uint B_RP = 4u / B_PASSES;
#define B_TROW(p) ((b_row_offset / B_RP) * 4u + (b_row_offset % B_RP) * B_PASSES + (p))
#define B_TCOL(p) (2u * ((b_row_offset % B_RP) * B_PASSES + (p)))
""")
b = sub(b, "      const uint k_row = p * B_ROWS_PER_PASS + b_row_offset;\n",
        "      if (p > 0u) {\n        temp_B[p] = temp_B[0];\n        continue;\n      }\n      const uint k_row = B_TROW(0u);\n")
b = sub(b, "        const uint k_row = chunkK_nxt + p * B_ROWS_PER_PASS + b_row_offset;\n",
        "        if (p > 0u) {\n          temp_B[p] = temp_B[0];\n          continue;\n        }\n        const uint k_row = chunkK_nxt + B_TROW(0u);\n")
b = sub(b, "B_SH_IDX(p * B_ROWS_PER_PASS + b_row_offset, b_col)", "B_SH_IDX(B_TROW(p), b_col)", 3)
b = sub(b, "dequant_block(temp_B[p], col_lo, col_hi, sc0, sc1)", "dequant_block(temp_B[p], B_TCOL(p), B_TCOL(p) + 1u, sc0, sc1)", 3)
(g / "sarc_dev/sarc_dev_linear_q4gsw_coopmat_bx_body.glslh").write_text(b)
w = (g / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.glsl").read_text()
w = w[w.index("#version 450 core"):]
w = sub(w, '#include "sarc_linear_q4gsw_coopmat_body.glslh"', '#include "sarc_dev_linear_q4gsw_coopmat_bx_body.glslh"')
(g / "sarc_dev/sarc_dev_linear_q4gsw_coopmat_bx.glsl").write_text("""/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone: 4w kernel with texel-wise weight staging (generated by gen_bx.py;
 * openspec/changes/sarc-1.5-780m-prefill-refine). The wrapper is the q4gsw sweep wrapper with a different
 * body. Only for variants without B_COLMAJOR.
 */

""" + w)
y = (g / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.yaml").read_text()
defaults = y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
T = [("t128x256k32g42s32f32c", 128, 256, 32, 4, 2), ("t128x128k32g42s32f32c", 128, 128, 32, 4, 2)]
out = "# SARC development zone: 4w with texel-wise weight staging (generated by gen_bx.py). Not shipped.\n\nsarc_dev_linear_q4gsw_coopmat_bx:\n" + defaults + "  shader_variants:\n"
for tok, m, n, k, sx, sy in T:
    wg = sx * sy * 32; bp = k // (wg // (n // 8))
    assert m % (wg // (k // 8)) == 0 and k % (wg // (n // 8)) == 0 and bp in (1, 2, 4), tok
    assert 2 * m * ((k + 8) // 8) >= sy * 16 * (n // 8) and 4 * (m * (k + 8) + k * (n + 8)) <= 60000, tok
    out += f"    - NAME: sarc_dev_linear_q4gsw_coopmat_bx_{tok}_texture3d_texture2d_half\n      IO_STORAGE: texture3d\n      WEIGHT_STORAGE: texture2d\n"
    out += f"      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n      WG_TILE_K: {k}\n      SG_GRID_X: {sx}\n      SG_GRID_Y: {sy}\n      SUBGROUP_SIZE: 32\n      ACC_FP32: true\n      CSH_IN_ASH: true\n"
(g / "sarc_dev/sarc_dev_linear_q4gsw_coopmat_bx.yaml").write_text(out)
o = root / "impl/sarc_dev/Overrides.cpp"; t = o.read_text()
if "sarc_dev_linear_q4gsw_coopmat_bx" not in t:
    a = "    // 780M phase timing, MEASUREMENT ONLY (glsl/sarc_dev/sarc_dev_prof_q4gsw.yaml):"
    rows = "    // 780M prefill refine 2026-10-03, candidate 4: texel-wise weight staging\n    // (glsl/sarc_dev/sarc_dev_linear_q4gsw_coopmat_bx.yaml).\n"
    for tok, m, n, k, sx, sy in T:
        rows += f'    {{"", nullptr, Op::kQ4gswLinear,\n     "sarc_dev_linear_q4gsw_coopmat_bx_{tok}", tile_mnk({m}, {n}, {k}, {sx}, {sy}, true),\n     kTex3dTex2d, nullptr, Status::kUnverified}},\n'
    t = sub(t, a, rows + a)
    a = "// Single-kernel SDPA screening profiles (qk-<tile>, av-<tile>).\n"
    t = sub(t, a, """// refine3 with the 4w texel-wise weight staging on the wide tile.
const Preference k780mRefine4[] = {
    {Op::kDq8caLinear, "bt_t128x64k32g22s32", nullptr},
    {Op::kQ4gswLinear, "bx_t128x256k32g42s32f32c", n_at_least_1024},
    {Op::kSdpaQk, "t128x64k32g22s64nf", nullptr},
    {Op::kSdpaAv, "t64x64k32g42s32", nullptr},
};
""" + a)
    a = '    {"780m-refine3", k780mRefine3, sizeof(k780mRefine3) / sizeof(Preference)},\n'
    t = sub(t, a, a + '    {"780m-refine4", k780mRefine4, sizeof(k780mRefine4) / sizeof(Preference)},\n')
    o.write_text(t)
print("bx family generated")
