/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_lin.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine): sweep tiles of sarc_linear_dq8ca_coopmat_zpgtr for this device.
 * Identical to the sweep wrapper from #version on; the body is the release body.
 */

#version 450 core

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
// 8-bit SSBO access: A is bound as a scalar int8_t array so that the
// coopMatLoad below has a MATCHING component type (see dbuf4tr's header for
// why the type must match on this driver).
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_control_flow_attributes : enable

#define PRECISION ${PRECISION}

$if WEIGHT_NBITS == 4:
  #define WEIGHT_INT4

$if HAS_BIAS:
  #define HAS_BIAS

$if WEIGHT_STORAGE == "buffer":
  #define WEIGHT_BUFFER

$if IO_STORAGE == "texture3d":
  #define IO_TEXTURE

// RTX 4070 Ti SUPER tuning (2026-09-26). Differential timing (each stage
// removed in turn) and nsys GPU metrics on the 4070 Ti showed the int8 MMA
// loop idle ~70% of the time, dominated by staging rather than by the MMAs.
//
// A_RAW: stage A as raw 16-byte vectors (uvec4 global load -> uvec4 LDS
// store) instead of coopMatLoad(global) -> coopMatStore(LDS). Ash_int8
// becomes a uvec4 array so each store is one 128-bit LDS store. Needs
// WG_TILE_M * WG_TILE_K / 16 to be a multiple of the workgroup size.
$if A_RAW:
  #define A_RAW
// B_PAIR: one weight texel fetch feeds both nibble parities of one component
// (output columns c and c + 4): half the fetches and half the prefetch
// registers of the one-uint-per-slot map.
$if B_PAIR:
  #define B_PAIR
// CSH_IN_ASH: stage the texture-IO drain band in Ash_int8, which is dead after
// the last MMA (every drain iteration starts with a barrier). Frees the
// Csh_out array so a WG_TILE_K = 64 tile fits the 48 KiB shared-memory limit.
$if CSH_IN_ASH:
  #define CSH_IN_ASH
// DRAIN_UNROLL: hand-expand the texture-IO drain band loop so every result[][]
// access has a constant index (the loop's barrier() keeps it rolled). Opt-in.
$if DRAIN_UNROLL:
  #define DRAIN_UNROLL
// B_SEL_EARLY_N: B slots si < N select their one int of the fetched texel right
// after the fetch instead of keeping the whole texel live. Opt-in.
$if B_SEL_EARLY_N > 0:
  #define B_SEL_EARLY_N ${B_SEL_EARLY_N}

layout(std430) buffer;

#include "common.glslh"

// Bindings — match add_linear_dqa_qw_node arg order:
//   output(0), fp_input(1), packed_int8_input(2), int_input_sums(3 - unused),
//   input_scales(4), input_zps(5), packed_weight(6), weight_sums(7),
//   weight_scales(8), bias(9).
${layout_declare_tensor(B, "w", "t_output",              "half", IO_STORAGE, is_scalar_array=True)}
// t_input is unread here -- the activations arrive already quantized in
// t_packed_int8_input -- but stays declared so the binding layout matches the
// dispatch site. It tracks IO_STORAGE so the two IO tensors stay consistent.
${layout_declare_tensor(B, "r", "t_input",               "half", IO_STORAGE, is_scalar_array=False)}
// ROW-MAJOR (kPackedInt8_4W) packed activations, bound as a scalar int8_t
// array (row stride = K int8) -- dbuf4tr's binding, unchanged. The stock
// 4h4w layout dbuf4zpg uses is NOT row-major (component index selects a row,
// non-affine), so it cannot be addressed by any coopMatLoad.
${layout_declare_tensor(B, "r", "t_packed_int8_input",   "int8", "buffer", is_scalar_array=True)}
#ifdef A_RAW
// uvec4 view of binding 2 (t_packed_int8_input) for 16-byte A staging.
// Spelled layout(std430, set...) on purpose: gen_vulkan_spv.py collects the
// descriptor list from every line matching ^layout\(set regardless of #ifdef,
// so the usual spelling would add a 13th descriptor to every variant.
layout(std430, set = 0, binding = 2) buffer restrict readonly t_packed_int8_input_v4Buffer {
  uvec4 t_packed_int8_input_v4[];
};
#endif
${layout_declare_tensor(B, "r", "t_int8_input_sums",     "int",  "buffer", is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_int8_input_scales",   "half", "texture3d")}
${layout_declare_tensor(B, "r", "t_int8_input_zps",      "int8", "texture3d")}
${layout_declare_tensor(B, "r", "t_packed_weight",       "int",  WEIGHT_STORAGE, is_scalar_array=False)}
${layout_declare_tensor(B, "r", "t_weight_sums",         "int",  "buffer", is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_weight_scales",       "half", "buffer", is_scalar_array=False)}
${layout_declare_tensor(B, "r", "t_bias",                "half", "buffer", is_scalar_array=True)}

${layout_declare_ubo(B, "ivec4", "output_sizes")}
${layout_declare_ubo(B, "ivec4", "input_sizes")}

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

${layout_declare_spec_const(C, "int", "apply_bias",   "0")}
// INT4 only; inert (0) for INT8 so the dispatcher's spec list lines up.
${layout_declare_spec_const(C, "int", "K4_per_group", "0")}
${layout_declare_spec_const(C, "int", "num_groups_arg", "0")}
${layout_declare_spec_const(C, "int", "out_N_arg", "0")}

// Tile geometry
const uint MMA_M = ${MMA_M};
const uint MMA_N = ${MMA_N};
const uint MMA_K = ${MMA_K};

const uint WG_TILE_M = ${WG_TILE_M};
const uint WG_TILE_N = ${WG_TILE_N};
const uint WG_TILE_K = ${WG_TILE_K};

const uint SG_GRID_X = ${SG_GRID_X};
const uint SG_GRID_Y = ${SG_GRID_Y};
const uint SUBGROUP_SIZE = ${SUBGROUP_SIZE};

#include "sarc_linear_dq8ca_coopmat_zpgtr_body.glslh"
