/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_df.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine). attn*V, direct feed (no operand staging).
 */

#version 450 core

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_control_flow_attributes : enable

#define PRECISION ${PRECISION}
// 0: fp32 accumulator; 1: fp16 per 32 of K, fp32 total; 2: fp16 accumulator.
#define ACC ${ACC}

layout(std430) buffer;

#include "common.glslh"

// Bindings mirror sdpa_compute_out_tiled: output(0), attn_weights(1), v(2).
${layout_declare_tensor(B, "w", "t_output", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_attn_weights", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_v", DTYPE, V_CACHE_STORAGE, is_scalar_array=True)}

${layout_declare_ubo(B, "ivec4", "q_sizes")}
${layout_declare_ubo(B, "ivec4", "v_sizes")}
${layout_declare_ubo(B, "int", "input_pos")}

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

// Same spec-constant list as glsl/sarc/sarc_sdpa_av_coopmat.glsl.
${layout_declare_spec_const(C, "float", "inv_scale_unused", "1.0")}
${layout_declare_spec_const(C, "int", "gqa_group_size_unused", "1")}
${layout_declare_spec_const(C, "int", "num_k_chunks_arg", "0")}
${layout_declare_spec_const(C, "int", "out_row_stride_arg", "0")}
${layout_declare_spec_const(C, "int", "head_dim_arg", "0")}

const uint MMA = 16;
const uint WG_TILE_M = ${WG_TILE_M};
const uint WG_TILE_N = ${WG_TILE_N};
const uint SG_GRID_X = ${SG_GRID_X};
const uint SG_GRID_Y = ${SG_GRID_Y};
const uint SG_TILE_M = WG_TILE_M / SG_GRID_Y;
const uint SG_TILE_N = WG_TILE_N / SG_GRID_X;
const uint MI = SG_TILE_M / MMA;
const uint NJ = SG_TILE_N / MMA;

#define ACC32 coopmat<float, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define ACC16 coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define MAT_A coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseA>
#define MAT_B coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseB>
#if ACC == 2
#define RES ACC16
#else
#define RES ACC32
#endif
RES result[MI][NJ];
#if ACC == 1
ACC16 part[MI][NJ];
#endif

void main() {
    const uvec2 tileID = uvec2(gl_WorkGroupID.xy);
    const uvec2 sgInTile = uvec2(gl_SubgroupID % SG_GRID_X, gl_SubgroupID / SG_GRID_X);
    const int q_h = int(gl_WorkGroupID.z);

    // LLM layout: q_sizes WHCN {D, H_q, S, B}; v_sizes WHCN {D, H_kv, C_max, B}.
    const int Q_H = q_sizes.y;
    const int S = q_sizes.z;
    const int KV_H = v_sizes.y;
    const int S_aligned = align_up_4(S);
    const int context_len = input_pos + S;
    const uint W = uint(div_up_4(context_len)) * 4u;
    const uint D = uint(head_dim_arg);

    int kv_h = q_h;
    if (KV_H < Q_H) {
        kv_h = q_h / (Q_H / KV_H);
    }

    const uint s0 = WG_TILE_M * tileID.y + SG_TILE_M * sgInTile.y;
    const uint d0 = WG_TILE_N * tileID.x + SG_TILE_N * sgInTile.x;
    if (s0 >= uint(S) || d0 >= D) {
        return;
    }

    [[unroll]] for (uint i = 0; i < MI; ++i) {
        [[unroll]] for (uint j = 0; j < NJ; ++j) {
            result[i][j] = RES(0.0);
        }
    }

    // P[s, c] == 0 for c > s + input_pos (the softmax writes the masked tail as
    // zero), so the rows of this subgroup need context columns up to max_c only.
    // 32-wide groups: context_len is a multiple of 32 (the row's k).
    const uint max_c = min(s0 + SG_TILE_M - 1u + uint(input_pos), uint(context_len) - 1u);
    const uint groups = min(uint(num_k_chunks_arg), max_c / 32u + 1u);

    const uint a_base = (uint(q_h) * uint(S_aligned) + s0) * W;
    const uint v_stride = uint(KV_H) * D;
    const uint b_base = uint(kv_h) * D + d0;

    for (uint grp = 0; grp < groups; ++grp) {
#if ACC == 1
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                part[i][j] = ACC16(0.0);
            }
        }
#endif
        [[unroll]] for (uint kk = 0; kk < 32u; kk += MMA) {
            const uint c = grp * 32u + kk;
            MAT_A matA[MI];
            [[unroll]] for (uint i = 0; i < MI; ++i) {
                coopMatLoad(matA[i], t_attn_weights, a_base + MMA * i * W + c, W,
                            gl_CooperativeMatrixLayoutRowMajor);
            }
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                MAT_B matB;
                coopMatLoad(matB, t_v, c * v_stride + b_base + MMA * j, v_stride,
                            gl_CooperativeMatrixLayoutRowMajor);
                [[unroll]] for (uint i = 0; i < MI; ++i) {
#if ACC == 1
                    part[i][j] = coopMatMulAdd(matA[i], matB, part[i][j]);
#else
                    result[i][j] = coopMatMulAdd(matA[i], matB, result[i][j]);
#endif
                }
            }
        }
#if ACC == 1
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                result[i][j] += ACC32(part[i][j]);
            }
        }
#endif
    }

    // DHSB output, head-interleaved; the stride is a spec constant.
    const uint out_row_stride = uint(out_row_stride_arg);
    const uint out_base = s0 * out_row_stride + uint(q_h) * D + d0;
    [[unroll]] for (uint i = 0; i < MI; ++i) {
        [[unroll]] for (uint j = 0; j < NJ; ++j) {
#if ACC == 2
            coopMatStore(result[i][j], t_output,
#else
            ACC16 out_tile = ACC16(result[i][j]);
            coopMatStore(out_tile, t_output,
#endif
                         out_base + MMA * i * out_row_stride + MMA * j, out_row_stride,
                         gl_CooperativeMatrixLayoutRowMajor);
        }
    }
}
