/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, RTX 4070 Ti SUPER (generated by gen_4070ti_df.py;
 * openspec/changes/sarc-1.5-4070ti-prefill-refine). QK^T, direct feed (no operand staging), NO_MASK_FILL.
 */

#version 450 core

#extension GL_KHR_cooperative_matrix : require
#extension GL_KHR_memory_scope_semantics : require
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_control_flow_attributes : enable

#define PRECISION ${PRECISION}
// 0: fp32 accumulator; 1: fp16 per 32 of K, fp32 total; 2: fp16 accumulator.
#define ACC ${ACC}

layout(std430) buffer;

#include "common.glslh"

// Bindings mirror sdpa_compute_attn_weights_tiled: attn_weights(0), q(1), k(2).
${layout_declare_tensor(B, "w", "t_attn_weights", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_q", DTYPE, IO_STORAGE, is_scalar_array=True)}
${layout_declare_tensor(B, "r", "t_k", DTYPE, K_CACHE_STORAGE, is_scalar_array=True)}

${layout_declare_ubo(B, "ivec4", "q_sizes")}
${layout_declare_ubo(B, "ivec4", "k_sizes")}
${layout_declare_ubo(B, "int", "input_pos")}

layout(local_size_x_id = 0, local_size_y_id = 1, local_size_z_id = 2) in;

${layout_declare_spec_const(C, "float", "inv_scale", "1.0")}
// head_dim / 32 (from the table row) and the attn_weights row width at node
// construction, as in glsl/sarc/sarc_sdpa_qk_coopmat.glsl.
${layout_declare_spec_const(C, "int", "num_k_chunks_arg", "0")}
${layout_declare_spec_const(C, "int", "aw_row_width_arg", "0")}

const uint MMA = 16;
const uint WG_TILE_M = ${WG_TILE_M};
const uint WG_TILE_N = ${WG_TILE_N};
const uint SG_GRID_X = ${SG_GRID_X};
const uint SG_GRID_Y = ${SG_GRID_Y};
const uint SG_TILE_M = WG_TILE_M / SG_GRID_Y;
const uint SG_TILE_N = WG_TILE_N / SG_GRID_X;
const uint MI = SG_TILE_M / MMA;
const uint NJ = SG_TILE_N / MMA;

#define ACC32 coopmat<float, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define ACC16 coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseAccumulator>
#define MAT_A coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseA>
#define MAT_B coopmat<float16_t, gl_ScopeSubgroup, MMA, MMA, gl_MatrixUseB>
#if ACC == 2
#define RES ACC16
#else
#define RES ACC32
#endif
RES result[MI][NJ];
#if ACC == 1
ACC16 part[MI][NJ];
#endif

// Scratch of the slow path only (row width differs from the baked one).
shared float16_t Csh[WG_TILE_M * WG_TILE_N];

void main() {
    const uvec2 tileID = uvec2(gl_WorkGroupID.xy);
    const uvec2 sgInTile = uvec2(gl_SubgroupID % SG_GRID_X, gl_SubgroupID / SG_GRID_X);
    const int q_h = int(gl_WorkGroupID.z);

    // LLM layout: q_sizes WHCN {D, H_q, S, B}; k_sizes WHCN {D, H_kv, C_max, B}.
    const int Q_H = q_sizes.y;
    const int S = q_sizes.z;
    const int KV_H = k_sizes.y;
    const int S_aligned = align_up_4(S);
    const int context_len = input_pos + S;
    const int aw_row_width = div_up_4(context_len) * 4;
    const uint D = uint(num_k_chunks_arg) * 32u;

    int kv_h = q_h;
    if (KV_H < Q_H) {
        kv_h = q_h / (Q_H / KV_H);
    }

    const uint s_tile_base = WG_TILE_M * tileID.y;
    const uint c_tile_base = WG_TILE_N * tileID.x;
    if (c_tile_base >= uint(context_len) || s_tile_base >= uint(S)) {
        return;
    }
    // Every element of the workgroup tile is masked: nothing is read from it.
    if (int(c_tile_base) > int(s_tile_base) + int(WG_TILE_M) - 1 + input_pos) {
        return;
    }

    const uint s0 = s_tile_base + SG_TILE_M * sgInTile.y;
    const uint c0 = c_tile_base + SG_TILE_N * sgInTile.x;
    const bool sg_masked = int(c0) > int(s0) + int(SG_TILE_M) - 1 + input_pos;

    if (!sg_masked) {
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                result[i][j] = RES(0.0);
            }
        }
        const uint q_stride = uint(Q_H) * D;
        const uint k_stride = uint(KV_H) * D;
        const uint q_base = (s0 * uint(Q_H) + uint(q_h)) * D;
        const uint k_base = (c0 * uint(KV_H) + uint(kv_h)) * D;
#if ACC == 1
        for (uint kg = 0; kg < D; kg += 32u) {
            [[unroll]] for (uint i = 0; i < MI; ++i) {
                [[unroll]] for (uint j = 0; j < NJ; ++j) {
                    part[i][j] = ACC16(0.0);
                }
            }
            [[unroll]] for (uint kk = 0; kk < 32u; kk += MMA) {
                const uint k = kg + kk;
#else
        {
            for (uint k = 0; k < D; k += MMA) {
#endif
                MAT_A matA[MI];
                [[unroll]] for (uint i = 0; i < MI; ++i) {
                    coopMatLoad(matA[i], t_q, q_base + MMA * i * q_stride + k, q_stride,
                                gl_CooperativeMatrixLayoutRowMajor);
                }
                [[unroll]] for (uint j = 0; j < NJ; ++j) {
                    // B = K^T [d][c]: element (d, c) is K[c][d], a column-major read of K.
                    MAT_B matB;
                    coopMatLoad(matB, t_k, k_base + MMA * j * k_stride + k, k_stride,
                                gl_CooperativeMatrixLayoutColumnMajor);
                    [[unroll]] for (uint i = 0; i < MI; ++i) {
#if ACC == 1
                        part[i][j] = coopMatMulAdd(matA[i], matB, part[i][j]);
#else
                        result[i][j] = coopMatMulAdd(matA[i], matB, result[i][j]);
#endif
                    }
                }
            }
#if ACC == 1
            [[unroll]] for (uint i = 0; i < MI; ++i) {
                [[unroll]] for (uint j = 0; j < NJ; ++j) {
                    result[i][j] += ACC32(part[i][j]);
                }
            }
#endif
        }
    }

    // The store stride must be a compile-time value (see the release kernel's
    // header): the baked row width is used only when it is the live one.
    const bool direct =
        aw_row_width_arg == aw_row_width &&
        s_tile_base + WG_TILE_M <= uint(S) &&
        c_tile_base + WG_TILE_N <= uint(context_len);
    if (direct) {
        if (sg_masked) {
            return;
        }
        const uint STRIDE = uint(aw_row_width_arg);
        const uint aw_base = (uint(q_h) * uint(S_aligned) + s0) * STRIDE + c0;
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
                // An MMA tile wholly above the diagonal is never read.
                if (int(c0 + MMA * j) <= int(s0 + MMA * i + MMA - 1u) + input_pos) {
#if ACC == 2
                    ACC16 out_tile = result[i][j] * float16_t(inv_scale);
#else
                    ACC16 out_tile = ACC16(result[i][j] * inv_scale);
#endif
                    coopMatStore(out_tile, t_attn_weights,
                                 aw_base + MMA * i * STRIDE + MMA * j, STRIDE,
                                 gl_CooperativeMatrixLayoutRowMajor);
                }
            }
        }
        return;
    }

    // Slow path: through a shared scratch with a compile-time stride, then a
    // scalar copy of the visible elements. All subgroups reach the barrier.
    if (!sg_masked) {
        [[unroll]] for (uint i = 0; i < MI; ++i) {
            [[unroll]] for (uint j = 0; j < NJ; ++j) {
#if ACC == 2
                ACC16 out_tile = result[i][j] * float16_t(inv_scale);
#else
                ACC16 out_tile = ACC16(result[i][j] * inv_scale);
#endif
                coopMatStore(out_tile, Csh,
                             (SG_TILE_M * sgInTile.y + MMA * i) * WG_TILE_N +
                                 SG_TILE_N * sgInTile.x + MMA * j,
                             WG_TILE_N, gl_CooperativeMatrixLayoutRowMajor);
            }
        }
    }
    memoryBarrierShared();
    barrier();
    const uint WG_SIZE = SG_GRID_X * SG_GRID_Y * ${SUBGROUP_SIZE}u;
    for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * WG_TILE_N; idx += WG_SIZE) {
        const uint gs = s_tile_base + idx / WG_TILE_N;
        const uint gc = c_tile_base + idx % WG_TILE_N;
        if (gs < uint(S) && gc < uint(context_len) && int(gc) <= int(gs) + input_pos) {
            t_attn_weights[(uint(q_h) * uint(S_aligned) + gs) * uint(aw_row_width) + gc] = Csh[idx];
        }
    }
}
