#!/usr/bin/env python3
"""Arc B580 dev-zone content of sarc-1.5-b580-prefill-refine, generated.

usage: gen_b580.py <executorch tree>

Writes, and rewrites idempotently:
  - impl/sarc_dev/B580Sdpa.cpp: the B580 SDPA base rows (device string `bmg g21` only, kUnverified, active only
    while ET_VK_SARC_DEV_PROFILE names a b580-* profile), so every other configuration of a dev build selects
    exactly what the release tables select. Same mechanism as impl/sarc_dev/Xe2Sdpa.cpp of the B70 campaign.
  - the b580 blocks of impl/sarc_dev/Overrides.cpp: one single-kernel screening profile per SDPA candidate row
    that exists in the dev zone (b580-qk-<family>-<tile>, b580-av-<family>-<tile>; the candidate rows themselves
    are the B70 campaign's, registered by name for any device) and the b580-refineN candidates (REFINE below).
Never writes a release-zone file. Blocks are delimited by "b580 begin" / "b580 end" comments."""
import pathlib, re, sys
root = pathlib.Path(sys.argv[1]) / "backends/vulkan"
impl = root / "runtime/graph/ops/impl/sarc_dev"

# (profile, [(op, token, shape predicate or None)], comment)
REFINE = [
    ("b580-sdpa0", [], "base rows only: the straight port"),
    ("b580-refine0", [("kSdpaQk", "pk_t128x64k32g44s16m8nf", None), ("kSdpaAv", "xe2_t128x64k32g44s16m8", "b580_head_dim_128")],
     "candidate 0 = the B70's accepted xe2-refine1 kernels, selected for this card"),
]
BASE = [("kSdpaQk", "sarc_sdpa_qk_coopmat_sweep_t128x64k32g44s16m8nf", "128, 64, 32, 4, 4"),
        ("kSdpaAv", "sarc_sdpa_av_coopmat_sweep_t64x64k32g44s16m8", "64, 64, 32, 4, 4")]

def block(text, begin, end, body, anchor):
    if begin in text:
        a = text.index(begin); b = text.index(end, a) + len(end)
        return text[:a] + begin + body + end + text[b:]
    assert text.count(anchor) == 1, f"anchor occurs {text.count(anchor)} times: {anchor[:60]!r}"
    return text.replace(anchor, begin + body + end + anchor)

cands = []   # (op, family, tile) of every SDPA candidate row in the dev zone
for f in sorted(impl.glob("*.cpp")):
    for op, name in re.findall(r'Op::(kSdpaQk|kSdpaAv),\s*"(sarc_sdpa_(?:qk|av)_coopmat_[a-z0-9_]+)"', f.read_text()):
        m = re.fullmatch(r"sarc_sdpa_(?:qk|av)_coopmat_([a-z0-9]+)_(t\d+x\d+k\d+g\d+s16m8(?:nf)?)", name)
        if m and (op, m[1], m[2]) not in cands: cands.append((op, m[1], m[2]))

rows = "".join(f'    {{"bmg g21", b580_profile_requested, Op::{op},\n     "{name}",\n     {{{dims}, 16, 8, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n' for op, name, dims in BASE)
(impl / "B580Sdpa.cpp").write_text(f"""/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

// SARC development zone, Intel Arc B580 (device tag b580): SDPA prefill base
// rows for the device string "bmg g21" only (openspec/changes/
// sarc-1.5-b580-prefill-refine; generated by its tools/gen_b580.py). Not part
// of a release.
//
// Same mechanism as Xe2Sdpa.cpp: kUnverified rows (ET_VK_SARC_UNVERIFIED=1)
// that match only while ET_VK_SARC_DEV_PROFILE names a b580-* profile, so
// every other configuration selects exactly what the release tables select.
// The b580-* profiles (Overrides.cpp) then pick this card's kernels by name.

#include <executorch/backends/vulkan/runtime/graph/ops/impl/sarc/Select.h>

#include <cstdlib>
#include <cstring>

namespace vkcompute {{
namespace sarc {{
namespace {{

bool b580_profile_requested(const DeviceInfo&) {{
  const char* e = std::getenv("ET_VK_SARC_DEV_PROFILE");
  return e != nullptr && std::strncmp(e, "b580-", 5) == 0;
}}

const Row kB580SdpaRows[] = {{
{rows}}};

struct Registrar {{
  Registrar() {{
    register_rows(
        kB580SdpaRows, sizeof(kB580SdpaRows) / sizeof(kB580SdpaRows[0]));
  }}
}} registrar;

}} // namespace
}} // namespace sarc
}} // namespace vkcompute
""")

ident = lambda s: re.sub(r"[^A-Za-z0-9]", "_", s)
prefs = ("// Single-kernel screening profiles and the b580-refineN candidates. They take effect on the Arc B580 only\n"
         "// (SDPA base rows of impl/sarc_dev/B580Sdpa.cpp, ET_VK_SARC_UNVERIFIED=1).\n"
         "// attn*V: ShapeInfo::N is head_dim.\nbool b580_head_dim_128(const ShapeInfo& s) {\n  return s.N >= 128;\n}\n")
profs = ""
for op, fam, tile in cands:
    kind = "qk" if op == "kSdpaQk" else "av"; name = f"b580-{kind}-{fam}-{tile}"
    prefs += f'const Preference kB580_{ident(name[5:])}[] = {{{{Op::{op}, "{fam}_{tile}", nullptr}}}};\n'
    profs += f'    {{"{name}", kB580_{ident(name[5:])}, 1}},\n'
for name, ps, why in REFINE:
    if ps:
        prefs += f"// {why}\nconst Preference kB580_{ident(name[5:])}[] = {{\n" + "".join(
            f'    {{Op::{op}, "{t}", {p or "nullptr"}}},\n' for op, t, p in ps) + "};\n"
        profs += f'    {{"{name}", kB580_{ident(name[5:])}, sizeof(kB580_{ident(name[5:])}) / sizeof(Preference)}},\n'
    else:
        profs += f'    {{"{name}", nullptr, 0}},\n'
o = impl / "Overrides.cpp"; t = o.read_text()
t = block(t, "// b580 begin: Arc B580 profiles (openspec/changes/sarc-1.5-b580-prefill-refine, tools/gen_b580.py)\n", "// b580 end\n", prefs, "struct Profile {\n")
t = block(t, "    // b580 begin: Arc B580 profiles (tools/gen_b580.py)\n", "    // b580 end\n", profs, "};\nconst Profile* requested_profile() {")
o.write_text(t)
print(f"{len(cands)} screening profiles, {len(REFINE)} named profiles")
