#!/bin/bash
# Generate a SARC release from dev/1.5: the tree of HEAD minus the dev zone.
#
# usage: make-release.sh --export <dir>/executorch
#            Write the release tree of the current working tree (tracked files
#            and initialized submodules, minus the dev zone and build/venv
#            output) to <dir>/executorch, for building. Incremental (rsync).
#        make-release.sh --commit <rN> [--dry-run]
#            Run check.sh, then append a commit to branch sarc/1.5 whose tree
#            is HEAD's tree minus the dev zone (parent: the previous release,
#            or release/1.5 for the first) and tag it sarc/1.5-<rN>. Needs a
#            clean working tree. --dry-run writes branch sarc/1.5-dryrun and no tag.
#            Nothing is pushed.
set -euo pipefail
SARC_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
. "$SARC_ROOT/sarc/tools/zones.sh"
cd "$SARC_ROOT"

case ${1:-} in
  --export)
    DST=$(realpath -m "$2")
    [[ $(basename "$DST") == executorch ]] || { echo "export dir must end in /executorch" >&2; exit 2; }
    mkdir -p "$DST"
    EX=(--exclude=/.git --exclude=/.venv --exclude=/pip-out --exclude='/cmake-out*' --exclude='/build*/')
    for z in "${SARC_DEV_ZONE[@]}"; do EX+=("--exclude=/${z%/}"); done
    # tracked + submodule content; untracked files outside the zones are an error (check.sh)
    rsync -a --delete "${EX[@]}" --exclude='.git' "$SARC_ROOT/" "$DST/"
    echo "exported release tree to $DST"
    ;;
  --commit)
    RN=$2; DRY=${3:-}
    [[ -z $(git status --porcelain --untracked-files=normal) ]] || { echo "working tree not clean" >&2; exit 1; }
    [[ $DRY == --dry-run ]] || "$SARC_ROOT/sarc/tools/check.sh"
    SRC=$(git rev-parse HEAD)
    IDX=$(mktemp); trap 'rm -f "$IDX"' EXIT
    GIT_INDEX_FILE=$IDX git read-tree "$SRC"
    for z in "${SARC_DEV_ZONE[@]}"; do GIT_INDEX_FILE=$IDX git rm -r -q --cached --ignore-unmatch "${z%/}"; done
    TREE=$(GIT_INDEX_FILE=$IDX git write-tree)
    BR=$SARC_RELEASE_BRANCH; [[ $DRY == --dry-run ]] && BR=$SARC_RELEASE_BRANCH-dryrun
    if git rev-parse -q --verify "refs/heads/$BR" >/dev/null; then PARENT=$(git rev-parse "refs/heads/$BR");
    else PARENT=$(git rev-parse "$SARC_BASE"); fi
    MSG="SARC release ${SARC_RELEASE_BRANCH}-$RN

Generated by sarc/tools/make-release.sh from dev/1.5 $SRC:
the dev/1.5 tree without the development zone (${SARC_DEV_ZONE[*]}).

Shipped selection rows (impl/sarc/table_*.cpp) and hooks (sarc/HOOKS at the
source commit) define what this release changes relative to ${SARC_BASE#origin/}."
    C=$(git commit-tree "$TREE" -p "$PARENT" -m "$MSG")
    git update-ref "refs/heads/$BR" "$C"
    [[ $DRY == --dry-run ]] || git tag -a "${SARC_RELEASE_BRANCH}-$RN" "$C" -m "SARC release ${SARC_RELEASE_BRANCH}-$RN (dev/1.5 $SRC)"
    echo "$BR -> $C"; git diff --stat "$SARC_BASE" "$C" | tail -1
    ;;
  *) sed -n '2,14p' "$0"; exit 2 ;;
esac
