#!/usr/bin/env python3
"""gen_sl.py <executorch tree>: the 4w kernel with a slab layout of both operands in shared memory (dev zone).

In the release body B_COLMAJOR stages B column-major with a padded column of WG_TILE_K + 8 halves and A row-major
with a padded row; FRAG_LAYOUT stages A as [k16 block][m][16 k] (a 16 x 16 A tile is 16 contiguous 32-byte runs,
no padding) but B row-major, and the two cannot be combined. This twin combines them: A as FRAG_LAYOUT has it and
B as [k16 slab][n][16 k], so that both operand tiles of a multiply-add are 16 contiguous 32-byte runs, which is
the layout the 8da4w zpg kernel already uses. Same values in the same accumulation order: bit-identical output.
Needs MMA_K == 16, B_COLMAJOR and FRAG_LAYOUT. Writes glsl/sarc_dev/sarc_dev_780m_linear_q4gsw_coopmat_sl{.glsl,.yaml,_body.glslh}.

MEASURED AND NOT PURSUED (2026-10-05): 8 to 25 % slower than the padded column-major kernels of the same tile on
all twelve shapes (results/780m/space/slab/kernel-time.txt). The generated files and their candidate rows are not
in the tree; to rebuild them run this tool and register rows for the yaml's variants (kTex3dTex2d, CSH_BAND dims).
The family name must contain "linear_" and "coopmat": the microbench finds the kernel time by them."""
import pathlib, sys
g = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops/glsl"
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    return text.replace(old, new)
b = (g / "sarc/sarc_linear_q4gsw_coopmat_body.glslh").read_text()
b = b.replace("SARC_LINEAR_Q4GSW_COOPMAT_BODY_GLSLH", "SARC_DEV_780M_LINEAR_Q4GSW_COOPMAT_SL_BODY_GLSLH")
b = sub(b, "#ifndef SARC_DEV_780M_LINEAR_Q4GSW_COOPMAT_SL_BODY_GLSLH", "// GENERATED by gen_sl.py from the release 4w body (slab layout of A and B).\n#ifndef SARC_DEV_780M_LINEAR_Q4GSW_COOPMAT_SL_BODY_GLSLH")
b = sub(b, """#if defined(FRAG_LAYOUT)
#error "B_COLMAJOR is not combined with FRAG_LAYOUT"
#endif
const uint BT_STRIDE_H = WG_TILE_K + 8u;
const uint BT_STRIDE_V2 = BT_STRIDE_H / 4u;
const uint BT_SLICE = WG_TILE_N * BT_STRIDE_V2;
""", """#if defined(FRAG_LAYOUT)
// Slab layout (dev): [k16 slab][n][16 k], 4 uvec2 per column and slab, no
// padding. (n, k) -> slice-relative index of the uvec2 holding k .. k + 3.
const uint BT_STRIDE_V2 = 4u;
const uint BT_SLICE = WG_TILE_N * (WG_TILE_K / 4u);
#define BT_IDX(n, k) (((k) / 16u) * WG_TILE_N + (n)) * 4u + ((k) % 16u) / 4u
#else
const uint BT_STRIDE_H = WG_TILE_K + 8u;
const uint BT_STRIDE_V2 = BT_STRIDE_H / 4u;
const uint BT_SLICE = WG_TILE_N * BT_STRIDE_V2;
#define BT_IDX(n, k) (n) * BT_STRIDE_V2 + (k) / 4u
#endif
""")
b = sub(b, "BshT[base + (n_local + j) * BT_STRIDE_V2 + k_local / 4u] =", "BshT[base + BT_IDX(n_local + j, k_local)] =")
b = sub(b, "cur_base_B + n_b * BT_STRIDE_V2 + k_start / 4u,", "cur_base_B + BT_IDX(n_b, k_start),", 2)
(g / "sarc_dev/sarc_dev_780m_linear_q4gsw_coopmat_sl_body.glslh").write_text(b)
w = (g / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.glsl").read_text()
w = w[w.index("#version 450 core"):]
w = sub(w, '#include "sarc_linear_q4gsw_coopmat_body.glslh"', '#include "sarc_dev_780m_linear_q4gsw_coopmat_sl_body.glslh"')
(g / "sarc_dev/sarc_dev_780m_linear_q4gsw_coopmat_sl.glsl").write_text("""/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, 780M: 4w kernel with a slab layout of both operands in shared memory (generated by
 * gen_sl.py; openspec/changes/sarc-1.5-780m-prefill-refine). The wrapper is the q4gsw sweep wrapper with a
 * different body. Only for variants with B_COLMAJOR and FRAG_LAYOUT.
 */

""" + w)
y = (g / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.yaml").read_text()
defaults = y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
T = [(256, 128, 1, 8), (256, 128, 2, 8), (256, 128, 2, 4), (128, 256, 4, 2), (128, 256, 2, 4), (128, 128, 4, 2)]
out = "# SARC development zone, 780M: 4w with a slab layout of A and B in shared memory (generated by gen_sl.py). Not shipped.\n# Name: t<M>x<N>k32g<X><Y>s32f32b = ACC_FP32 + CSH_BAND, always with B_COLMAJOR + FRAG_LAYOUT.\n\nsarc_dev_780m_linear_q4gsw_coopmat_sl:\n" + defaults + "  shader_variants:\n"
for m, n, sx, sy in T:
    k = 32; wg = sx * sy * 32
    assert m % (wg // (k // 8)) == 0 and (m // sy) % 16 == 0 and (n // sx) % 16 == 0
    lds = 2 * m * k * 2 + 2 * n * k * 2 + 16 * n * 2   # A, B (two slices each, no padding) + the band drain
    assert lds <= 65536, (m, n, lds)
    out += f"    # shared memory {lds} bytes\n    - NAME: sarc_dev_780m_linear_q4gsw_coopmat_sl_t{m}x{n}k32g{sx}{sy}s32f32b_texture3d_texture2d_half\n      IO_STORAGE: texture3d\n      WEIGHT_STORAGE: texture2d\n"
    out += f"      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n      WG_TILE_K: {k}\n      SG_GRID_X: {sx}\n      SG_GRID_Y: {sy}\n      SUBGROUP_SIZE: 32\n      ACC_FP32: true\n      CSH_BAND: true\n      B_COLMAJOR: true\n      FRAG_LAYOUT: true\n"
(g / "sarc_dev/sarc_dev_780m_linear_q4gsw_coopmat_sl.yaml").write_text(out)
print("slab twin written:", [f"t{m}x{n}k32g{sx}{sy}s32f32b" for m, n, sx, sy in T])
