#!/usr/bin/env python3
"""gen_rx7600_dq.py: writes glsl/sarc_dev/sarc_dev_rx7600_dq8ca_zpg.yaml and impl/sarc_dev/SpaceRx7600Dq.inc from one table of
variants (round 2, candidate 1: 8da4w). Run from the repository root: python3 -I <this file>. Suffixes: padN = A_PAD N uint between
the K slabs of A in shared memory; csha = drain tile in the A staging buffer; p = phase timing, ablN = removed work (both
MEASUREMENT ONLY, wrong results by design)."""
import sys
G = "backends/vulkan/runtime/graph/ops/glsl/sarc_dev/sarc_dev_rx7600_dq8ca_zpg.yaml"
I = "backends/vulkan/runtime/graph/ops/impl/sarc_dev/SpaceRx7600Dq.inc"
HEAD = """# SARC development zone, RX 7600 campaign round 2: the shipped 8da4w zpg kernel (release body copy) with options, default off.
# GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_dq.py; do not edit. Not shipped. Candidate kernels
# are selected by the rx7600 profiles in impl/sarc_dev/Overrides.cpp; the measurement-only variants (suffix p = phase timing,
# ablN = removed work; they write wrong results by design) only by exact name (ET_VK_SARC_780M_DQ).

sarc_dev_rx7600_dq8ca_zpg:
  parameter_names_with_default_values:
    PRECISION: highp
    HAS_BIAS: false
    IO_STORAGE: texture3d
    WEIGHT_NBITS: 4
    WEIGHT_STORAGE: texture2d
    A_MAP_FULL: true
    A_MULTI_BLOCK: true
    A_BLOCKS: 1
    A_PAD: 0
    CSH_IN_ASH: false
    PROF: false
    ABL: 0
    MMA_M: 16
    MMA_N: 16
    MMA_K: 16
    WG_TILE_M: 256
    WG_TILE_N: 64
    WG_TILE_K: 64
    SG_GRID_X: 4
    SG_GRID_Y: 8
    SUBGROUP_SIZE: 32
  shader_variants:
"""
# (suffix, WG_TILE_N, A_PAD, CSH_IN_ASH, PROF, ABL)
V = [("t256x64k64g48s32", 64, 0, False, False, 0),
     ("t256x64k64g48s32pad4", 64, 4, False, False, 0),
     ("t256x64k64g48s32pad8", 64, 8, False, False, 0),
     ("t256x64k64g48s32p", 64, 0, False, True, 0),
     ("t256x64k64g48s32pad4p", 64, 4, False, True, 0)]
for a in (1, 2, 4, 8, 16, 3, 7, 15, 31):
    V.append((f"t256x64k64g48s32abl{a}", 64, 0, False, False, a))
V += [("t256x128k64g48s32csha", 128, 0, True, False, 0),
      ("t256x128k64g48s32pad4csha", 128, 4, True, False, 0),
      ("t256x128k64g48s32pad4cshap", 128, 4, True, True, 0)]
y = HEAD
inc = "// GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_dq.py. Do not edit.\n"
for s, n, pad, csh, prof, abl in V:
    base = f"sarc_dev_rx7600_dq8ca_zpg_{s}"
    y += f"    - NAME: {base}_texture3d_texture2d_half\n      WG_TILE_N: {n}\n"
    if pad: y += f"      A_PAD: {pad}\n"
    if csh: y += "      CSH_IN_ASH: true\n"
    if prof: y += "      PROF: true\n"
    if abl: y += f"      ABL: {abl}\n"
    inc += (f'{{"", nullptr, Op::kDq8caLinear, "{base}", {{256, {n}, 64, 4, 8, 32, 16, {"true" if csh else "false"}, false, false}}, '
            f'kTex3dTex2d, nullptr, Status::kUnverified}},\n')
open(G, "w").write(y); open(I, "w").write(inc)
print(len(V), "variants")
