#!/usr/bin/env python3
"""gen_space.py <executorch tree> <selection dir>: write the 780M parameter-space variants into the dev zone.

For each family file <selection dir>/<family>.txt (4w, 8da4w, qk, av; one enum_space.py token per line, "#"
comments allowed; a missing file means no variant of that family) this writes
  glsl/sarc_dev/<template>.glsl   a copy of the existing wrapper under a 780M template name (a template can have
                                   only one yaml); the bodies are the ones the source wrappers include
  glsl/sarc_dev/<template>.yaml   the source yaml's defaults and one variant per selected token
  impl/sarc_dev/Space780m.inc     one candidate Row per variant, included by the 780m block of Overrides.cpp
Every token must be a survivor of enum_space.py (asserted), so nothing over the shared-memory limit is built.
Kernels are selected by exact base name: ET_VK_SARC_780M_{Q4,DQ,QK,AV}=<kernel base> (Overrides.cpp, 780m block).

The committed tree holds the selection in results/780m/space/committed/; the exhaustive sweep build is generated
from results/780m/space/sweep/ into a scratch copy of the tree and is not committed.
"""
import pathlib, sys, yaml
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import enum_space as es, gen_space_names as gn

tree, sel = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
g = tree / "backends/vulkan/runtime/graph/ops/glsl/sarc_dev"
inc = tree / "backends/vulkan/runtime/graph/ops/impl/sarc_dev/Space780m.inc"

# family -> {token prefix: (source template, new template)}
TEMPLATES = {
    "4w": {"": ("sarc_linear_q4gsw_coopmat_sweep", "sarc_dev_780m_x_linear_q4gsw_coopmat"),
           "bx_": ("sarc_dev_linear_q4gsw_coopmat_bx", "sarc_dev_780m_x_linear_q4gsw_coopmat_bx")},
    "8da4w": {"": ("sarc_linear_dq8ca_coopmat_zpg_sweep", "sarc_dev_780m_x_linear_dq8ca_coopmat_zpg"),
              "bt_": ("sarc_dev_linear_dq8ca_coopmat_zpg_bt", "sarc_dev_780m_x_linear_dq8ca_coopmat_zpg_bt")},
    "qk": {"": ("sarc_sdpa_qk_coopmat_sweep", "sarc_sdpa_qk_coopmat_x780m"),
           "pk_": ("sarc_sdpa_qk_coopmat_pk", "sarc_sdpa_qk_coopmat_x780m_pk")},
    "av": {"": ("sarc_sdpa_av_coopmat_sweep", "sarc_sdpa_av_coopmat_x780m"),
           "ml_": ("sarc_sdpa_av_coopmat_ml", "sarc_sdpa_av_coopmat_x780m_ml")},
}
OP = {"4w": "kQ4gswLinear", "8da4w": "kDq8caLinear", "qk": "kSdpaQk", "av": "kSdpaAv"}

def params(fam, c):
    M, N, K, X, Y, S = c["g"]
    p = dict(WG_TILE_M=M, WG_TILE_N=N, WG_TILE_K=K, SG_GRID_X=X, SG_GRID_Y=Y, SUBGROUP_SIZE=S)
    if fam == "4w":
        mm, mn, mk = c["mma"]; p.update(MMA_M=mm, MMA_N=mn, MMA_K=mk, **c["f"])
    elif fam == "8da4w":
        mm, mn, mk = c["mma"]
        p.update(MMA_M=mm, MMA_N=mn, MMA_K=mk, A_MAP_FULL=c["full"], A_MULTI_BLOCK=c["multi"], A_BLOCKS=c["blocks"])
    elif fam == "qk":
        p.update(NO_MASK_FILL=c["nf"])
    return p

def prefix(fam, c):
    return {"4w": "bx_" if c.get("bx") else "", "8da4w": "bt_" if c.get("bt") else "",
            "qk": "pk_" if c.get("pk") else "", "av": "ml_" if c.get("ml") else ""}[fam]

rows = []; counts = {}
for fam, tmpl in TEMPLATES.items():
    f = sel / f"{fam}.txt"
    want = [l.split()[0].split("/")[0] for l in f.read_text().splitlines() if l.strip() and not l.startswith("#")] if f.exists() else []
    assert len(want) == len(set(want)), f"{fam}: duplicate tokens"
    found = {}
    if want:
        ws = set(want)
        if fam == "4w":   # parse instead of enumerating 75 million combinations
            for t in ws:
                c = gn.parse_4w(t)
                if gn.survives_4w(es, c) is None and es.token(fam, c) == t: found[t] = c
        else:
            for c, r in es.space(fam):
                t = es.token(fam, c).split("/")[0]
                if r is None and t in ws: found[t] = c
        missing = ws - set(found); assert not missing, f"{fam}: not survivors of enum_space: {sorted(missing)[:5]}"
    by = {px: [] for px in tmpl}
    for t in want: by[prefix(fam, found[t])].append(t)
    for px, (src, new) in tmpl.items():
        for ext in ("glsl", "yaml"): (g / f"{new}.{ext}").unlink(missing_ok=True)
        if not by[px]: continue
        text = (g / f"{src}.glsl").read_text()
        (g / f"{new}.glsl").write_text(text[:text.index("#version 450 core")].rstrip() +
            f"\n\n// 780m: generated by gen_space.py from {src}.glsl (same text from the version directive on).\n\n" +
            text[text.index("#version 450 core"):])
        y = next(iter(yaml.safe_load((g / f"{src}.yaml").read_text()).values()))
        linear = fam in ("4w", "8da4w"); variants = []
        for t in by[px]:
            c = found[t]; base = f"{new}_{t[len(px):]}"
            v = {"NAME": base + ("_texture3d_texture2d_half" if linear else "")}
            if linear: v["IO_STORAGE"] = "texture3d"; v["WEIGHT_STORAGE"] = "texture2d"
            for k, val in params(fam, c).items():
                assert k in y["parameter_names_with_default_values"], f"{src}.yaml has no parameter {k}"
                v[k] = val
            variants.append(v)
            M, N, K, X, Y, S = c["g"]; mm = c.get("mma", (16,))[0]; fl = c.get("f", {})
            b = lambda k: "true" if fl.get(k) else "false"
            rows.append(f'{{"", nullptr, Op::{OP[fam]}, "{base}", {{{M}, {N}, {K}, {X}, {Y}, {S}, {mm}, {b("CSH_IN_ASH")}, '
                        f'{b("CSH_FULL")}, {b("CSH_POOL")}}}, {"kTex3dTex2d" if linear else "kBufBuf"}, nullptr, Status::kUnverified}},')
        y["shader_variants"] = variants
        (g / f"{new}.yaml").write_text(f"# 780m: generated by gen_space.py from {src}.yaml. Not shipped.\n\n" +
                                       yaml.safe_dump({new: y}, sort_keys=False, width=200))
        counts[new] = len(variants)
assert rows, "empty selection: Space780m.inc needs at least one row"
inc.write_text("// 780m: generated by openspec/changes/sarc-1.5-780m-prefill-refine/tools/gen_space.py. Do not edit.\n" + "\n".join(rows) + "\n")
for k, v in counts.items(): print(f"{k}: {v} variants")
print(f"Space780m.inc: {len(rows)} rows")
