#!/usr/bin/env python3
"""Generate the measurement-only phase-timing (PROF) twins of the 780M linear kernels in the dev zone.

usage: gen_prof.py <executorch tree>

Reads the release bodies and the sweep wrappers (never writes them) and writes new files under
glsl/sarc_dev/: sarc_dev_prof_q4gsw{.glsl,.yaml,_body.glslh} and sarc_dev_prof_dq8ca_zpg{...}.
Each wave keeps one running shader-clock timestamp (VK_KHR_shader_clock, 20-bit cycle counter); PTICK(x)
adds the cycles since the previous tick to phase x. Subgroup 0 of every workgroup overwrites the first two
output texels (8 elements) of its tile with
  [barrier, fetch, mma, lds_store] / iterations   and   [prologue, group_epilog, drain, write] / 64.
The outputs of these kernels are therefore wrong by construction; they are never selected by default.
"""
import pathlib, sys

root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops/glsl"

def sub(text, old, new, count=1, which=0):
    """Replace the `which`-th occurrence (0-based) of `old`; it must occur exactly `count` times."""
    n = text.count(old)
    assert n == count, f"anchor occurs {n} times, expected {count}: {old[:70]!r}"
    parts = text.split(old)
    return old.join(parts[: which + 1]) + new + old.join(parts[which + 1 :])

DECL = """void main() {
  // PROF (measurement only): per-phase shader-clock cycles of this wave.
  uint p_pro = 0u, p_bar = 0u, p_pre = 0u, p_mma = 0u, p_st = 0u, p_ep = 0u, p_dr = 0u, p_wr = 0u;
  uint p_t = clock2x32ARB().x;
#define PTICK(acc) { const uint p_n = clock2x32ARB().x; acc += (p_n - p_t) & 0xFFFFFu; p_t = p_n; }
"""
OUT = """
  // PROF output: subgroup 0 writes the phase means into the first 8 elements of its tile.
  PTICK(p_wr)
  {
    const float it = float(max(num_chunks, 1u));
    const vec4 v0 = vec4(float(p_bar), float(p_pre), float(p_mma), float(p_st)) / it;
    const vec4 v1 = vec4(float(p_pro), float(p_ep), float(p_dr), float(p_wr)) / 64.0;
#ifdef IO_TEXTURE
    memoryBarrierImage();
    barrier();
    if (gl_SubgroupID == 0u && subgroupElect()) {
      imageStore(t_output, ivec3(tile_n_start / 4u, tile_m_start, 0), v0);
      imageStore(t_output, ivec3(tile_n_start / 4u + 1u, tile_m_start, 0), v1);
    }
#else
    memoryBarrierBuffer();
    barrier();
    if (gl_SubgroupID == 0u && subgroupElect()) {
      const uint pb = tile_m_start * uint(out_N_arg) + tile_n_start;
      [[unroll]] for (uint c = 0; c < 4u; ++c) {
        t_output[pb + c] = float16_t(v0[c]);
        t_output[pb + 4u + c] = float16_t(v1[c]);
      }
    }
#endif
  }
}
"""

# ---------------- 4w ----------------
b = (root / "sarc/sarc_linear_q4gsw_coopmat_body.glslh").read_text()
b = b.replace("SARC_LINEAR_Q4GSW_COOPMAT_BODY_GLSLH", "SARC_DEV_PROF_Q4GSW_BODY_GLSLH")
b = sub(b, "void main() {\n", DECL)
b = sub(b, "  uint chunk;\n  for (chunk = 0; chunk + 1u < num_chunks; ++chunk) {",
        "  PTICK(p_pro)\n  uint chunk;\n  for (chunk = 0; chunk + 1u < num_chunks; ++chunk) {")
b = sub(b, "    memoryBarrierShared();\n    barrier();\n\n    // --- prefetch chunk+1 -> temp ---",
        "    memoryBarrierShared();\n    barrier();\n    PTICK(p_bar)\n\n    // --- prefetch chunk+1 -> temp ---")
b = sub(b, "    // --- MMA math on the cur slice ---", "    PTICK(p_pre)\n    // --- MMA math on the cur slice ---")
b = sub(b, "    // --- store temp (chunk+1) -> nxt slice, dequantizing B ---",
        "    PTICK(p_mma)\n    // --- store temp (chunk+1) -> nxt slice, dequantizing B ---")
b = sub(b, "    }\n  }\n\n  // --- epilogue: barrier, then MMA on the last chunk (loop peeled) ---",
        "    }\n    PTICK(p_st)\n  }\n\n  // --- epilogue: barrier, then MMA on the last chunk (loop peeled) ---")
b = sub(b, "    memoryBarrierShared();\n    barrier();\n\n    [[unroll]] for (uint k = 0; k < WG_TILE_K / MMA_K; ++k) {",
        "    memoryBarrierShared();\n    barrier();\n    PTICK(p_bar)\n\n    [[unroll]] for (uint k = 0; k < WG_TILE_K / MMA_K; ++k) {")
b = sub(b, "  // --- Bias staging (if any) ---", "  PTICK(p_mma)\n  // --- Bias staging (if any) ---")
# default texture drain (the CSH_IN_ASH / Csh band branch): drain = accumulator -> LDS, write = imageStore
b = sub(b, "    }\n    memoryBarrierShared();\n    barrier();\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {",
        "    }\n    memoryBarrierShared();\n    barrier();\n    PTICK(p_dr)\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {")
b = sub(b, "#endif\n    }\n  }\n#endif // CSH_FULL / CSH_BAND", "#endif\n    }\n    PTICK(p_wr)\n  }\n#endif // CSH_FULL / CSH_BAND")
b = sub(b, "#endif // IO_TEXTURE\n}\n", "#endif // IO_TEXTURE\n" + OUT)
(root / "sarc_dev/sarc_dev_prof_q4gsw_body.glslh").write_text(
    b.replace("// Body of sarc_linear_q4gsw_coopmat;", "// GENERATED by gen_prof.py (measurement only, never shipped). Body of sarc_linear_q4gsw_coopmat;", 1))

w = (root / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.glsl").read_text()
w = w[w.index("#version 450 core"):]
w = sub(w, "#extension GL_EXT_control_flow_attributes : enable\n",
        "#extension GL_EXT_control_flow_attributes : enable\n#extension GL_ARB_shader_clock : require\n")
w = sub(w, '#include "sarc_linear_q4gsw_coopmat_body.glslh"', '#include "sarc_dev_prof_q4gsw_body.glslh"')
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone, MEASUREMENT ONLY: phase-timing twin of %s
 * (generated by gen_prof.py; see openspec/changes/sarc-1.5-780m-prefill-refine). Its output is
 * overwritten with cycle counts, so it must never be selected for a model.
 */

"""
(root / "sarc_dev/sarc_dev_prof_q4gsw.glsl").write_text(HDR % "sarc_linear_q4gsw_coopmat" + w)
y = (root / "sarc_dev/sarc_linear_q4gsw_coopmat_sweep.yaml").read_text()
defaults = y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
YH = "# SARC development zone, MEASUREMENT ONLY (phase timing, generated by gen_prof.py). Never shipped.\n\n"
V4 = """  shader_variants:
    - NAME: sarc_dev_prof_q4gsw_t128x128k32g42s32f32cp_texture3d_texture2d_half
      IO_STORAGE: texture3d
      WG_TILE_K: 32
      SG_GRID_X: 4
      SG_GRID_Y: 2
      ACC_FP32: true
      CSH_IN_ASH: true
    - NAME: sarc_dev_prof_q4gsw_t128x128k32g42s32f32cp_buffer_texture2d_half
      WG_TILE_K: 32
      SG_GRID_X: 4
      SG_GRID_Y: 2
      ACC_FP32: true
      CSH_IN_ASH: true
"""
(root / "sarc_dev/sarc_dev_prof_q4gsw.yaml").write_text(YH + "sarc_dev_prof_q4gsw:\n" + defaults + V4)

# ---------------- 8da4w zpg ----------------
b = (root / "sarc/sarc_linear_dq8ca_coopmat_zpg_body.glslh").read_text()
b = b.replace("SARC_LINEAR_DQ8CA_COOPMAT_ZPG_BODY_GLSLH", "SARC_DEV_PROF_DQ8CA_ZPG_BODY_GLSLH")
b = sub(b, "void main() {\n", DECL)
b = sub(b, "  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {",
        "  PTICK(p_pro)\n  uint chunk = 0;\n  for (uint group_i = 0; group_i < num_groups; ++group_i) {")
b = sub(b, "      memoryBarrierShared();\n      barrier();\n\n      // --- 2. prefetch chunk+1 -> temp ---",
        "      memoryBarrierShared();\n      barrier();\n      PTICK(p_bar)\n\n      // --- 2. prefetch chunk+1 -> temp ---")
b = sub(b, "      // --- 3. int8 MMA on the cur slice ---", "      PTICK(p_pre)\n      // --- 3. int8 MMA on the cur slice ---")
b = sub(b, "      // --- 4. store temp (chunk+1) -> nxt slice ---", "      PTICK(p_mma)\n      // --- 4. store temp (chunk+1) -> nxt slice ---")
b = sub(b, "    }  // chunks", "      PTICK(p_st)\n    }  // chunks")
b = sub(b, "  }  // groups", "    PTICK(p_ep)\n  }  // groups")
b = sub(b, "  // --- Bias (optional) ---", "  PTICK(p_ep)\n  // --- Bias (optional) ---")
b = sub(b, "    }\n    memoryBarrierShared();\n    barrier();\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {",
        "    }\n    memoryBarrierShared();\n    barrier();\n    PTICK(p_dr)\n\n    for (uint t = gl_LocalInvocationID.x; t < CSH_TEXELS; t += WG_SIZE) {")
b = sub(b, "              float(Csh_out[base + 3u])));\n    }\n  }\n#else",
        "              float(Csh_out[base + 3u])));\n    }\n    PTICK(p_wr)\n  }\n#else")
b = sub(b, "#endif // IO_TEXTURE\n}\n", "#endif // IO_TEXTURE\n" + OUT)
(root / "sarc_dev/sarc_dev_prof_dq8ca_zpg_body.glslh").write_text(
    b.replace("// Body of sarc_linear_dq8ca_coopmat_zpg;", "// GENERATED by gen_prof.py (measurement only, never shipped). Body of sarc_linear_dq8ca_coopmat_zpg;", 1))
w = (root / "sarc_dev/sarc_linear_dq8ca_coopmat_zpg_sweep.glsl").read_text()
w = w[w.index("#version 450 core"):]
w = sub(w, "#extension GL_EXT_control_flow_attributes : enable\n",
        "#extension GL_EXT_control_flow_attributes : enable\n#extension GL_ARB_shader_clock : require\n")
w = sub(w, '#include "sarc_linear_dq8ca_coopmat_zpg_body.glslh"', '#include "sarc_dev_prof_dq8ca_zpg_body.glslh"')
(root / "sarc_dev/sarc_dev_prof_dq8ca_zpg.glsl").write_text(HDR % "sarc_linear_dq8ca_coopmat_zpg" + w)
y = (root / "sarc_dev/sarc_linear_dq8ca_coopmat_zpg_sweep.yaml").read_text()
defaults = y[y.index("  parameter_names_with_default_values:"):y.index("  shader_variants:")]
V8 = """  shader_variants:
    - NAME: sarc_dev_prof_dq8ca_zpg_t128x64k32g42s32p_texture3d_texture2d_half
      IO_STORAGE: texture3d
      A_MAP_FULL: true
    - NAME: sarc_dev_prof_dq8ca_zpg_t128x64k32g42s32p_buffer_texture2d_half
      A_MAP_FULL: true
"""
(root / "sarc_dev/sarc_dev_prof_dq8ca_zpg.yaml").write_text(YH + "sarc_dev_prof_dq8ca_zpg:\n" + defaults + V8)
print("generated", sorted(p.name for p in (root / "sarc_dev").glob("sarc_dev_prof_*")))
