#!/usr/bin/env python3
"""gen_rx7600_q4.py: writes glsl/sarc_dev/sarc_dev_rx7600_x_linear_q4gsw_coopmat.yaml and impl/sarc_dev/SpaceRx7600Q4.inc from one table of
variants (round 2, candidate 2: 4w). Run from the repository root. Suffix bpN = BT_PAD_H N (padding in fp16 of a row of the column-major B staging;
the row pitch is 32 + N fp16), gXY = SG_GRID_X x SG_GRID_Y of the 256 x 128 tile, cbt = column-major B staging with fp32 accumulation."""
G = "backends/vulkan/runtime/graph/ops/glsl/sarc_dev/sarc_dev_rx7600_x_linear_q4gsw_coopmat.yaml"
I = "backends/vulkan/runtime/graph/ops/impl/sarc_dev/SpaceRx7600Q4.inc"
FAM = "sarc_dev_rx7600_x_linear_q4gsw_coopmat"
HEAD = f"""# SARC development zone, RX 7600 campaign round 2: the 4w coopmat linear (release body copy) with options, default off.
# GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_q4.py; do not edit. Not shipped.

{FAM}:
  parameter_names_with_default_values:
    PRECISION: highp
    HAS_BIAS: false
    IO_STORAGE: texture3d
    WEIGHT_STORAGE: texture2d
    MMA_M: 16
    MMA_N: 16
    MMA_K: 16
    WG_TILE_M: 256
    WG_TILE_N: 128
    WG_TILE_K: 32
    SG_GRID_X: 2
    SG_GRID_Y: 8
    SUBGROUP_SIZE: 32
    ACC_FP32: true
    CSH_IN_ASH: true
    ACC_GROUP_FP32: false
    ACC_GROUP_FP32_REG: false
    FRAG_LAYOUT: false
    IMG_A: false
    IMG_W: false
    SH_F16V4: false
    CSH_BAND: false
    B_COLMAJOR: true
    CSH_FULL: false
    CSH_POOL: false
    BT_PAD_H: 8
  shader_variants:
"""
V = []
def row(suffix, gx, gy, pad):
    V.append((suffix, gx, gy, pad))
for gx, gy in ((2, 8), (2, 4)):
    base = f"t256x128k32g{gx}{gy}s32f32cbt"
    row(base, gx, gy, 8)
    for pad in (4, 12):
        row(f"{base}bp{pad}", gx, gy, pad)
y = HEAD
inc = "// GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_q4.py. Do not edit.\n"
for s, gx, gy, pad in V:
    base = f"{FAM}_{s}"
    y += f"    - NAME: {base}_texture3d_texture2d_half\n"
    if (gx, gy) != (2, 8): y += f"      SG_GRID_X: {gx}\n      SG_GRID_Y: {gy}\n"
    if pad != 8: y += f"      BT_PAD_H: {pad}\n"
    inc += (f'{{"", nullptr, Op::kQ4gswLinear, "{base}", {{256, 128, 32, {gx}, {gy}, 32, 16, true, false, false}}, '
            f'kTex3dTex2d, nullptr, Status::kUnverified}},\n')
open(G, "w").write(y); open(I, "w").write(inc)
print(len(V), "variants")
