#!/usr/bin/env python3
"""gen_rx7600_dq.py: writes glsl/sarc_dev/sarc_dev_rx7600_x_linear_dq8ca_coopmat_zpg.yaml and impl/sarc_dev/SpaceRx7600Dq.inc from one table
of variants (round 2, candidate 1: 8da4w). Run from the repository root: python3 -I <this file>. Name suffixes: paN / pbN = row pitch N uint of the A / B staging; padN = A_PAD N; csha = drain tile in the A staging buffer; gXY = SG_GRID_X x SG_GRID_Y;
uv4 = uvec4 shared staging arrays; bf = branch-free chunk loop; aXbY = the stores of
the next chunk's A / B staging after K slab X / Y of the current chunk's MMAs (need bf); p = phase timing twin and ablN = removed work (both
MEASUREMENT ONLY, wrong results by design). The family name contains 'coopmat' because test_llama_microbench classifies a kernel by it."""
G = "backends/vulkan/runtime/graph/ops/glsl/sarc_dev/sarc_dev_rx7600_x_linear_dq8ca_coopmat_zpg.yaml"
I = "backends/vulkan/runtime/graph/ops/impl/sarc_dev/SpaceRx7600Dq.inc"
FAM = "sarc_dev_rx7600_x_linear_dq8ca_coopmat_zpg"
HEAD = f"""# SARC development zone, RX 7600 campaign round 2: the shipped 8da4w zpg kernel (release body copy) with options, default off.
# GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_dq.py; do not edit. Not shipped. Candidate kernels
# are selected by the rx7600 profiles in impl/sarc_dev/Overrides.cpp; the measurement-only variants (suffix p = phase timing,
# ablN = removed work; they write wrong results by design) only by exact name (ET_VK_SARC_780M_DQ).

{FAM}:
  parameter_names_with_default_values:
    PRECISION: highp
    HAS_BIAS: false
    IO_STORAGE: texture3d
    WEIGHT_NBITS: 4
    WEIGHT_STORAGE: texture2d
    A_MAP_FULL: true
    A_MULTI_BLOCK: true
    A_BLOCKS: 1
    A_PAD: 0
    CSH_IN_ASH: false
    BF: false
    UV4: false
    A_PITCH: 4
    B_PITCH: 4
    ST_A: -1
    ST_B: -1
    PROF: false
    ABL: 0
    MMA_M: 16
    MMA_N: 16
    MMA_K: 16
    WG_TILE_M: 256
    WG_TILE_N: 64
    WG_TILE_K: 64
    SG_GRID_X: 4
    SG_GRID_Y: 8
    SUBGROUP_SIZE: 32
  shader_variants:
"""
# one row per variant: suffix, grid X, grid Y, A_BLOCKS, BF, ST_A, ST_B, UV4, PROF, ABL, A_PAD, CSH_IN_ASH, A_PITCH, B_PITCH
V = []
def row(suffix, gx=4, gy=8, ab=1, bf=False, sa=-1, sb=-1, uv4=False, prof=False, abl=0, pad=0, csha=False, pa=4, pb=4):
    V.append((suffix, gx, gy, ab, bf, sa, sb, uv4, prof, abl, pad, csha, pa, pb))
B48 = "t256x64k64g48s32"
row(B48)                                   # the shipped kernel's copy (SPIR-V identical to afmb1)
row(B48 + "bf", bf=True)
# row pitch (uint, 4 = 16 bytes) of the A / B staging in shared memory, drain tile in the A buffer (csha) so that the total stays under 64 KiB
# (8192 * pa + 2048 * pb + 2816 bytes)
for pa in (4, 5, 6):
    for pb in (4, 5, 6, 7, 8):
        if 8192 * pa + 2048 * pb + 2816 <= 65536:
            row(f"{B48}pa{pa}pb{pb}csha", pa=pa, pb=pb, csha=True)
row(B48 + "pa6pb4cshabf", pa=6, csha=True, bf=True)
row(B48 + "pa6pb4cshap", pa=6, csha=True, prof=True)
for a in (7, 23, 32, 39, 48, 55):          # measurement only (see the body header): 7 = no staging, 16 = no barrier, 32 = fragments of slab 0 reused
    row(f"{B48}abl{a}", abl=a)
y = HEAD
inc = "// GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_dq.py. Do not edit.\n"
for s, gx, gy, ab, bf, sa, sb, uv4, prof, abl, pad, csha, pa, pb in V:
    base = f"{FAM}_{s}"
    y += f"    - NAME: {base}_texture3d_texture2d_half\n"
    if (gx, gy) != (4, 8): y += f"      SG_GRID_X: {gx}\n      SG_GRID_Y: {gy}\n"
    if ab != 1: y += f"      A_BLOCKS: {ab}\n"
    if pad: y += f"      A_PAD: {pad}\n"
    if csha: y += "      CSH_IN_ASH: true\n"
    if pa != 4: y += f"      A_PITCH: {pa}\n"
    if pb != 4: y += f"      B_PITCH: {pb}\n"
    if bf: y += "      BF: true\n"
    if sa >= 0: y += f"      ST_A: {sa}\n"
    if sb >= 0: y += f"      ST_B: {sb}\n"
    if uv4: y += "      UV4: true\n"
    if prof: y += "      PROF: true\n"
    if abl: y += f"      ABL: {abl}\n"
    inc += (f'{{"", nullptr, Op::kDq8caLinear, "{base}", {{256, 64, 64, {gx}, {gy}, 32, 16, {"true" if csha else "false"}, false, false}}, '
            f'kTex3dTex2d, nullptr, Status::kUnverified}},\n')
open(G, "w").write(y); open(I, "w").write(inc)
print(len(V), "variants")
