#!/usr/bin/env python3
"""gen_rx7600_dq.py: writes glsl/sarc_dev/sarc_dev_rx7600_x_linear_dq8ca_coopmat_zpg.yaml and impl/sarc_dev/SpaceRx7600Dq.inc from one table
of variants (round 2, candidate 1: 8da4w). Run from the repository root: python3 -I <this file>. Name suffixes: gXY = SG_GRID_X x SG_GRID_Y;
uv4 = uvec4 shared staging arrays; bf = branch-free chunk loop; aXbY = the stores of
the next chunk's A / B staging after K slab X / Y of the current chunk's MMAs (need bf); p = phase timing twin and ablN = removed work (both
MEASUREMENT ONLY, wrong results by design). The family name contains 'coopmat' because test_llama_microbench classifies a kernel by it."""
G = "backends/vulkan/runtime/graph/ops/glsl/sarc_dev/sarc_dev_rx7600_x_linear_dq8ca_coopmat_zpg.yaml"
I = "backends/vulkan/runtime/graph/ops/impl/sarc_dev/SpaceRx7600Dq.inc"
FAM = "sarc_dev_rx7600_x_linear_dq8ca_coopmat_zpg"
HEAD = f"""# SARC development zone, RX 7600 campaign round 2: the shipped 8da4w zpg kernel (release body copy) with options, default off.
# GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_dq.py; do not edit. Not shipped. Candidate kernels
# are selected by the rx7600 profiles in impl/sarc_dev/Overrides.cpp; the measurement-only variants (suffix p = phase timing,
# ablN = removed work; they write wrong results by design) only by exact name (ET_VK_SARC_780M_DQ).

{FAM}:
  parameter_names_with_default_values:
    PRECISION: highp
    HAS_BIAS: false
    IO_STORAGE: texture3d
    WEIGHT_NBITS: 4
    WEIGHT_STORAGE: texture2d
    A_MAP_FULL: true
    A_MULTI_BLOCK: true
    A_BLOCKS: 1
    A_PAD: 0
    CSH_IN_ASH: false
    BF: false
    UV4: false
    ST_A: -1
    ST_B: -1
    PROF: false
    ABL: 0
    MMA_M: 16
    MMA_N: 16
    MMA_K: 16
    WG_TILE_M: 256
    WG_TILE_N: 64
    WG_TILE_K: 64
    SG_GRID_X: 4
    SG_GRID_Y: 8
    SUBGROUP_SIZE: 32
  shader_variants:
"""
# one row per variant: suffix, grid X, grid Y, A_BLOCKS, BF, ST_A, ST_B, UV4, PROF, ABL
V = []
def row(suffix, gx=4, gy=8, ab=1, bf=False, sa=-1, sb=-1, uv4=False, prof=False, abl=0):
    V.append((suffix, gx, gy, ab, bf, sa, sb, uv4, prof, abl))
B48 = "t256x64k64g48s32"
row(B48)                                   # the shipped kernel's copy (SPIR-V identical to afmb1)
row(B48 + "bf", bf=True)
for a, b in ((1, 1), (1, 2), (2, 2)):
    row(f"{B48}bfa{a}b{b}", bf=True, sa=a, sb=b)
row(B48 + "uv4abl4", uv4=True, abl=4)      # measurement only: aligned fragment loads, no stores
row(B48 + "uv4", uv4=True)
# smaller workgroups (more registers per wave, bigger tile per wave); A_BLOCKS = 1024 / workgroup size
for gx, gy in ((4, 4), (2, 8), (2, 4), (4, 2)):
    ab = 1024 // (gx * gy * 32)
    row(f"t256x64k64g{gx}{gy}s32", gx, gy, ab)
    row(f"t256x64k64g{gx}{gy}s32uv4", gx, gy, ab, uv4=True)
for gx, gy in ((4, 4), (2, 8)):
    ab = 1024 // (gx * gy * 32)
    row(f"t256x64k64g{gx}{gy}s32p", gx, gy, ab, prof=True)
y = HEAD
inc = "// GENERATED by openspec/changes/sarc-1.5-rx7600-prefill-refine/tools/gen_rx7600_dq.py. Do not edit.\n"
for s, gx, gy, ab, bf, sa, sb, uv4, prof, abl in V:
    base = f"{FAM}_{s}"
    y += f"    - NAME: {base}_texture3d_texture2d_half\n"
    if (gx, gy) != (4, 8): y += f"      SG_GRID_X: {gx}\n      SG_GRID_Y: {gy}\n"
    if ab != 1: y += f"      A_BLOCKS: {ab}\n"
    if bf: y += "      BF: true\n"
    if sa >= 0: y += f"      ST_A: {sa}\n"
    if sb >= 0: y += f"      ST_B: {sb}\n"
    if uv4: y += "      UV4: true\n"
    if prof: y += "      PROF: true\n"
    if abl: y += f"      ABL: {abl}\n"
    inc += (f'{{"", nullptr, Op::kDq8caLinear, "{base}", {{256, 64, 64, {gx}, {gy}, 32, 16, false, false, false}}, '
            f'kTex3dTex2d, nullptr, Status::kUnverified}},\n')
open(G, "w").write(y); open(I, "w").write(inc)
print(len(V), "variants")
