#!/usr/bin/env python3
"""Candidate 3 (B, SDPA prefill): dev-zone sweep twins of the SARC QK^T and attn*V kernels.

usage: gen_sdpa.py <executorch tree>

QK^T (sarc_sdpa_qk_coopmat_sweep): the release shader with a NO_MASK_FILL parameter. In LLM mode the consumer of
attn_weights is sarc_sdpa_attn_weights_softmax, which reads row s only up to c = s + input_pos (reduce_len), so
  - a tile that is entirely above the causal diagonal is never read: with NO_MASK_FILL it is not written
    (the release shader fills it with -inf, 8192 scalar fp16 stores per tile, 240 of 512 tiles at 2048);
  - the masked elements of a diagonal tile are never read either: with NO_MASK_FILL a diagonal tile takes the
    direct coopMatStore path instead of the Csh round trip with the per-element mask.
The softmax output, and everything after it, is unchanged bit for bit; only never-read attn_weights elements
differ. NO_MASK_FILL is only valid together with the truncated softmax (devices with an SDPA row).
attn*V (sarc_sdpa_av_coopmat_sweep): the release shader unchanged, for subgroup-32 tiles.
Kernel names keep the sarc_sdpa_qk_ / sarc_sdpa_av_ prefixes that impl/sarc/SdpaCoopmat.cpp:sdpa_gwg keys on,
and WG_TILE_K stays 32 (the spec constants come from the table row).
"""
import pathlib, sys
root = pathlib.Path(sys.argv[1]) / "backends/vulkan/runtime/graph/ops"
g = root / "glsl"
def sub(text, old, new, count=1):
    n = text.count(old); assert n == count, f"anchor occurs {n} times: {old[:60]!r}"
    return text.replace(old, new)
HDR = """/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * SARC development zone: sweep twin of glsl/sarc/%s.glsl (generated by gen_sdpa.py;
 * openspec/changes/sarc-1.5-780m-prefill-refine).%s
 */

"""
q = (g / "sarc/sarc_sdpa_qk_coopmat.glsl").read_text()
q = q[q.index("#version 450 core"):]
q = sub(q, "#define PRECISION ${PRECISION}\n", """#define PRECISION ${PRECISION}

// NO_MASK_FILL: do not write attn_weights elements that the truncated softmax
// never reads (c > s + input_pos). Valid only with sarc_sdpa_attn_weights_softmax.
$if NO_MASK_FILL:
  #define NO_MASK_FILL
""")
q = sub(q, """    const bool tile_all_visible =
        tile_in_extent && aw_stride_is_static &&
        (int(c_tile_base) + int(WG_TILE_N) - 1 <= int(s_tile_base) + input_pos);
""", """#ifdef NO_MASK_FILL
    // A diagonal tile's masked elements are never read, so it needs no mask:
    // every executed tile takes the direct store.
    const bool tile_all_visible = tile_in_extent && aw_stride_is_static;
#else
    const bool tile_all_visible =
        tile_in_extent && aw_stride_is_static &&
        (int(c_tile_base) + int(WG_TILE_N) - 1 <= int(s_tile_base) + input_pos);
#endif
""")
q = sub(q, "    if (tile_all_masked) {\n        for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * WG_TILE_N;",
        "    if (tile_all_masked) {\n#ifdef NO_MASK_FILL\n        return;\n#endif\n        for (uint idx = gl_LocalInvocationID.x; idx < WG_TILE_M * WG_TILE_N;")
(g / "sarc_dev/sarc_sdpa_qk_coopmat_sweep.glsl").write_text(HDR % ("sarc_sdpa_qk_coopmat", "\n * Adds NO_MASK_FILL (see the define below); identical otherwise.") + q)
def yaml(name, extra_default, cache, variants):
    out = f"# SARC development zone: {name} sweep candidates (generated by gen_sdpa.py). Not shipped.\n\n{name}_sweep:\n"
    out += f"  parameter_names_with_default_values:\n    DTYPE: half\n    PRECISION: highp\n    IO_STORAGE: buffer\n    {cache}: buffer\n    MMA_M: 16\n    MMA_N: 16\n    MMA_K: 16\n"
    out += f"    WG_TILE_M: {variants[0][1]}\n    WG_TILE_N: {variants[0][2]}\n    WG_TILE_K: 32\n    SG_GRID_X: 2\n    SG_GRID_Y: 2\n    SUBGROUP_SIZE: 64\n{extra_default}"
    out += f"  generate_variant_forall:\n    combination:\n      parameter_names: [IO_STORAGE, {cache}]\n      combos:\n        - parameter_values: [buffer, buffer]\n    DTYPE:\n      - VALUE: half\n  shader_variants:\n"
    for tok, m, n, sx, sy, sg, nf in variants:
        out += f"    - NAME: {name}_sweep_{tok}\n      WG_TILE_M: {m}\n      WG_TILE_N: {n}\n      WG_TILE_K: 32\n      SG_GRID_X: {sx}\n      SG_GRID_Y: {sy}\n      SUBGROUP_SIZE: {sg}\n"
        if nf: out += "      NO_MASK_FILL: true\n"
    return out
# (token, M, N, sgx, sgy, subgroup, no_mask_fill); LDS = Ash + Bsh + Csh fp16
QK = [("t128x64k32g22s64nf", 128, 64, 2, 2, 64, True), ("t128x64k32g42s32nf", 128, 64, 4, 2, 32, True),
      ("t128x64k32g42s32", 128, 64, 4, 2, 32, False), ("t128x64k32g24s32nf", 128, 64, 2, 4, 32, True),
      ("t128x64k32g22s32nf", 128, 64, 2, 2, 32, True)]
for tok, m, n, sx, sy, sg, nf in QK:
    assert 2 * (m * 40 + 32 * (n + 8) + m * n) <= 60000, tok
(g / "sarc_dev/sarc_sdpa_qk_coopmat_sweep.yaml").write_text(yaml("sarc_sdpa_qk_coopmat", "    NO_MASK_FILL: false\n", "K_CACHE_STORAGE", QK))
a = (g / "sarc/sarc_sdpa_av_coopmat.glsl").read_text()
a = a[a.index("#version 450 core"):]
(g / "sarc_dev/sarc_sdpa_av_coopmat_sweep.glsl").write_text(HDR % ("sarc_sdpa_av_coopmat", " Identical from #version on.") + a)
# attn*V stages A and B in a single pass: WG_SIZE == 4 * WG_TILE_M and WG_SIZE == WG_TILE_K * WG_TILE_N / 8.
AV = [("t64x64k32g42s32", 64, 64, 4, 2, 32, False), ("t64x64k32g24s32", 64, 64, 2, 4, 32, False)]
for tok, m, n, sx, sy, sg, nf in AV:
    assert sx * sy * sg == 4 * m == 32 * n // 8, tok
(g / "sarc_dev/sarc_sdpa_av_coopmat_sweep.yaml").write_text(yaml("sarc_sdpa_av_coopmat", "", "V_CACHE_STORAGE", AV))
o = root / "impl/sarc_dev/Overrides.cpp"; t = o.read_text()
if "sarc_sdpa_qk_coopmat_sweep" not in t:
    a = "};\n\nstd::string& requested_variant() {"
    rows = "    // 780M prefill refine 2026-10-03, candidate 3 (SDPA): glsl/sarc_dev/sarc_sdpa_{qk,av}_coopmat_sweep.yaml.\n    // Selected only through ET_VK_SARC_DEV_PROFILE.\n"
    for tok, m, n, sx, sy, sg, nf in QK:
        rows += f'    {{"", nullptr, Op::kSdpaQk,\n     "sarc_sdpa_qk_coopmat_sweep_{tok}",\n     {{{m}, {n}, 32, {sx}, {sy}, {sg}, 16, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n'
    for tok, m, n, sx, sy, sg, nf in AV:
        rows += f'    {{"", nullptr, Op::kSdpaAv,\n     "sarc_sdpa_av_coopmat_sweep_{tok}",\n     {{{m}, {n}, 32, {sx}, {sy}, {sg}, 16, false}}, kBufBuf, nullptr,\n     Status::kUnverified}},\n'
    t = sub(t, a, rows + a)
    a = "struct Profile {\n"
    prefs = ""
    for tok, *_ in QK:
        prefs += f'const Preference kQk_{tok}[] = {{{{Op::kSdpaQk, "{tok}", nullptr}}}};\n'
    for tok, *_ in AV:
        prefs += f'const Preference kAv_{tok}[] = {{{{Op::kSdpaAv, "{tok}", nullptr}}}};\n'
    t = sub(t, a, "// Single-kernel SDPA screening profiles (qk-<tile>, av-<tile>).\n" + prefs + a)
    a = '    {"780m-refine1-dq",'
    ent = ""
    for tok, *_ in QK: ent += f'    {{"qk-{tok}", kQk_{tok}, 1}},\n'
    for tok, *_ in AV: ent += f'    {{"av-{tok}", kAv_{tok}, 1}},\n'
    t = sub(t, a, ent + a)
    o.write_text(t)
print("sdpa sweep twins generated")
